- CodeSniffer/Standards/PEAR/Sniffs/Commenting/FunctionCommentSniff.php
- CodeSniffer/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc
- CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- CodeSniffer/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
The removed code was used to compare the class name with the method name to skip PHP4 constructors.
> [CLEANUP] Remove legacy code for PHP4 constructors

- CodeSniffer/Standards/Generic/Sniffs/Commenting/DocCommentSniff.php
Since the sniff registers the T_DOC_COMMENT_OPEN_TAG there is no need to use the findNext() method to get the end of the comment. The comment end tag is stored into the open tag token.
> [FEATURE] Improve the doc comment detection.

- CodeSniffer/Standards/Squiz/Sniffs/ControlStructures/ForLoopDeclarationSniff.php
The "SpacingBeforeClose" error in the "Squiz.ControlStructures.ForLoopDeclaration" sniff has non-replaced "%s" in it:
```
Expected %s spaces before closing bracket; %s found 
```
This PR replaces them with actual values.
> Replace "%s" in "Squiz.ControlStructures.ForLoopDeclaration.SpacingBeforeClose" error

- CodeSniffer/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php
After commit https://github.com/squizlabs/PHP_CodeSniffer/commit/22060b65a3cb54a49011d87fd90cb3dac5388746 rules named **PEAR.Commenting.FileComment.MissingTag** and **PEAR.Commenting.ClassComment.MissingTag** was splitted into many per tag name (category, package, author, license and link).
In version 2.1.0 to exclude requirements for this tags in ruleset.xml is required to write:
```
<rule ref="PEAR.Commenting.FileComment">
<exclude name="PEAR.Commenting.FileComment.Missing@categoryTag"/>
<exclude name="PEAR.Commenting.FileComment.Missing@packageTag"/>
<exclude name="PEAR.Commenting.FileComment.Missing@authorTag"/>
<exclude name="PEAR.Commenting.FileComment.Missing@licenseTag"/>
<exclude name="PEAR.Commenting.FileComment.Missing@linkTag"/>
</rule>
<rule …
```
> Fixup code for rule: missing tag

- CodeSniffer/Standards/PSR2/ruleset.xml
Fixing indentation for `<properties>` tag in Squiz.WhiteSpace.SuperfluousWhitespace rule.
> Fix indentation in PSR2 Ruleset

- composer.json
As a few reporters uses the XMLWriter extension. I suggest to add this in composer.json to warn users as soon as possible
> PHP_CodeSniffer should depends on the XMLWriter extension

- CodeSniffer/Reports/Json.php
The code should follow same syntax in the whole file. You should not use PHP variables inside double quoted string.
Using this syntax  "$param{" causes an inspection error:
Expected: right double quote | Expecting statement
a) Concatenate string
b) Escape bracket: "$param\\{"
I have made a PR for version a
> Fix Inspection Error

- CodeSniffer/DocGenerators/HTML.php
Instate of switching to a high error reporting level switch back to last error reporting level
> switch back to the original error_reporting level

- CodeSniffer/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php
- CodeSniffer/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.inc.fixed
When using `phpcbf` with `Generic.ControlStructures.InlineControlStructure` on the following code:
```php
<label><input type="radio" <?php if($series) echo 'checked="checked"' ?> > By Series</label>
```
it was transformed into the following which is ***not valid*** PHP
```php
<label><input type="radio" <?php if($series) { echo 'checked="checked"' } ?> > By Series</label>
```
I have altered the correction to include a semicolon if the end is not one.
> Generic InlineControlStructureSniff can correct with missing semicolon

- CodeSniffer/Standards/Generic/Sniffs/NamingConventions/CamelCapsFunctionNameSniff.php
- CodeSniffer/Standards/PEAR/Sniffs/NamingConventions/ValidFunctionNameSniff.php
> Fix: Remove duplicate key-value-pair from magic methods array

- CodeSniffer/Standards/PSR1/Sniffs/Methods/CamelCapsMethodNameSniff.php
- CodeSniffer/Standards/PSR1/Tests/Methods/CamelCapsMethodNameUnitTest.inc
- CodeSniffer/Standards/PSR1/Tests/Methods/CamelCapsMethodNameUnitTest.php
> Fix: PSR1_Sniffs_Methods_CamelCapsMethodNameSniff and magic method detections

- composer.json
When in 32dd78e5bc2d512e89aaaf1ac0870404df854041 commit the `branch-alias` setting was removed from `composer.json` the versions like `~2.0@dev` stopped working.
> Adding back "branch-alias" setting that points to "master" branch

- src/Config.php
- src/Reports/Notifysend.php
- src/Standards/Generic/Sniffs/Debug/CSSLintSniff.php
- src/Standards/Generic/Sniffs/Debug/ClosureLinterSniff.php
- src/Standards/Generic/Sniffs/Debug/JSHintSniff.php
- src/Standards/Generic/Sniffs/PHP/SyntaxSniff.php
- src/Standards/Generic/Tests/PHP/SyntaxUnitTest.php
- src/Standards/Squiz/Sniffs/Debug/JSLintSniff.php
- src/Standards/Squiz/Sniffs/Debug/JavaScriptLintSniff.php
- src/Standards/Squiz/Tests/Debug/JSLintUnitTest.php
- src/Standards/Squiz/Tests/Debug/JavaScriptLintUnitTest.php
- src/Standards/Zend/Sniffs/Debug/CodeAnalyzerSniff.php
- src/Standards/Zend/Tests/Debug/CodeAnalyzerUnitTest.php
See https://github.com/squizlabs/PHP_CodeSniffer/issues/541. Alternatively, the approach used in [symfony/process](https://github.com/symfony/Process/blob/master/ExecutableFinder.php) could be used, however it's much more complex than just calling a shell command.
> Automatic discovery of executable paths

- CodeSniffer/Standards/Squiz/Tests/CSS/SemicolonSpacingUnitTest.css
- CodeSniffer/Tokenizers/CSS.php
Apparently :hover exists in CSS and confuses a couple of CSS sniffs. Test case only for now.
> Colons in CSS selectors within media queries throw false positives

- CodeSniffer.php
Until https://github.com/facebook/hhvm/issues/4323 was resolved, older
HHVM versions had the Phar extension installed, but it did not support
the Phar::running() function, causing fatal errors.
For other reasons, Wikimedia's CI installation is still running HHVM
3.3.1, causing fatal errors: https://phabricator.wikimedia.org/T100544.
The code now checks whether the Phar::running() function it plans to
call exists instead of just the class.
> Don't fatal due to Phar::running() on older HHVM versions

- CodeSniffer/Standards/Generic/Sniffs/Strings/UnnecessaryStringConcatSniff.php
- CodeSniffer/Standards/Generic/Tests/Strings/UnnecessaryStringConcatUnitTest.inc
- CodeSniffer/Standards/Generic/Tests/Strings/UnnecessaryStringConcatUnitTest.js
- CodeSniffer/Standards/Generic/Tests/Strings/UnnecessaryStringConcatUnitTest.php
Default setting is to ignore the limit and always complain, lineLimit is configurable in an AnnotatedRuleset to match the PSR-2 120 chars for example.
Could not write a UnitTest case because I didn't find a way to set the configurable property from the TestSuit, when the default would be set to 80 or 120 I can make a unit-test for that case. Didn't set any default to keep the unconfigured behaviour the same.
> Add support for allowing string concatenation when the concatenated string would result in a line being to long

- CodeSniffer/File.php
*When code sniffing for doc blocks, PHPCS broke when the PHP 5.4 short array syntax was introduced.
*To fix this, I added a check for a bracket_opener and then skipped to the bracket_closer similar to the check for a parenthesis_opener/closer.
> Method params incorrectly detected when default value uses short array syntax

- CodeSniffer/File.php
The return value of iconv_strlen() is checked, thus there is not need to have an error (E_NOTICE) when an illegal byte sequence is encountered in a file that is being checked.
> Silence errors from iconv_strlen()

- CodeSniffer/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
- CodeSniffer/Standards/PSR1/Tests/Files/SideEffectsUnitTest.5.inc
- CodeSniffer/Standards/PSR1/Tests/Files/SideEffectsUnitTest.php
findNext() might return false, so we have to check for that.
Otherwise we overwrite our loop variable and get stuck.
Detected while playing around with the horde source tree.
Update v2: Fixed a "PRS1" <-> "PSR1" typo in my branch name / commit message.
> Endless loop in PSR1 SideEffects sniffer if no semicolon after last statement

- CodeSniffer/Standards/Squiz/Sniffs/Functions/FunctionDeclarationArgumentSpacingSniff.php
- CodeSniffer/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.inc
This fixes a bug in the `Squiz.Functions.FunctionDeclarationSpacing`
sniff when the `requiredSpacesAfterOpen` option was set to anything
other than 0.
When the first argument in a multiline function declaration had a
type-hint, this error would be given:
> Expected 1 spaces between opening bracket and type hint "array"; 0
found
I don’t think this check was ever intended to affect multiline
functions. The logic was such that it never does when
`requiredSpacesAfterOpen` is 0, and because this is the default, the
bug was never noticed.
> Squiz.Functions.FunctionDeclarationSpacing error for multi-line declarations with required spaces greater than zero

- CodeSniffer/Tokenizers/PHP.php
HHVM 3.5-3.6 tokenize "#!/usr/bin/php" as a non-standard T_HASHBANG
instead of PHP5's T_INLINE_HTML, so convert it to the expected
T_INLINE_HTML.
> Convert HHVM's T_HASHBANG to T_INLINE_HTML (fixes #625)

- CodeSniffer/File.php
- tests/Core/ErrorSuppressionTest.php
Currently the only acceptable way of suppressing errors is by either using single line comments:
```
// @codeStandardsIgnoreStart
```
Or doc block comments:
```
/*
* @codeStandardsIgnoreStart
*/
```
This commit makes it possible to suppress errors by using PHPDoc comments:
```
/**
* @codeStandardsIgnoreStart
*/
```
> Fixes suppression of errors using docblocks

- CodeSniffer/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.1.inc
- CodeSniffer/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.1.inc.fixed
- CodeSniffer/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.php
Only a test case for now, not sure about the correct fix.
> ScopeIndent can fail when a short array opening square bracket is on a line by itself

- CodeSniffer/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.1.inc
- CodeSniffer/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.1.inc.fixed
- CodeSniffer/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.2.inc
- CodeSniffer/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.2.inc.fixed
- CodeSniffer/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.php
Previously:
https://github.com/squizlabs/PHP_CodeSniffer/issues/735
The commit 9badf27cc7 did fix the most of the problems, but there are still a missed hit.
**I have no idea on how to fix the problem itself**, but I did added the test case for it. In short, it's something like:
switch ($foo) {
.....
case 7:
return functionCall(
$withMultiLineParam[0],
array(),
$functionReturningString(
$withMultiLineParam[1]
)
);
.....
}
It's also effecting something like ...
switch ($foo) {
.....
case 7:
return functionCall(
array()
);
.....
}
Or just ...
switch ($foo) {
.....
case 7:
return array(
array(),
);
.....
}
> More complex switch-return structure (Affiliate to #735)

- CodeSniffer/Reports/Json.php
When any of the error or warning messages contain tabs or newlines and a JSON report is generated then the resulting JSON will be invalid.
A good solution for this would be to use `json_encode()` to generate the JSON, but since we need to support old PHP versions this is not possible until PHP CodeSniffer 3 (see #449 for more information).
For the moment we can work around the issue by replacing the offending characters before outputting the JSON report.
> JSON report is invalid when messages contain newlines or tabs

- CodeSniffer/Standards/Squiz/Sniffs/ControlStructures/ForEachLoopDeclarationSniff.php
Add guard code for syntax errors to foreach control structure.
Since [this commit](https://github.com/squizlabs/PHP_CodeSniffer/commit/b2050fab7affad74fca0cb7e01193bb4d36aa147) it is already checking for the opening parenthesis, but if the closing parenthesis for a foreach was missing it still resulted in several php notices which are now fixed:
``` bash
PHP Notice:  Undefined index: parenthesis_closer in /Users/johan/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Squiz/Sniffs/ControlStructures/ForEachLoopDeclarationSniff.php on line 83
PHP Stack trace:
PHP   1. {main}() /Users/johan/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcs:0
PHP   2. PHP_CodeSniffer_CLI->runphpcs() /Users/johan/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcs:25
PHP   3. …
```
> Check for closing parenthesis - Refs #580

- CodeSniffer/Standards/Squiz/Sniffs/Commenting/BlockCommentSniff.php
- CodeSniffer/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc.fixed
The `$stackPtr` was being used instead of `$end`, leading to the
comment opener being replaced with `*/`. This would cause a syntax
error in the “fixed” PHP file.
The sniff did not have a test for the fixing component, which is why
this wasn’t caught sooner. I’ve added the `.fixed` file, but it is just
a copy of the `.inc` file, because I didn’t know for sure whether all
of the fixing behavior is correct. So currently the tests are
intentionally failing.
See
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/478
> Auto fix for Squiz.Commenting.BlockComment.WrongEnd is incorrect

- CodeSniffer/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php
- CodeSniffer/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.js
- CodeSniffer/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.js.fixed
- CodeSniffer/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.php
In Javascript a do-while loop without curly braces is legal, as long as it only contains a single statement:
```
do i++; while (i < 5);
```
When detecting inline sniffs this is handled incorrectly at the moment, resulting in this:
```
do { i++; } while (i < 5) {}
```
We should add support for this construct.
> Add support for braceless do-while loops in Javascript.

- CodeSniffer/CLI.php
This is to fix the following from happening:
$ phpcs --generator=Markdown .
PHP Warning:  Invalid argument supplied for foreach() in /usr/share/php/PHP/CodeSniffer/CLI.php on line 789
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpcs:0
PHP   2. PHP_CodeSniffer_CLI->runphpcs() /usr/bin/phpcs:25
PHP   3. PHP_CodeSniffer_CLI->process() /usr/share/php/PHP/CodeSniffer/CLI.php:95
> Ensure $values['standard'] is set when generator is specified on the command line.

- CodeSniffer/CLI.php
This adds a longopt for specifying bootstrap files. An example of why this might be useful:
```php
<?php
PHP_CodeSniffer::$allowedTypes = array_merge(PHP_CodeSniffer::$allowedTypes, ['int', 'bool']);
```
You can set a bootstrap file in `ruleset.xml` using the `<arg>` element. Previously we were modifying `$allowedTypes` in our custom sniff files, but there's a race condition unless you add this to every single sniff file you have (and you end up with lots of dupes unless you run `array_unique` each time.)
> Add bootstrap file option

- CodeSniffer/CLI.php
`PHP_CodeSniffer::realpath()` either returns false, or a file path. We don't need to check `file_exists()` because `PHP_CodeSniffer::realpath()` does it for us. However, we do want to show a proper filename in the event that the referenced file does not exist.
> Fix error message for non-existent bootstrap file

- CodeSniffer/Standards/Generic/Sniffs/NamingConventions/ConstructorNameSniff.php
- CodeSniffer/Standards/Squiz/Sniffs/Operators/ComparisonOperatorUsageSniff.php
- CodeSniffer/Standards/Squiz/Tests/Operators/ComparisonOperatorUsageUnitTest.inc
- CodeSniffer/Standards/Squiz/Tests/Operators/ComparisonOperatorUsageUnitTest.js
- CodeSniffer/Standards/Squiz/Tests/Operators/ComparisonOperatorUsageUnitTest.php
When enforcing strict and explicit comparison operators for if-statements, I think it would be logical to also enforce these rules for for-statements, while-statements and do-while statements.
> Extended Squiz.Operators.ComparisonOperatorUsage to for, while and do-while

- CodeSniffer/Standards/Generic/Sniffs/PHP/LowerCaseKeywordSniff.php
- CodeSniffer/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc
- CodeSniffer/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc.fixed
- CodeSniffer/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.php
`array` does not seems to be recognized as a keyword when it's not followed by an opening parenthesis. In the [php documentation](http://php.net/manual/en/reserved.keywords.php) it is shown followed by a parenthesis but I think it should be treated as a keyword. 
otherwise, the following statement from the documentation would not make sense for `array` : 
> You cannot use any of the following words as constants, class names, function or method names
> Generic.PHP.LowerCaseKeyword ignores "array" hint keyword

- CodeSniffer/Tokens.php
This solves 2 problems:
1. the `<=>` operator added in PHP 7 wasn't interpreted as operator token (the `T_SPACSHIP`) by sniffs that handle operators (e.g. `Squiz.WhiteSpace.OperatorSpacing`)
2. if custom standard referred to this `T_SPACESHIP` token and PHP 7 code was checked on PHP 5 version then `T_SPACSHIP` constant wasn't defined
> Recognize T_SPACESHIP token as operator token

- CodeSniffer/Standards/Squiz/Tests/CSS/IndentationUnitTest.css.fixed
- CodeSniffer/Standards/Squiz/Tests/CSS/IndentationUnitTest.php
- CodeSniffer/Tokenizers/CSS.php
Here is a test case for demonstration: the line ```background: #072237;``` is changed into ```background: 1072237;```.
Not sure where this should be fixed, so the phpunit tests will fail on this right now.
> CSS indentation fixer changes color codes

- CodeSniffer/CLI.php
Problem: Drupal's Coder defines a PHPCS standard where one sniff uses the Symfony YAML library. That triggers fatal errors because potential Composer dependencies are never included for auto loading.
Let's do it in CLI.php?
PHP-CS-Fixer does something similar: https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/php-cs-fixer
> Composer autoload include statements to make Composer dependencies work

- CodeSniffer/Standards/Generic/Sniffs/NamingConventions/CamelCapsFunctionNameSniff.php
- CodeSniffer/Standards/PEAR/Sniffs/NamingConventions/ValidFunctionNameSniff.php
PHP 5.6 added the magic method __debugInfo.
http://php.net/manual/en/language.oop5.magic.php#object.debuginfo
> Recognize __debugInfo as a magic method.

- CodeSniffer/Standards/Squiz/Sniffs/Commenting/InlineCommentSniff.php
PSR-5 (draft) [defines](https://github.com/phpDocumentor/fig-standards/blob/master/proposed/phpdoc.md#3-definitions) `include()`, `include_once()`, `require()` and `require_once()` as Structural Elements which can therefore have DocBlocks.
_Since this was loosening off of a potential false positive, I was unsure if / how unit tests needed to be updated for this._
> Allow DocBlocks on require|include(_once)

- CodeSniffer/Standards/Generic/Sniffs/PHP/SyntaxSniff.php
- CodeSniffer/Standards/Generic/Tests/PHP/SyntaxUnitTest.php
Without this, you have to manually set php_path in your configuration for this test to work. This also reduces a skipped test in the default testing configuration.
> Default to PHP_BINARY for syntax tests

- CodeSniffer.php
When the `installed_paths` configuration option is used to specify the path of a rule that is used in a custom ruleset a fatal error occurs. This happens because the rule is processed before the configuration option is set, which causes the rule not to be found.
An example, if this custom ruleset is used the "Drupal" rule cannot be found even though it is located in the path specified in the config:
```
<?xml version="1.0" encoding="UTF-8"?>
<ruleset name="drupal_core">
<config name="installed_paths" value="/home/pieter/drupal/vendor/drupal/coder/coder_sniffer/" />
<rule ref="Drupal" /> 
</ruleset>
```
```
$ ../vendor/bin/phpcs -p
PHP Fatal error:  Uncaught PHP_CodeSniffer_Exception: Referenced sniff "Drupal" does not exist in /home/pieter/drupal/vendor/squizlabs/php_codesniffer/CodeSniffe …
```
> 'installed_paths' cannot be set for a rule in a custom ruleset

- composer.json
Since the code uses functions from the SimpleXML module
(simplexml_load_string), it should require it. Some distributions split
SimpleXML in a separate package (as Debian recently did), so being
explicit about used modules is helpful.
Bug-Debian: https://bugs.debian.org/816248
> Require SimpleXML

- CodeSniffer/Tokenizers/Comment.php
Hello!
This is a simple PR that removes a call to an undefined variable. This call was causing a stack trace to be printed to the console in "very verbose" mode (i.e. `-vv`) while parsing comments.
Example file that was being processed
```php
<?php
class TestClass {
/** @var asdfsdf */
private static $testId;
public static function getTestId() {
if (is_null(self::$testId)) {
self::$testId = mt_rand();
}
return self::$testId;
}
}
```
Output produced by file (removed a few lines to keep it brief)
```
/usr/local/bin/php /.../vendor/bin/phpcs --standard=/.../MyStandard /.../test/staticvar.php -p -vv
Processing ruleset /.../MyStandard/ruleset.xml
Adding sniff files from "/.../MyStandard/Sniffs/" directory
...
=> Ruleset processing complete; included 3 sniffs and excluded 0
Creating file …
```
> Removed undefined variable call to $lineToken 

- package.xml
Mimic existing documentation from composer.json.
Bug-Debian: https://bugs.debian.org/816248
> Document needed extensions in package.xml

- CodeSniffer/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
- CodeSniffer/Standards/PSR1/Tests/Files/SideEffectsUnitTest.7.inc
I found another spot where the [issue 20481 reported through PEAR](https://pear.php.net/bugs/bug.php?id=20481) occurred during a PSR2 sniff. A PHP script beginning with shebang but containing only comments does not trigger it, but a script defining symbols will trigger the `PSR1.Files.SideEffects.FoundWithSymbols` warning.
```
A file should declare new symbols (classes, functions, constants, etc.) and cause no other side effects, or it should execute logic with side effects, but should not do both. The first symbol is defined on line 5 and the first side effect is on line 1. (PSR1.Files.SideEffects.FoundWithSymbols)
```
This patch fixes that issue in a similar way to the approach found in the commit addressing issue 20481.
> Shebang can cause PSR1 SideEffects warning

- CodeSniffer/Standards/Generic/Sniffs/Functions/CallTimePassByReferenceSniff.php
- CodeSniffer/Standards/Generic/Tests/Functions/CallTimePassByReferenceUnitTest.inc
> Fixed bug #959 : Call-time pass-by-reference false positive if there is a square bracket before the ampersand

- CodeSniffer/Tokens.php
This adds support for T_COALESCE token that corresponds to null coalescing operator (??) added in PHP 7.0.
Fixes issue #962.
> T_COALESCE as operator token

- CodeSniffer/CLI.php
This PR fixes the following weird behavior:
```sh
$ phpcs --standard=PSR1,PSR2 src/
$ phpcs --config-set default_standard PSR1,PSR2
Config value "default_standard" added successfully
$ phpcs src/
ERROR: the "PSR1,PSR2" coding standard is not installed. The installed coding standards are PSR2, PHPCS, PEAR, PSR1, MySource, Squiz and Zen
```
> Allow multiple default_standard values in CodeSniffer.conf

- CodeSniffer.php
name is actually determined form $xml file
> CodeSniffer: drop unused variable

- CodeSniffer/Standards/Squiz/Sniffs/PHP/LowercasePHPFunctionsSniff.php
We can no longer rely on calling `function_exists` to determine whether the function token in question is a "PHP internal" function. Mainly because PHP_CodeSniffer now uses the vendor/autoload.php file (if it exists) to load classes. This is a shared autoload system, that could cause many user defined functions to exist in the same memory space under which PHPCS is running.
Since the whole point of the sniff is to check only PHP built in (inbuilt) functions, I've made the change in this PR to check the function using `get_defined_functions`.
I didn't change or add any unit tests, since I couldn't think of any additional use cases needed. I suppose the only risk is if a given function returns `true` for function_exists() but does not exist in get_defined_functions()['internal'].
- phpcs …
> Use php's internal defined function list for sniff

- CodeSniffer/CLI.php
Sometimes the internal values of CLI.php are not initialized. This happens on test runs in Drupal's coder. I'm trying to add
```xml
<arg name="extensions" value="php,module,inc,install,test,profile,theme,css,info,txt,md,yml"/>
```
to ruleset.xml to have some extension default values.
The commit is my best guess at fixing the notice, or is there another place where $this->values should be initialized?
> Fix PHP notices when file extensions defaults are not present

- CodeSniffer/CLI.php
Read stdin from the handle opened via `fopen('php://stdin')`, not the original `STDIN` handle which may not have been affected by the `stream_set_blocking()` call.
I’d look for confirmation from others but I’m pretty sure this fixes https://github.com/squizlabs/PHP_CodeSniffer/issues/993.
> Read stdin input from the dup()’ed non-blocking handle

- CodeSniffer/Standards/Generic/Sniffs/NamingConventions/UpperCaseConstantNameSniff.php
- CodeSniffer/Standards/Generic/Tests/NamingConventions/UpperCaseConstantNameUnitTest.inc
- CodeSniffer/Standards/Generic/Tests/NamingConventions/UpperCaseConstantNameUnitTest.php
The current version in combination with hhvm raises issues like https://github.com/zircote/swagger-php/pull/319. hhvm interprets the namespaces more strict than php.
This pull request will allow constant definitions with a lower case namespace like `define('bar\foo\baz\VALID_NAME_WITH_NAMESPACE', true)`. Currently it's not allowed and you need to change the code to `define('BAR\FOO\BAZ\VALID_NAME_WITH_NAMESPACE', true);` though the namespace is in lower case like `namespace bar\foo\baz;`.
> Allow lower case namespace in constant definitions

- CodeSniffer/Standards/Squiz/Sniffs/Commenting/LongConditionClosingCommentSniff.php
- CodeSniffer/Standards/Squiz/Tests/Commenting/LongConditionClosingCommentUnitTest.inc
- CodeSniffer/Standards/Squiz/Tests/Commenting/LongConditionClosingCommentUnitTest.inc.fixed
- CodeSniffer/Standards/Squiz/Tests/Commenting/LongConditionClosingCommentUnitTest.js
- CodeSniffer/Standards/Squiz/Tests/Commenting/LongConditionClosingCommentUnitTest.php
- package.xml
* Allow for setting a different lineLimit from the config file.
* Allow for a different comment format to be set from the config file.
Also: minor spelling corrections.
Original test files have been renamed to prevent unit tests failing because of property value bleed through.
> Make the LongConditionClosingCommentSniff more flexible.

- CodeSniffer/Standards/Generic/Sniffs/PHP/ForbiddenFunctionsSniff.php
The `Generic.PHP.ForbiddenFunctions` sniff can easily be extended to also sniff for other functions.
However, there is a bug which prevents functions in mixed- or uppercase from being recognized.
As functionnames in PHP are case-insensitive both for userland functions as well as build-in functions, the function should always do a case-insensitive function name check.
In the current code the comparison was not consistently done in a case-insensitive manner. This PR fixes that.
No unit tests are provided with the PR as I can't seem to influence the `$forbiddenFunctions` array just and only for the unit test without actually extending the class.
A real world example of the bug can be found here:
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/WPCS/feature/fix-bug …
> Fix bug where functions in mixed/uppercase would not be recognized.

- CodeSniffer/Standards/Generic/Docs/PHP/BacktickOperatorStandard.xml
- CodeSniffer/Standards/Generic/Sniffs/PHP/BacktickOperatorSniff.php
- CodeSniffer/Standards/Generic/Tests/PHP/BacktickOperatorUnitTest.inc
- CodeSniffer/Standards/Generic/Tests/PHP/BacktickOperatorUnitTest.php
Working on a project now which wants to add a sniff like this as part of their security-sniffs and figured it would be re-usable for others as well.
> Add a sniff to detect the usage of the backtick operator.

- CodeSniffer.php
phpcs versions beyond 2.6.1 fail to process xml files in directories containing "%2F". This is because of this change:
https://github.com/squizlabs/PHP_CodeSniffer/commit/322fa248f2c43e6df18f83a8193b42aa37d02c17
We discovered this because we build all our sources via Jenkins which transforms / into %2F so a directory looks like:
/home/jenkins/workspace/project/feature%2Fname
This is needed because in Linux0, / is a directory separator and cannot be used as part of the directory/file name.
phpcs will print an error:
Warning: simplexml_load_file(): I/O warning : failed to load external entity "/home/jenkins/workspace/project/feature%2Fname/phpcs.xml" in /home/jenkins/workspace/project/feature%2Fname/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 715
Fatal error: Uncaught …
> Rulesets cannot be loaded if the path contains urlencoded characters

- .travis.yml
- CodeSniffer/Standards/Generic/Sniffs/PHP/DisallowShortOpenTagSniff.php
- CodeSniffer/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.inc
- CodeSniffer/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.inc.fixed
- CodeSniffer/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.php
- myconfig.ini
- package.xml
This PR makes the `Generic.PHP.DisallowShortOpenTag` sniff fixable.
The `myconfig.ini` file and the adjustment to the `travis` script are needed for the fixer unit tests to pass as when `short_open_tag` is set to `off`, the fixer won't fix it correctly and the tests will fail ;-)
> Make the `Generic.PHP.DisallowShortOpenTag` sniff fixable.

- CodeSniffer/CLI.php
- CodeSniffer/Standards/Generic/Tests/Files/OneTraitPerFileUnitTest.php
- CodeSniffer/Standards/Generic/Tests/PHP/BacktickOperatorUnitTest.php
- CodeSniffer/Standards/PSR1/Sniffs/Classes/ClassDeclarationSniff.php
- CodeSniffer/Standards/PSR1/Tests/Classes/ClassDeclarationUnitTest.php
- CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- CodeSniffer/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.php
Inspired by: https://github.com/squizlabs/PHP_CodeSniffer/pull/1084#discussion_r71835858
A PHP version number is build up as `{major}.{minor}.{release}{extra}`.
In 99.9% of cases where a version comparison is needed, the `{extra}` (`alpha/beta/RC`) information can/should be disregarded.
`PHP_VERSION` is a string which contains the complete version number, including `{extra}`.
`PHP_VERSION_ID` is an integer which contains the release version number *without* the `{extra}`
So using `PHP_VERSION_ID` allows to do accurate version comparisons without taking the `{extra}` into account *and* without an extra function call to `version_compare()`.
As `PHP_VERSION_ID` only became available in PHP 5.2.7, it needs to be defined in the application for older PHP versions.
Ref: …
> Improve version comparisons by using PHP_VERSION_ID.

- CodeSniffer/File.php
Based on `findExtendedClassName()`. Allows to retrieve an array with the names of the interfaces a class implements.
Credits go to @westonruter (with a minor fix by me).
This is a method used within the WPCS project, but could possibly be useful for others too.
[Edit] Example use case: check if a method is in an extended class or implements an interface and if so, exempt it from method name convention checks as when overloading a method from the parent/interface complying with the method name conventions may not be possible.
> Add a new utility method to find implemented interface names.

- CodeSniffer/CLI.php
This PR allows running the Code Sniffer on multiple PHP files given as input and output a single report file. This is more convenient than passing the files on the command line(command line limits, simpler handling of input, etc). 
Unix throws an error in case many files(>hundreds) are passed on the command line:
`-bash: <process>: Argument list too long`
This solves the above issue.
> Allow input paths / files to be passed in a file

- CodeSniffer/Standards/Squiz/Sniffs/WhiteSpace/ObjectOperatorSpacingSniff.php
- CodeSniffer/Standards/Squiz/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.inc
- CodeSniffer/Standards/Squiz/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.php
The Squiz.WhiteSpace.OperatorSpacing sniff has a parameter named ignoreNewlines. Thus, I can disallow:
`$a = $b+$c+$d;`
While allowing:
```
$a =
$b +
$c +
$d;
```
I would like to do the same for object operators, and disallow:
`$foo -> bar() -> baz();`
While allowing:
```
$foo
->bar()
->baz();
```
However, the Squiz.WhiteSpace.ObjectOperatorSpacing sniff does not have an ignoreNewlines parameter, so the latter is always flagged.
This is an enhancement request to add an ignoreNewlines parameter to the Squiz.WhiteSpace.ObjectOperatorSpacing sniff. Thanks.
> Added ignoreNewlines parameter to Squiz.WhiteSpace.ObjectOperatorSpacing

- CodeSniffer/Standards/Generic/Sniffs/PHP/DisallowAlternativePHPTagsSniff.php
- CodeSniffer/Standards/PSR1/Sniffs/Classes/ClassDeclarationSniff.php
- CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
Provides enhancement requested in #1103, allows your phpcs to target a specific php version since some sniffs (three currently) provide different checks based on php version.
Allows user to specify `--platform=PHP_VERSION_ID` on command line, or `<platform>` in `phpcs.xml`. Can be used for both phpcs and phpcbf. Modified the Squiz Function Comment to use it if present.
Defaults to current PHP_VERSION_ID.
Documentation updates cannot be made in a PR.
This is similar to the composer config setting `platform` https://getcomposer.org/doc/06-config.md#platform but for phpcs.
I almost exclusively live on an intranet with SVN, so this is my first PR, sorry if I did anything wrong.
Ran codestyle and phpunit before submitting. Not sure if I need to also provide a test.
> add config `php_version` to override PHP_VERSION_ID in sniffs

- CONTRIBUTING.md
The current `CONTRIBUTING.md` says to run `php scripts/phpcs . --standard=PHPCS -np` which makes it ignore the default `phpcs.xml.dist` and also scans the whole `vendor` directory. 
By removing the arguments it will use the `phpcs.xml.dist` file and not scan the vendor directory, plus keep up to date with whatever defaults you change in the future.
Alternatively it if you want to keep it listing everything, it could be changed to `php scripts/phpcs CodeSniffer.php scripts CodeSniffer --standard=PHPCS -np` so that vendor and tests are ignored.
> contributing.md remove args so it uses phpcs.xml.dist

- CodeSniffer/Standards/Squiz/Sniffs/Scope/MethodScopeSniff.php
- CodeSniffer/Standards/Squiz/Tests/Scope/MethodScopeUnitTest.inc
- CodeSniffer/Standards/Squiz/Tests/Scope/MethodScopeUnitTest.php
It currently sniffs classes and interfaces, this just adds traits to the list of things sniffed.
Scrutinizer was complaining about one of our traits having a method without visibility defined and I was like "phpcs should have caught this!" huzzah, it was not checking traits.
Easy fix.
> Makes Squiz MethodScopeSniff sniff Traits

- CodeSniffer/Standards/Squiz/Sniffs/CSS/DuplicateClassDefinitionSniff.php
- CodeSniffer/Standards/Squiz/Tests/CSS/DuplicateClassDefinitionUnitTest.css
- CodeSniffer/Standards/Squiz/Tests/CSS/DuplicateClassDefinitionUnitTest.php
It now handles a media block as a scope.
This prevents false positives caused by the same class in multiple media queries/blocks.
> Fix in Squiz.CSS.DuplicateClassDefinitionSniff

- tests/Standards/AllSniffs.php
- tests/TestSuite.php
If there are `installed_paths` set up in the config and one of the standards in the `installed_paths` uses an alternative way to unit test - this applies in particular to the [PHPCompatibility](https://github.com/wimg/PHPCompatibility) sniff library -, running the unit tests for any of the other standards using the normal PHPCS unit test set up will fail as fatal errors will be thrown for (sniff) files which cannot be found.
This minor adjustment prevents these fatal errors while leaving the responsibility for running the tests which are set up differently with the sniff library in question.
> Play nice with sniff libraries with alternative unit test setups.

- CodeSniffer/Tokenizers/JS.php
Seems to be copy/pasted from `PHP_CodeSniffer_Tokenizers_PHP::tokenizeString()`.
> Fix DocBlock of `PHP_CodeSniffer_Tokenizers_JS::tokenizeString()`

- CodeSniffer/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php
The three code blocks for `T_ARRAY`, `T_OPEN_SHORT_ARRAY` and `T_CLOSURE` were nearly the same.
This PR simplifies the code by folding the three blocks into one and only having a small if/else block for the actual difference between the three.
> Remove duplicate code from the Squiz `ArrayDeclaration` sniff.

- CodeSniffer/Tokenizers/JS.php
Previously, these were treated as two comparison operators.
Fixes #1230.
> Tokenise << and >> in JS as bitwise shifts

- CodeSniffer/Standards/Generic/Sniffs/NamingConventions/CamelCapsFunctionNameSniff.php
- CodeSniffer/Standards/Generic/Tests/NamingConventions/CamelCapsFunctionNameUnitTest.inc
- CodeSniffer/Standards/PSR1/Sniffs/Methods/CamelCapsMethodNameSniff.php
- CodeSniffer/Standards/PSR1/Tests/Methods/CamelCapsMethodNameUnitTest.inc
Function and method names starting with a double underscore are reserved by PHP itself for magic functions/methods.
A triple underscore function name prefix, however, should not trigger this error. (I'm not saying it's a good idea, but it's out there in userland code)
Fixed in the two non-proprietary standards which have checks for double underscored function/method names.
Includes additional unit tests for all four sniffs.
This PR does not cover similar checks in the proprietary PEAR and Squiz standards.
Fixes https://github.com/wimg/PHPCompatibility/issues/297
> False positive for function names starting with triple underscore

- CodeSniffer/Standards/Squiz/Sniffs/Commenting/DocCommentAlignmentSniff.php
- CodeSniffer/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc
- CodeSniffer/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc.fixed
- CodeSniffer/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.php
Did not have time for a test case yet.
> fix(DocCommentAlignment): Check doc block alignment on var key word

- CodeSniffer/File.php
- tests/Core/File/GetMethodParametersTest.php
Improve type hint recognition:
- `self` is a valid type hint and was so far not being recognized as such. Ref: http://php.net/functions.arguments#functions.arguments.type-declaration
- `parent` and `static` are _not_ valid type hints, but if they are there, they were probably intended as such.
- For both the above, made sure not to confuse the type hint with the default value.
New array value `raw`:
- Add raw content of the parameter parts to the return array for use in further processing.
Includes adjusted unit tests + added unit test for `self`
P.S.: the alignment of the setting of the `raw` array value is a bit out of sync, but that's due to a bug in another sniff. The PHPCS code style was borking on proper alignment.
> Recognize `self` as type hint in `getMethodParameters()`.

- CodeSniffer/File.php
- tests/Core/ErrorSuppressionTest.php
- tests/Core/File/FindExtendedClassNameTest.inc
- tests/Core/File/FindExtendedClassNameTest.php
- tests/Core/File/FindImplementedInterfaceNamesTest.inc
- tests/Core/File/FindImplementedInterfaceNamesTest.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/IsCamelCapsTest.php
PHP 7.1 introduces nullable types.
This PR allows for recognizing these in the `getMethodParameters()` method.
The starting `?` will be added to the type hint and a new parameter array key `nullable_type` will be set as well.
Includes additional unit test for this functionality, however the unit test breaks the test suite as the nullable type hint is seen as a parse error in PHP < 7.1. This is due to the test code being contained in the same file as the actual tests.
@gsherwood Any suggestions how I should work around this ? Remove the unit tests ? Move the test code to a separate file ? (but how will the PHPCS test suite handle that ?)
Ref:
- http://php.net/manual/en/migration71.new-features.php#migration71.new-features.nullable-types
- https://wiki.php.net/rfc/nullable_types
> Allow for nullable type hints and add a `nullable_type` indicator.

- CodeSniffer/Fixer.php
- package.xml
Fixer incorrectly handles filepath, e.g.:
For example, if filePath is `/app/path/app/file.php` and cwd is `/app/`, expected filepath should be `path/app/file.php`
But in fact, filepath became wrong - `pathfile.php`
Because `str_replace` replaces all occurrences in target filepath:
https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Fixer.php#L246
```php
$cwd      = getcwd().DIRECTORY_SEPARATOR;
$filename = str_replace($cwd, '', $filePath);
```
> Fixed bug #1267 : Fixer incorrectly handles filepath

- CodeSniffer/Standards/Generic/Sniffs/PHP/SyntaxSniff.php
Syntax errors were not being matched if the `php.ini` file used contained a value for `error_prepend_string`.
This fix makes double sure that those will now start showing up as it:
* Overloads the ini value specifically for the php process used for the linting.
* Matches the error line pattern per line in the result. The `error_prepend_string` will normally be on its own line in the output, so matching the error pattern for each line should prevent further issues.
Unit testing this would be near impossible as one would need to overload the `php.ini` file used by the linting process.
All the same, the issue can easily be reproduced:
* Edit the `php.ini` file for the PHP version on which PHPCS is running, uncomment it and give it a value. Example often used by people mainly using PHP in the …
> Syntax errors not being shown when error_prepend_string is set

- CodeSniffer/Standards/Generic/Sniffs/Files/ByteOrderMarkSniff.php
While working on the list of public properties which can be changed from rulesets (#1278), I came across this property in the `Generic_Sniffs_Files_ByteOrderMarkSniff` for which it seemed unlikely that it was intended to be public.
> Generic / ByteOrderMark: property visibility

- CodeSniffer/Standards/Squiz/Sniffs/CSS/NamedColoursSniff.php
- CodeSniffer/Standards/Squiz/Sniffs/CSS/ShorthandSizeSniff.php
While working on the list of public properties which can be changed from rulesets (#1278), I came across two properties in the Squiz sniffs for which it seemed unlikely that these were intended to be public.
> Squiz: property visibility

- CodeSniffer/Standards/Generic/Sniffs/Classes/DuplicateClassNameSniff.php
While working on the list of public properties which can be changed from rulesets (#1278), I came across this property for which it seemed unlikely that it was intended to be public.
This is a complex property which expects a multi-level array to be set based on the classes found by the sniff.
> Generic/DuplicateClassName: fix property visibility

- CodeSniffer/File.php
- CodeSniffer/Standards/Generic/Sniffs/CodeAnalysis/UnusedFunctionParameterSniff.php
- CodeSniffer/Standards/Generic/Tests/CodeAnalysis/UnusedFunctionParameterUnitTest.inc
- CodeSniffer/Standards/Generic/Tests/CodeAnalysis/UnusedFunctionParameterUnitTest.php
- CodeSniffer/Standards/PEAR/Sniffs/Functions/ValidDefaultValueSniff.php
- CodeSniffer/Standards/PEAR/Tests/Functions/ValidDefaultValueUnitTest.inc
- CodeSniffer/Standards/PEAR/Tests/Functions/ValidDefaultValueUnitTest.php
The method itself works perfectly for closures, it just didn't allow itself to be used for them.
Includes allowing for closures in two sniffs which use the `getMethodParameters()` method.
Includes additional unit test(s) for these sniffs.
> getMethodParameters(): Allow for closures.

- .travis.yml
And as expected and reported in #1280, the build for PHP 5.2 is currently breaking.
[Edit] Just looked through the details of the breaking build and most of the issues seem to be to do with the `\` `T_NS_SEPARATOR` not being recognized in PHP 5.2, haven't found one demonstrating the current issue yet....
How would you like me to proceed with this ? Exclude namespace related tests for PHP 5.2 ?
> Let's start testing the build on PHP 5.2 to avoid further breaks by PHP notices

- CodeSniffer/Standards/PEAR/Sniffs/WhiteSpace/ScopeClosingBraceSniff.php
- CodeSniffer/Standards/Squiz/Sniffs/Formatting/OperatorBracketSniff.php
These are no longer needed since commit 5def2acbe3911e2aea08ac8b8eb4e4d64330021f / `addFixableError() and addFixableWarning() now only return true if the fixer is enabled`
> Remove two superfluous checks for fixer->enabled.

- CodeSniffer/Standards/Generic/Sniffs/Functions/FunctionCallArgumentSpacingSniff.php
- CodeSniffer/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc
- CodeSniffer/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc.fixed
- CodeSniffer/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.php
Checks for calling closures and other methods that have their own
tokens, like unset()
> allows for closures

- .travis.yml
Currently PHPUnit is failing on PHP nightly and therefore the build is failing.
This change will prevent complete builds failing for failures which occur only in PHP nightly.
FYI: the underlying issue in PHPUnit / Comparator has already been addressed but is not contained in the version used by Travis yet.
Ref: https://github.com/sebastianbergmann/phpunit/issues/2453
Ref: https://github.com/sebastianbergmann/comparator/pull/30
> Allow failures for PHP nightly.

- CodeSniffer/Standards/Squiz/Sniffs/WhiteSpace/SemicolonSpacingSniff.php
- CodeSniffer/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.inc
- CodeSniffer/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.inc.fixed
- CodeSniffer/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.js
- CodeSniffer/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.js.fixed
- CodeSniffer/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.php
Used to remove everything between a semicolon and a nonempty token. Now it jumps over the comments leaving them as is only removing whitespaces between a comment and a semicolon. For exmple, if we have code like this:
`$test = $a /* + $b */ ;`
Before: the comment would be removed:
`$test = $a;`
Now: the comment remains:
`$test = $a; /* + $b */`
> Fixed: comments are no longer removed

- CodeSniffer/Standards/Generic/Sniffs/CodeAnalysis/UselessOverridingMethodSniff.php
Remove an unused variable.
Simple thing.
> Remove an unused param inside UselessOverridingMethodSniff

- CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- CodeSniffer/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.1.inc
- CodeSniffer/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.1.inc.fixed
- CodeSniffer/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.php
- package.xml
Also incidentally fixes a _"Function return type is not void, but function has no return statement"_ error being thrown when it shouldn't be when using multiple types including void, i.e. `array|void`.
Includes unit tests specific to this issue in a separate file + fixed file.
Fixes #1018
Note: the unit tests are in a separate file as the "main" unit test file for this sniff does not have a `.fixed` version and adding that is currently not an option as there are a number of other bugs in the sniff.
Once all the bugs are solved & a `.fixed` file for the main unit test file can be added, the tests for this issue can be added to the main file.
> Squiz / FunctionComment: fix detection of incorrect types when @return tag has description

- CodeSniffer/Standards/Squiz/Sniffs/Strings/DoubleQuoteUsageSniff.php
On files with CRLF new lines the message would get distorted, since \r chars would not get converted.
> Squiz.Strings.DoubleQuoteUsage.NotRequired message is badly formatted when string contains a CR newline char

- CodeSniffer/Standards/PEAR/Sniffs/Functions/FunctionCallSignatureSniff.php
- CodeSniffer/Standards/PSR2/Tests/Methods/FunctionCallSignatureUnitTest.inc
- CodeSniffer/Standards/PSR2/Tests/Methods/FunctionCallSignatureUnitTest.inc.fixed
- CodeSniffer/Standards/PSR2/Tests/Methods/FunctionCallSignatureUnitTest.php
This is a somewhat hard to come by bug, but still... The problem was, when using PSR2.Methods.FunctionCallSignatureSniff with requiredSpacesBeforeClose set to 1 and you had a situation like this:
```
foo('Testing
multiline text'
);
```
Notice a space before the closing parenthesis. The sniff would try to fix it but would get stuck, since it was removing a single token before the parenthesis. What I've done is I try to move the closing parenthesis to the end of the function call parameter, while jumping over any inline T_COMMENT and moving it before any /* */ comments or any other token, so for example, if we had a situation like this:
```
foo('Testing
multiline text: ' // . $text
);
```
The fixed code would look like this:
```
foo('Testing
multiline text: ' ) // . $text
;
```
But if we …
> PSR2.Methods.FunctionCallSignature strips some comments during fixing

- CodeSniffer/Standards/Squiz/Sniffs/PHP/DisallowMultipleAssignmentsSniff.php
- CodeSniffer/Standards/Squiz/Tests/PHP/DisallowMultipleAssignmentsUnitTest.inc
While PHP4 code shouldn't be used anymore, there are other sniffs which deal with that.
This sniff should in that regard be version agnostic.
> DisallowMultipleAssignments sniff: fix false positive for PHP4 compatible code

- CodeSniffer/Standards/Generic/Sniffs/PHP/DisallowShortOpenTagSniff.php
- CodeSniffer/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.3.inc
- CodeSniffer/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.4.inc
- CodeSniffer/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.php
- package.xml
When the ini setting `short_open_tag` is `off` on the machine running PHPCS, short open tags would not be recognized in `T_INLINE_HTML` tokens.
This could lead to undesirable consequences if the code would later be deployed on a machine where `short_open_tag` is set to `on`.
This PR fixes that and will throw a warning if a use of short open tags is detected in inline HTML.
Fixes #1398
Note: the `getSnippet()` method is a 1-on-1 copy of the one used in the `DisallowAlternativePHPTags` sniff.
It would be better if that method would be placed in another file and just called by both sniffs, but I wasn't sure which class would be most suited to place the method in.
> DisallowShortOpenTag: throw warning for potential short open tags in inline HTML

- .travis.yml
In the current setup, the tests were only run using the custom ini files.
This meant that the test-cases for which the default ini is expected, were never being run.
I've now added a custom environment variable which toggles whether the default ini values or the custom values should be used.
I've selectively chosen two PHP versions on which to run with the custom ini file based on the sniffs involved.
The other PHP versions will now use the default ini values, making the build testing via travis more comprehensive as both situations will be tested.
> Travis tweak: Run the test with & without the custom ini files.

- CodeSniffer/Tokens.php
The `T_COALESCE_EQUAL` operator compares and assigns to a variable:
```php
$a ??= $b; // When $a is set, use $a, otherwise assign $b to $a.
```
Looking at the token arrays, I believe was incorrectly placed with `$operators` and should be in `$assignmentTokens` instead.
Having it in `$operators` could cause issues with sniffs like `Squiz.Formatting.OperatorBracket`.
> Tokens: Move `T_COALESCE_EQUAL` from `$operators` to `$assignmentTokens`

- CodeSniffer/Tokens.php
The `PHP_CodeSniffer_Tokens` class currently contains a `$stringTokens` property which contains the tokens for the typical single/quoted text string variable type.
However, when the intention is examining the _content_ of textual tokens, there are three more tokens which need to be taken into account: `T_INLINE_HTML`, `T_HEREDOC` and `T_NOWDOC`.
I was a bit wary of changing the `$stringTokens` array as it feels like the intention of that array is different than what I described above, so I have opted for adding a new `$textStringTokens` property.
> Tokens: Add new `$textStringTokens` property representing all tokens which typically contain text strings

- CodeSniffer/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
- CodeSniffer/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- CodeSniffer/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
> Squiz/OperatorSpacing: Ignore operators in declare statements.

- CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentThrowTagSniff.php
- CodeSniffer/Standards/Squiz/Tests/Commenting/FunctionCommentThrowTagUnitTest.inc
- CodeSniffer/Standards/Squiz/Tests/Commenting/FunctionCommentThrowTagUnitTest.php
This update lets PHPCS detect when an exception is caught and re-thrown as a variable. It requires the re-thrown exception to be explicitly listed in the function comment, and avoids problems where re-thrown exceptions are listed correctly, but show PHPCS errors as excessive `@throws` tags.
For example, this would now be valid:
``` php
/**
* Calls a function that may raise an exception, or may return false. In either instance, raise an exception
*
* @throws NewException When a brand new exception is thrown.
* @throws OldException When an exception is caught and re-thrown.
*/
function thisThrowsExceptions() {
try {
$val = mightThrowExceptions();
} catch (OldException $e) {
throw $e;
}
if ($val === false) {
throw new NewException('$val is false');
}
// The rest of the code.
}
```
> Throw tag sniff supporting re-thrown exceptions

- CodeSniffer/File.php
Add information about the `variable_length` index in the returned array.
> Minor doc fix `PHP_CodeSniffer_File::getMethodParameters()`

- CodeSniffer/Standards/PEAR/Sniffs/Commenting/ClassCommentSniff.php
- CodeSniffer/Standards/PEAR/Tests/Commenting/ClassCommentUnitTest.inc
- CodeSniffer/Standards/PEAR/Tests/Commenting/ClassCommentUnitTest.php
Under the "PEAR rules were created before traits existed" principle, I figured traits should comply with the class comment rules as well.
I've not added anonymous classes as to add that, some token walking would be needed allow for the anonymous class to be assigned to a variable. Let me know if you'd like me to change/add that anyway.
> PEAR/ClassComment: Apply the class comment rules to traits as well.

- src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.php
PSR-2 requires a comment when intentionally falling through a `case` within a `switch`.  Before reporting this error, we now check if there is an if/else statement at the end of the `case` block which always terminates. This reduces the number of false positives.
This PR fixes bug #834 .
> PSR2.ControlStructSwitchDeclaration does not handle if branches with returns

- CodeSniffer/Standards/Squiz/Sniffs/Commenting/ClassCommentSniff.php
The description did not reflect what the sniff was really checking for.
It might be that the other items were intended to be added at some point, but they are currently not in the sniff.
> Squiz/ClassComment: Fix incorrect sniff description in class docblock.

- CodeSniffer/Standards/Generic/Sniffs/PHP/DisallowShortOpenTagSniff.php
- CodeSniffer/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.2.inc
- CodeSniffer/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.2.inc.fixed
- CodeSniffer/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.php
I was using `phpcbf` to fix some legacy files that contained short opening tags without an empty space between them and the content: `<?echo` (this is valid to the PHP engine)
The problem is that `phpcbf` was replacing the short opening tag with a huge string like `<?phpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpphpecho`
I've added a test that shows the failure + the fix that I found for the problem.
Keep up the good work.
Cheers
> PHPCBF can't fix short open tags when they are not followed by a space

- src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.php
If the sniff has found a ternary statement it would return to quickly and so it would avoid doing some checks.
You can check the tests to see what I am talking about.
> Squiz.WhiteSpace.OperatorSpacing is not checking spacing on either side of a short ternary operator

- src/Util/Standards.php
If a "Standards" directory is called the same as one of the standards it contains and that standard is requested, an _"ERROR: the ... coding standard is not installed."_ error will be thrown and the sniffs will not run.
While I suppose this change in behaviour between PHPCS 3.x and PHPCS 2.x is intended to add support for "one standard" type of libraries, it breaks support for multi-standard libraries where one of the standards has the same name as the repository.
The change I'm proposing in this PR will maintain support for the PHPCS 2.x behaviour - thus not breaking existing registered standards - while at the same time supporting the new feature.
> Coding standard located under an installed_path with the same directory name throws an error

- src/Standards/Generic/Sniffs/Classes/OpeningBraceSameLineSniff.php
- src/Standards/Generic/Tests/Classes/OpeningBraceSameLineUnitTest.inc
- src/Standards/Generic/Tests/Classes/OpeningBraceSameLineUnitTest.inc.fixed
- src/Standards/Generic/Tests/Classes/OpeningBraceSameLineUnitTest.php
There might be a comment between the opening brace and the last part of the class declaration.
The sniff currently did not take that into account.
Fixed including unit test demonstrating the issue.
> Generic.Classes.OpeningBraceSameLine doesn't detect comment before opening brace

- src/Files/File.php
- src/Sniffs/AbstractScopeSniff.php
- src/Standards/Generic/Sniffs/Debug/ClosureLinterSniff.php
- src/Standards/Generic/Sniffs/Debug/ESLintSniff.php
- src/Standards/Generic/Sniffs/Debug/JSHintSniff.php
- src/Standards/Generic/Sniffs/VersionControl/SubversionPropertiesSniff.php
- src/Standards/Squiz/Sniffs/Debug/JSLintSniff.php
- tests/Standards/AbstractSniffUnitTest.php
Fixed various places where the old exception of PHP_Codesniffer_Exception was used either as docblock either as an actual exception (found only one place... so it's mainly docblocks)
> Fix exceptions uses in version 3.x

- src/Config.php
Running `phpcbf` with the `--sufffix` argument caused a fatal `array to string conversion` error.
The `suffix` argument is expected to be a `string`, but was being converted to an array with the `explode` in the `Config::processLongArgument()` method.
```
Fatal error: Uncaught exception 'PHP_CodeSniffer\Exceptions\RuntimeException' with message 'Array to  string conversion in PHP_CodeSniffer\src\Reports\Cbf.php on line 81' in PHP_CodeSniffer\src\Runner.php on line 557
PHP_CodeSniffer\Exceptions\RuntimeException: Array to string conversion in PHP_CodeSniffer\src\Reports\Cbf.php on line 81 in PHP_CodeSniffer\src\Runner.php on line 557
Call Stack:
0.0000     124152   1. {main}() PHP_CodeSniffer\bin\phpcbf:0
0.0070     298216   2. PHP_CodeSniffer\Runner->runPHPCBF() …
```
> Fatal error when using the --suffix argument

- src/Standards/Squiz/Sniffs/PHP/EmbeddedPhpSniff.php
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.inc
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.inc.fixed
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.php
The `Squiz.PHP.EmbeddedPhp` sniff will create a fixer conflict with itself when it encounters a `//` comment just before the PHP close tag.
The tokenizer will tokenize whitespace at the end of a `//` comment as part of the `T_COMMENT` token, so the fixer just keeps adding more spaces between the `T_COMMENT` and the `T_CLOSE_TAG` which in the next fixer round is then tokenized again as being part of the `T_COMMENT` resulting in the loop.
> 3.x: Squiz/EmbeddedPHP sniff - prevent fixer conflict

- CodeSniffer/Standards/Squiz/Sniffs/PHP/EmbeddedPhpSniff.php
- CodeSniffer/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.inc
- CodeSniffer/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.inc.fixed
- CodeSniffer/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.php
The `Squiz.PHP.EmbeddedPhp` sniff will create a fixer conflict with itself when it encounters a `//` comment just before the PHP close tag.
The tokenizer will tokenize whitespace at the end of a `//` comment as part of the `T_COMMENT` token, so the fixer just keeps adding more spaces between the `T_COMMENT` and the `T_CLOSE_TAG` which in the next fixer round is then tokenized again as being part of the `T_COMMENT` resulting in the loop.
> 2.x: Squiz/EmbeddedPHP sniff - prevent fixer conflict

- autoload.php
If the composer autoloader has prepend-autoloader: false set, the PHPCS
autoloader will take priority over the composer autoloader, and composer
will have trouble autoloading its own autoloader.
Avoid all of that by simply not trying to load any classes that are
under the "Composer" namespace.
Fixes #1497
> Don't try to autoload any of Composer's classes

- src/Tokenizers/PHP.php
All backslashes in import function are now tokenized as `T_NS_SEPARATOR`.
Previously first backslash was tokenized incorrectly as `T_STRING`.
The same behaviour we have for classes and constants.
Resolves #1547
> Hotfix #1547 - Tokenize backslashes in import function

- src/Ruleset.php
I was running into trouble with a library containing several standards which all use the same custom autoload file, resulting in fatal `class already declared` errors for the autoloader class.
This simple change fixes that.
> Only include the custom autoload file once.

- src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.inc
- src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.js
- src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.php
- src/Tokenizers/PHP.php
Currently comments starting form /** but without space after that
were not tokenized as doc-block comments.
For example:
```php
/**@var string */
```
was not recognized as doc-block comment.
> Tokenize comments starting from '/**' as doc-block comments

- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.php
- src/Tokenizers/PHP.php
Resolves #1513 
With these changes PR #1492 is not gonna fail.
> Tokenize `yield` keyword as `T_YIELD` on PHP 5.4, and `yield from` as `T_YIELD_FROM` on PHP < 7.0

- src/Sniffs/AbstractVariableSniff.php
- src/Standards/Generic/Sniffs/NamingConventions/CamelCapsFunctionNameSniff.php
- src/Standards/PEAR/Sniffs/NamingConventions/ValidFunctionNameSniff.php
- src/Util/Tokens.php
Add new `$ooScopeTokens` property representing all tokens which typically open class-like constructs.
This is particularly useful if a sniff needs to behave differently when it encounters a token within one of those scopes, like in the case of NamingConvention sniffs.
Applied the use of the property in a few places in existing sniffs.
> Tokens: Add new `$ooScopeTokens` property.

- src/Files/File.php
- tests/Core/File/FindExtendedClassNameTest.inc
- tests/Core/File/FindExtendedClassNameTest.php
I've changed `PHP_CodeSniffer_File::findExtendedClassName()` behaviour so it also works with extended interfaces
> PHP_CodeSniffer_File::findExtendedClassName() works with extended interfaces

- package.xml
- src/Standards/Generic/Docs/CodeAnalysis/AssignmentInConditionStandard.xml
- src/Standards/Generic/Sniffs/CodeAnalysis/AssignmentInConditionSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/AssignmentInConditionUnitTest.inc
- src/Standards/Generic/Tests/CodeAnalysis/AssignmentInConditionUnitTest.php
Most of the time variable assignments being made in conditions are unintentional and are in actual fact typos which were intended as a comparison.
This sniff will warn when any such a variable assignment is found in a condition.
Note: the sniff does currently **not** detect variable assignments in the conditional part of ternaries.
Includes extensive unit tests.
Inspired by [this twitter thread](https://twitter.com/jrf_nl/status/893891839903838209), or rather: the responses I received to my tweet.
> Add new `AssignmentInCondition` sniff to `Generic`

- src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
Changes (just and only) the code block which determines whether a minus sign is used as an operator or a unary, to use `$emptyTokens` instead of `T_WHITESPACE` for improved accuracy.
Fixes #1605
> Squiz/OperatorSpacing: fix false positive on unary minus after comment.

- src/Util/Standards.php
If any external standard or a custom ruleset refers to a complete standard and this standard is registered in the `installed_paths` config as a one-standard directory, a `Reference sniff ...  does not exist` error will be thrown and no sniffs will be run.
Bug introduced in #1450 (by me, sorry!).
The reason for this is that the `getInstalledStandardPath()` method expects a string, but will in actual fact receive a `SimpleXMLElement` object when a complete standard is included by  another standard. This was previously not documented in the function doc block as a possibility.
While in the original code, the `$standards` name was only used as a concatenated string - which  triggered the `SimpleXML.toString()` method -, the fix in #1450 introduced a strict comparison  without the `toString()` …
> Sniffs not loaded when one-standard directories are being registered in `installed_paths`

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
Please see #1550 for more information and see tests.
> Hotfix #1550 - Squiz.Commenting.FunctionComment - return type in doc-block

- src/Standards/Squiz/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.inc.fixed
Saw that this sniff does contain fixers, but didn't have a `.fixed` file to unit test the fixes made.
This PR adds the file. The unit tests pass and the fixes look good.
> Squiz/ObjectOperatorSpacing: add fixed test file

- src/Standards/Squiz/Sniffs/PHP/EmbeddedPhpSniff.php
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.inc
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.inc.fixed
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.php
When a snippet of embedded PHP contains only a comment, the `Squiz.PHP.EmbeddedPhp` sniff would add a semi-colon before the comment which is unnecessary and makes for untidy code.
Without this fix, the unit test snippet would be "fixed" to look like:
```php
<?php ;/* translators: My sites label */ ?>
```
While the change looks more extensive because of the change in indentation, in reality all I did was wrap the relevant code in an `if ($prev !== $stackPtr) {}`.
----
When there is no space between a `/* .. */` comment and the close tag, PHPCS would report an `Empty embedded PHP tag found (Squiz.PHP.EmbeddedPhp.Empty)` error and the fixer would accidentally remove a complete line of embedded PHP.
This bug is related to the inconsistency in …
> Squiz.PHP.EmbeddedPhp: two bug fixes for when there's only a comment

- src/Standards/Squiz/Sniffs/Strings/DoubleQuoteUsageSniff.php
- src/Standards/Squiz/Tests/Strings/DoubleQuoteUsageUnitTest.inc
- src/Standards/Squiz/Tests/Strings/DoubleQuoteUsageUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Strings/DoubleQuoteUsageUnitTest.php
If a string contains tabs, they were previously - unintentionally - replaced by spaces while that is not the responsibility of this sniff.
Includes unit test,
--- 
While examining the sniff code to fix the above issue, I also noticed two other optimizations which could benefit this sniff:
As the last token of the multi-line string is known, it can be returned to skip past subsequent tokens in a multi-line string instead of checking each string token.
Only check strings which are finished double quotes strings.
This offers additional protection against examining unfinished strings during live code checking.
> Squiz.Strings.DoubleQuoteUsage replaces tabs with spaces when fixing

- src/Standards/Squiz/Sniffs/ControlStructures/InlineIfDeclarationSniff.php
I have found unused variable `$fix` in two places, and I think there were missing conditions to run fixer only when `$fix === true`.
> Fix only when fixer is enabled

- .travis.yml
- composer.json
- package.xml
- phpunit.xml.dist
- tests/AllTests.php
- tests/Core/AllTests.php
- tests/Core/ErrorSuppressionTest.php
- tests/Core/File/FindExtendedClassNameTest.php
- tests/Core/File/FindImplementedInterfaceNamesTest.php
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/IsCamelCapsTest.php
- tests/Standards/AbstractSniffUnitTest.php
- tests/Standards/AllSniffs.php
- tests/TestSuite.php
- tests/bootstrap.php
Since today Travis uses PHPUnit 6.x for PHP 7+. The unit tests were not compatible with this and failing because of it.
These relatively minor changes fix that and make the testsuite compatible with both PHPUnit < 6 as well as 6+.
Ref: https://github.com/sebastianbergmann/phpunit/wiki/Release-Announcement-for-PHPUnit-6.0.0
I've also run a test with an external standard using the PHPCS test suite to confirm that this will fix it for them too without any effort on their side and have confirmed it will.
See: https://travis-ci.org/jrfnl/WordPress-Coding-Standards/builds/209592330 - the PHP 7+ builds fail when using PHPCS `master`, but pass when using the branch contained in this PR.
Fixes #1383
> Make the unit test suite compatible with PHPUnit v6

- .travis.yml
The new Trusty images as per Sept 7 include an image for PHP 7.2 (even though it hasn't been released yet) and nightly is now PHP 7.3-dev.
> Travis: run the build tests against PHP 7.2 as well

- package.xml
- src/Files/File.php
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
- tests/Core/AllTests.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/File/IsReferenceTest.inc
- tests/Core/File/IsReferenceTest.php
The `File::isReference()` method misidentified a number of situations where the `T_BITWISE_AND` token was encountered, most notably:
* An array assignment of a calculated value with a _bitwise and_ operator in it ,was being misidentified as a reference.
* A calculated default value for a function parameter with a _bitwise and_ operator in it, was being misidentified as a reference.
* New by reference was not recognized as a reference.
* References to class properties with `self::`, `parent::`, `static::`, `namespace\Class::`, `classname::` were not recognized as references.
This PR fixes these cases and adds dedicated unit test files for this method.
Fixes #1604
As part of this fix, the `File::getMethodParameters()` method also needed to be fixed.
Since PHP 5.6, default values in function …
> Fix `File::isReference()` method

- tests/bootstrap.php
fix for https://github.com/squizlabs/PHP_CodeSniffer/issues/1671 should not break alias but also should fix IDE problems at least phpStorm works. lets see if tests pass
> Possible fix for #1671

- package.xml
- src/Standards/Squiz/Tests/Arrays/ArrayBracketSpacingUnitTest.inc.fixed
The fixed file highlights that the fixer does not only remove spaces, but also removes comments.
Whether this is intentional or not, is unclear to me.
If it is unintentional, I'd be happy to add a second commit to fix this.
> Squiz/ArrayBrackets: Add `fixed` file

- src/Standards/Squiz/Sniffs/Arrays/ArrayBracketSpacingSniff.php
- src/Standards/Squiz/Tests/Arrays/ArrayBracketSpacingUnitTest.inc
- src/Standards/Squiz/Tests/Arrays/ArrayBracketSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayBracketSpacingUnitTest.php
As discussed in https://github.com/squizlabs/PHP_CodeSniffer/pull/1673#issuecomment-335048664, this PR addresses the `Squiz.Arrays.ArrayBracketSpacing` sniff unintentionally removing comments which were placed adjacent to the brackets.
This should not happen anymore once this PR has been merged.
Includes adjusted and additional unit tests.
While looking at the sniff, I noticed two other improvements begging to be made :heart_eyes_cat: 
* The sniff still had some checks in it to prevent it acting on short array syntax. As the short array open/close brackets have their own tokens now, these checks are no longer needed.
* The sniff had a sanity check for parse errors/live coding for the close bracket, but not for the open bracket.
Both of these additional issues have been fixed in separate …
> Squiz.Arrays.ArrayBracketSpacing is removing some comments during fixing

- package.xml
- src/Standards/Squiz/Sniffs/Commenting/InlineCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.js
- src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.js.fixed
- src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.php
I came across this issue when running `phpcbf` with the complete `WordPress` standard against the WPCS unit test files in an attempt to find fixer conflicts.
When an inline comment is the last non-whitespace content in a file, the sniff *will* report an error, but will always fail to fix it as the value of `$next` (formely on line 295) would be `false`.
The file would get the "FAILED TO FIX" status as there is still one "fixable" error remaining, even though the file is correctly overwritten by the fixed file.
As whether or not there should be a blank line at the end of a file is another matter and is covered by the `Generic.Files.EndFileNewline` / `Generic.Files.EndFileNoNewLine` sniffs, this specific case should IMHO not be handled by this sniff anyway.
The fix I'm proposing is to exit …
> Squiz.Commenting.InlineComment will fail to fix comments at the end of the file

- src/Standards/Generic/Sniffs/VersionControl/SubversionPropertiesSniff.php
Don't examine this file again after the first PHP open tag has been passed.
> Generic/SubversionProperties: minor efficiency fix

- package.xml
- src/Standards/Generic/Docs/PHP/DiscourageGotoStandard.xml
- src/Standards/Generic/Sniffs/PHP/DiscourageGotoSniff.php
- src/Standards/Generic/Tests/PHP/DiscourageGotoUnitTest.inc
- src/Standards/Generic/Tests/PHP/DiscourageGotoUnitTest.php
Usage of goto is often seen as a typical code smell.
Includes docs file and unit tests.
Closes #1662
> New "Generic.PHP.DiscourageGoto" sniff

- src/Standards/Squiz/Sniffs/WhiteSpace/SemicolonSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/SemicolonSpacingUnitTest.php
This is a solution for issue #1690 in which I've basically implemented the first of the three options mentioned in the issue.
> Selectively exclude semi-colons found within a for() condition when they are preceded by the open parenthesis or by another ;.
Fixes #1690
> Squiz/SemicolonSpacing: improve handling of semicolons in `for` control structures

- src/Ruleset.php
While it is debatable whether it is a bug or a feature that custom property arrays are unforgiving about spaces surrounding the individual keys and values, all custom array properties in PHPCS itself do not expect spaces around them.
This minor change removes spaces around array keys and values before the property is passed to the sniff.
This means that each of the below examples will now result in the same property value being set:
```xml
<rule ref="Generic.PHP.ForbiddenFunctions">
<properties>
<property name="forbiddenFunctions" value="print=>echo,create_function=>null" type="array" />
<property name="forbiddenFunctions" value="print=>echo, create_function=>null" type="array" />
<property name="forbiddenFunctions" value="print => echo, create_function => null" type="array" /> …
```
> Custom property arrays: be lenient about space usage

- src/Standards/Generic/Tests/Formatting/SpaceAfterNotUnitTest.js
- src/Standards/Generic/Tests/Formatting/SpaceAfterNotUnitTest.js.fixed
PR fourteen in the series to fix fixer conflicts.
This one was easily solved: It's a JS test file, not a PHP file :sunglasses:
> Generic/SpaceAfterNot: fix copy/paste artifact in JS test file

- src/Standards/Generic/Tests/Files/EndFileNewlineUnitTest.3.js
- src/Standards/Generic/Tests/Files/EndFileNoNewlineUnitTest.3.js
Related to #1718 
This typo highlights a bug in the JS Tokenizer were the original file would be processed in such a way that the `'hi);` would end up being tokenized as `T_WHITESPACE`.
Strangely enough, the `1` and `2` JS test files for these two sniffs *do* get tokenized correctly.
> Tests: fix unintentional parse error in js test file

- src/Util/Common.php
When using bash process substitution leaves a file descriptor to read
from. PHP needs its own stream for this, so this translates the two.
Example
`phpcs --file-list=<(git diff origin/master --name-only -- '*.php')`
To only run code sniffer for the changed files
> Enable process substitution

- src/Standards/Generic/Sniffs/WhiteSpace/DisallowSpaceIndentSniff.php
- src/Standards/Generic/Sniffs/WhiteSpace/DisallowTabIndentSniff.php
Both these sniffs include `T_INLINE_HTML` in the `$checkTokens` array, but would only start checking the file **after** the first PHP open tag, so if a file - such as a view - would start with inline HTML and only have the first PHP open tag on line 5, the first 4 lines would not be inspected, nor fixed for tabs vs spaces.
I have not added unit tests for this as it would require to either renumber all the unit tests òr to add a second unit test file for both sniffs. If so desired, I'd be happy to make those changes, but it seemed a bit over the top for such a small change.
> Generic.WhiteSpace.Disallow[Space/Tab]Indent not inspecting content before open tag

- bin/phpcbf.bat
- bin/phpcs.bat
The batch files didn't work for me because neither of those `@var_names@` existed (frankly I don't even know that syntax). I found several blog posts online about how to "fix" this by editing the bat file, but I figured it would be nice if this was simply included in this repository. Better out-of-the-box compatibility, yay!
So I extended the .bat files to support both the original logic, and the situation where "php" is available in the Environment Variables in Windows, which I believe is usually recommended to do. 
(Further, I think `@bin_dir@` is actually never required because we can use %~dp0, but I decided not to touch the orginal logic more than needed)
> Improve compatibility of Windows BAT files

- src/Standards/Squiz/Sniffs/WhiteSpace/LanguageConstructSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/LanguageConstructSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/LanguageConstructSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/LanguageConstructSpacingUnitTest.php
As we discussed in https://github.com/squizlabs/PHP_CodeSniffer/pull/1337#discussion_r129082516 I've created this PR to issues noted in PR #1337
> Squiz.WhiteSpace.LanguageConstructSpacing does not properly check for tabs and newlines

- src/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php
- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.inc
- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.php
First fix in a series to fix the issues found.
Error encountered: `Undefined index: scope_closer in phpcs/src/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php on line 238`
Error occurs when an unfinished function or OO structure is encountered.
While looking at the code, I saw three more minor improvements which I have included in this PR:
* Account for modern PHP OO structures.
The sniff is designed to skip over declarations, but only accounted for functions, classes and interfaces.
This has been updated to include closures, traits and anonymous classes.
* Add the semi-colon to the ignore list for reporting.
In this …
> Squiz/NonExecutableCode: fix undefined index during live coding reviews

- src/Standards/Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php
- src/Standards/Zend/Tests/NamingConventions/ValidVariableNameUnitTest.inc
- src/Standards/Zend/Tests/NamingConventions/ValidVariableNameUnitTest.php
Second fix in a series to fix the issues found.
Error encountered: `Undefined index: scope in phpcs/src/Standards/Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php on line 142`
Error occurred when a variable was encountered in an interface.
Includes unit test
> Zend/ValidVariableName: fix undefined index error when exception is encountered

- src/Standards/Generic/Sniffs/Arrays/DisallowLongArraySyntaxSniff.php
- src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.inc
- src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.inc.fixed
- src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.php
Third fix in a series to fix the issues found.
Error encountered: `Undefined index:  in phpcs/src/Fixer.php on line 524`
Error occurred when due to, for instance, a git merge conflict artifact, the array closer has not been determined.
One of the already existing unit tests results has been adjusted. a found `array` keyword without parentheses was previously being fixed to short array syntax.
However, as this is "unfinished" code, it could just as easily have been the start of an array function call like `array_merge()`, making this a risky fix.
For this case as well as the new case, the error will …
> Generic/DisallowLongArray: fix undefined index when running fixer

- package.xml
- src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.js.fixed
While working on the fixes related to https://github.com/squizlabs/PHP_CodeSniffer/pull/1645#issuecomment-336314794 I noticed that there were no `fixed` files for the `Squiz.Functions.MultiLineFunctionDeclaration` sniff.
> Squiz/MultiLineFunctionDeclaration: add fixed files

- src/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php
Sixth fix in a series to fix the issues found.
For a JS function declared at the very top of the file, there may not be a token on a previous line.
Always moving the pointer one forward at the end of the loop prevents an `undefined offset -1` error.
To reproduce the issue, run:
`phpcbf -p -s --standard=Squiz ./src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.js -vv`
> PEAR/FunctionDeclaration: fix undefined offset error

- src/Standards/Generic/Sniffs/Formatting/MultipleStatementAlignmentSniff.php
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.js
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.js.fixed
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.php
Eighth fix in a series to fix the issues found.
In certain cases, it was possible for the `$expected` padding to become less than zero, leading to the following fatal error during fixing:
`str_repeat(): Second argument has to be greater than or equal to 0 in phpcs/src/Standards/Generic/Sniffs/Formatting/MultipleStatementAlignmentSniff.php on line 293`
This PR fixes that.
> Generic/MultipleStatementAlignment: fix fatal error

- package.xml
- src/Standards/Squiz/Tests/Commenting/PostStatementCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/PostStatementCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/PostStatementCommentUnitTest.js.fixed
While debugging another fixer conflict related to #1645 (comment) I noticed that there were no fixed files for the `Squiz.Commenting.PostStatementComment` sniff.
>  Squiz/PostStatementComment: add fixed files 

- package.xml
- src/Standards/Squiz/Sniffs/CSS/ColonSpacingSniff.php
- src/Standards/Squiz/Tests/CSS/ColonSpacingUnitTest.css
- src/Standards/Squiz/Tests/CSS/ColonSpacingUnitTest.css.fixed
- src/Standards/Squiz/Tests/CSS/ColonSpacingUnitTest.php
Twelfth PR in the series to fix fixer conflicts.
When encountering an empty CSS rule _without_ semi-colon, the `Squiz` standard would end up in a fixer loop caused by a conflict between the following three sniffs: `Squiz.CSS.Indentation`, `Squiz.CSS.ColonSpacing`, `Squiz.CSS.DisallowMultipleStyleDefinitions`.
To reproduce the fixer conflict, run the following command:
`phpcbf -p -s ./src/Standards/Squiz/Tests/CSS/EmptyStyleDefinitionUnitTest.inc --standard=Squiz -vv`
or just run the fixer using this original sniff against the updated test file as included in this PR.
This PR adds a `fixed` file to the unit tests for the `Squiz.CSS.ColonSpacing` sniff and fixes the fixer conflict by making a minor adjustment to that sniff.
> Squiz/CSS/ColonSpacing: fix fixer conflict

- src/Standards/Squiz/Sniffs/Functions/FunctionDeclarationArgumentSpacingSniff.php
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.inc
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.php
Fifth fix in a series to fix the issues found.
When a function declaration contains comments, the `FunctionDeclarationArgumentSpacing` sniff would mistakingly see them as type hints, causing a fixer conflict between that sniff and the `PEAR.Functions.FunctionDeclaration`/`Squiz.Functions.MultiLineFunctionDeclaration` sniff.
Includes unit test demonstrating the issue.
> Squiz/FunctionDeclarationArgumentSpacing: fix fixer conflict

- src/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.inc
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.js
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.js.fixed
Seventh fix in a series to fix the issues found.
Closures - both JS as well as in PHP - have their own token, but only if the structure is finished.
For live coding/parse errors, the structure will be identified as `T_FUNCTION`.
This caused a fixer conflict within the `PEAR.Functions.FunctionDeclaration` sniff and by extension in the `Squiz.Functions.MultiLineFunctionDeclaration` sniff, between the `SpaceAfterFunction` and the `SpaceBeforeOpenParen` error codes.
Unfinished closures can be distinguished from functions by checking for the `scope_opener` having been set.
> PEAR/FunctionDeclaration: fix fixer conflict in handling of unfinished closures

- src/Standards/Squiz/Sniffs/Formatting/OperatorBracketSniff.php
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.inc
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.php
PR thirteen in the series to fix fixer conflicts.
The `Squiz.Formatting.OperatorBracket` sniff would conflict with itself if it could not identify correctly the start or end of the arithmetic expression which would cause it to go into a fixer loop.
The fix in this commit checks if that's the case before throwing the error and if so, does throw the error, but doesn't try to auto-fix it anymore.
Includes additional unit test highlighting the issue.
> Squiz/OperatorBracket: fix fixer conflict

- src/Standards/Squiz/Sniffs/CSS/EmptyStyleDefinitionSniff.php
- src/Standards/Squiz/Tests/CSS/EmptyStyleDefinitionUnitTest.css
- src/Standards/Squiz/Tests/CSS/EmptyStyleDefinitionUnitTest.php
The `Squiz.CSS.EmptyStyleDefinition` sniff checks for CSS styles being defined without value.
This sniff would fail to report an issue if there is no value, but a comment is encountered instead.
> Squiz.CSS.EmptyStyleDefinition sees comment as style definition and fails to report error

- src/Config.php
In a ruleset file (e.g. `phpcs.xml.dist`) it's possible to set CLI parameters with `  <arg name="awesome_arg" value="myval"/>`. 
The CLI itself always overrides the ruleset settings. Unfortunately, it's not possible to reset `basepath`, to show the full path of a file, when `basepath` is set in `phpcs.xml.dist`:
```
<arg name="basepath" value="."/>
```
currently, setting
```
bin/phpcs -q -w --report=emacs --basepath='' src/Util/Tokens.php 
```
will set `basepath` to '.' as you can see in the output of the command
```
src/Util/Tokens.php:7:15: warning - Line exceeds 85 characters; contains 94 characters
```
With this patch, setting basepath in CLI an XML to the empty string `""` will set the internal config settings to `null`. The full path will be show:
``` …
```
> The basepath setting can be unset

- src/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.inc
This file was replaced by the `DisallowShortOpenTagUnitTest.[1-3].inc` files and was already removed from the `package.xml` file.
> Remove unused test file

- .travis.yml
When PHPCS 3.x was being prepared, the builds for PHP < 5.4 were removed from the Travis matrix. However, that also meant that the build against alternative ini settings was removed, while it shouldn't have been.
Re-added against an arbitrary PHP 5.x version.
> Build/Travis: bring back testing with alternative ini settings for PHP 5.x

- src/Standards/Generic/Tests/PHP/DisallowAlternativePHPTagsUnitTest.3.inc
- src/Standards/Generic/Tests/PHP/DisallowAlternativePHPTagsUnitTest.php
The current unit tests did not test that the `warning`s were correctly being thrown when the `asp_tags` ini setting was set to `Off`.
This needs to be tested using a separate test file as the warnings cannot be auto-fixed, so the unit tests would fail if this was tested against unit test file 2.
This change in this commit ensures that the warnings are now also unit tested.
N.B.: The actual testing will only be done once PR #1784 has been merged!
> Generic/DisallowAlternativePHPTags: improve unit tests

- src/Standards/Generic/Sniffs/PHP/SyntaxSniff.php
Cloned and noticed that the testsuite failed on my pc, since I have display_error disabled.
This PR fixes that
> Lint with display_errors enabled

- src/Standards/Squiz/Sniffs/NamingConventions/ValidVariableNameSniff.php
- src/Standards/Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php
Looks like the property is no longer used in either of these sniffs or the parent sniffs they extend.
A quick look at the history reveals that the properties were introduced when the sniffs were written in 2007, but it looks like the use of the property was already removed a few days later (still in 2007) and that the property was never used in a released version.
Removing the properties does not seem to have any negative effects. The unit tests still pass without the property and the sniffs do not throw errors about an "undefined property".
> ValidVariableName sniffs: remove superfluous property setting

- src/Standards/Generic/Sniffs/Functions/OpeningFunctionBraceKernighanRitchieSniff.php
No need to call the `recordMetric()` method again if the metric has already been recorded.
> Generic/OpeningBraceKernighanRitchie: minor efficiency fix

- src/Standards/Squiz/Sniffs/WhiteSpace/LanguageConstructSpacingSniff.php
Small fix which improves on 14b9857876d88ba3ed77318b4c4e51391c16da2d in regards to disregarding this sniff when at the end of the file.
This prevents conflicts with the `Generic.Files.EndFileNewLine`/`Generic.Files.EndFileNoNewLine` sniffs.
Unit test case already exists.
To reproduce the issue, run the following command against `master`:
`phpcbf -p -s -vv ./src/Standards/Squiz/Tests/LanguageConstructSpacingUnitTest.inc --standard=Squiz`
> Squiz/LanguageConstructSpacing: fix fixer conflict

- src/Standards/PSR2/Sniffs/Namespaces/UseDeclarationSniff.php
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.1.inc
Another small PR in the series to fix fixer conflicts.
This fixes two minor issues in the `PSR2.Namespaces.UseDeclaration` sniff:
1. Bow out during live coding.
2. Improved check to bow out in case it's a closure `use` statement.
I've committed the new unit tests separately to facilitate easy testing of the issue. Run `phpcbf` against the unit test commit to see the fixer conflict.
> PSR2/UseDeclaration: fix fixer conflict

- src/Standards/Squiz/Sniffs/PHP/EmbeddedPhpSniff.php
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.inc
- src/Standards/Squiz/Tests/PHP/EmbeddedPhpUnitTest.inc.fixed
- src/Util/Tokens.php
This is basically the same fix as previously pulled & merged in #1554, but now to allow for `// phpcs:ignore` comments as they have their own token.
> The Squiz.PHP.EmbeddedPhp sniff will create a fixer conflict with itself when it encounters a // comment just before the PHP close tag.
> 
> The tokenizer will tokenize whitespace at the end of a // comment as part of the T_COMMENT token, so the fixer just keeps adding more spaces between the T_COMMENT and the T_CLOSE_TAG which in the next fixer round is then tokenized again as being part of the T_COMMENT resulting in the loop.
> Squiz/EmbeddedPhp: Allow for ignore comments

- src/Tokenizers/Tokenizer.php
- tests/Core/ErrorSuppressionTest.php
Fixes #1825
The actual change is quite small, easiest to view by ignoring the indentation change: https://github.com/squizlabs/PHP_CodeSniffer/pull/1827/files?w=1
> A phpcs:enable comment is not tokenized correctly if it is outside a phpcs:disable block

- src/Standards/Squiz/Sniffs/WhiteSpace/SuperfluousWhitespaceSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.php
Setting `ignoreBlankLines` to `true`, would also cause the sniff to ignore single-line comments with superfluous whitespace at the end.
> Squiz.WhiteSpace.SuperfluousWhiteSpace ignoreBlankLines property ignores whitespace after single line comments

- src/Standards/Generic/Sniffs/Files/LineLengthSniff.php
- src/Standards/Generic/Tests/Files/LineLengthUnitTest.1.inc
- src/Standards/Generic/Tests/Files/LineLengthUnitTest.php
Ignore the new `// phpcs:` annotation comments completely when they are on a line by themselves.
Do not record metrics about lines only containing these type of comments.
Errors would not be thrown anyway as lines containing these comments are ignored when throwing errors. Still, this does save the sniff from executing the rest of the logic when its not necessary.
> Generic/LineLength: ignore new PHPCS annotations for the metrics

- src/Standards/Squiz/Sniffs/CSS/IndentationSniff.php
- src/Standards/Squiz/Tests/CSS/IndentationUnitTest.css
- src/Standards/Squiz/Tests/CSS/IndentationUnitTest.css.fixed
This makes the sniff more efficient by skipping the logic for errors which will not be reported anyway.
> Squiz/CSS/Indentation: minor efficiency fix

- src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc.fixed
Includes adjusted unit test.
This fixes a bug where when a `// phpcs:ignore` comment is at the end of a line, it would be incorrectly "fixed" by moving it down a line, making the comment apply to a different line altogether.
> PSR2/SwitchDeclaration: bug fix - ignore PHPCS annotation tokens

- src/Standards/PSR2/Sniffs/Classes/ClassDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc.fixed
This fixes a bug where an error would be reported for a `// phpcs:` comment being on the same line as the class close brace.
> PSR2/ClassDeclaration: bug fix - ignore PHPCS annotation tokens

- src/Standards/Squiz/Sniffs/Classes/ClassDeclarationSniff.php
- src/Standards/Squiz/Tests/Classes/ClassDeclarationUnitTest.inc
- src/Standards/Squiz/Tests/Classes/ClassDeclarationUnitTest.inc.fixed
Includes adjusted unit test.
This fixes a bug where an error would be reported for a `// phpcs:` comment being on the same line as the class close brace, as well as the fixer for that error moving the `// phpcs:` comment, while it shouldn't.
> Squiz/ClassDeclaration: bug fix - ignore PHPCS annotation tokens

- src/Standards/Squiz/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
Related to #1817, which was recently fixed in a7d4118b9ca880acd2b9a7d70b7861e9228756eb. This commit builds onto that fix.
Without the fix, the `NoLineAfterClose` error would not be reported when there is a `phpcs:` comment after a control structure close brace and the needed fix would not be applied.
> Squiz/ControlStructureSpacing: bug fix - allow for PHPCS annotation tokens

- src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.inc.fixed
Without this fix, the fixer would report an error for the spacing above the function and add two blank lines between the `// phpcs:` comment and the function declaration.
> Squiz/FunctionSpacing: bug fix - ignore PHPCS annotation tokens

- src/Standards/Generic/Sniffs/NamingConventions/UpperCaseConstantNameSniff.php
- src/Standards/Generic/Tests/NamingConventions/UpperCaseConstantNameUnitTest.inc
- src/Standards/Generic/Tests/NamingConventions/UpperCaseConstantNameUnitTest.php
This fixes a bug where non-uppercase constants defined using the `const` keyword would not be reported.
It also fixes some outdated code. Looking at the history, originally this sniff also tried to detect _usage_ of non-uppercase constants.
As of commit 4af13118b1fedd89faadd78b9bccf858ce21dbc9 / October 2013, this is no longer the case and only definition of non-uppercase constants is reported.
It looks like both the sniff as well as the unit test case file still contains quite some code related to the old behaviour which could be further simplified, but that is outside the scope of this PR.
> Generic/UpperCaseConstantName: bug fix - ignore PHPCS annotation tokens

- src/Standards/Squiz/Sniffs/PHP/CommentedOutCodeSniff.php
- src/Standards/Squiz/Tests/PHP/CommentedOutCodeUnitTest.inc
- src/Standards/Squiz/Tests/PHP/CommentedOutCodeUnitTest.php
Another one in the series to make sure sniffs handle the new PHPCS annotations correctly.
PHPCS annotations in commented out code would be tokenized and would throw the "commented out" % off, making the sniff underreport commented out code.
This PR fixes that.
While reviewing the sniff to figure out how to fix this in the best way, I came across numerous other bugs and inefficiencies and have fixed each one in a separate commit.
Includes unit tests covering the bugs.
The PR looks bigger than it is. It will be easiest to review by looking at each commit separately.
-------
The regex used to parse out comment fencing was a little too overactive and would change the below commented out code:
```php
//eval('$var = 4;');
```
to
```php
//eval('$var - ;');
```
Now only real comment fencing for …
> Squiz/CommentedOutCode: ignore PHPCS annotations + minor other fixes

- src/Standards/Generic/Sniffs/Commenting/FixmeSniff.php
- src/Standards/Generic/Sniffs/Commenting/TodoSniff.php
As "errors" in the PHPCS annotations will not be reported anyway, no need to examine them for these sniffs.
> Generic/Todo & Fixme: minor efficiency fix

- package.xml
- src/Standards/Generic/Sniffs/Commenting/DocCommentSniff.php
- src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.inc
- src/Standards/Squiz/Sniffs/Commenting/DocCommentAlignmentSniff.php
- src/Standards/Squiz/Sniffs/Commenting/FileCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.2.inc
Another small PR to deal with fixer conflicts.
When a docblock comment is unfinished and at the end of a file - typically found in live coding situations -, fixer conflicts would occur through a combination of the `Generic.Files.(No)Newline`, `Generic.Commenting.DocComment`, `Squiz.Commenting.DocCommentAlignment` and the `Squiz.Commenting.FileComment` sniffs.
The fixer conflicts can be reproduced by checking out the first commit, which just contains the tests demonstrating the issue, and running:
`phpcbf -p -s -vv ./src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.inc --standard=Squiz`
and
`phpcbf -p -s -vv ./src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.2.inc --standard=Squiz`
The changes made in the second commit basically just prevent the sniffs from throwing …
> Various comment sniffs: fix fixer conflicts

- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.php
Add unit tests to document the behaviour when PHPCS annotations are encountered.
This is basically for the `AfterComment` error. As that error is thrown on the line containing the comment, it is automatically ignored for the PHPCS annotations, so no sniff code adjustments were needed.
> Squiz/MemberVarSpacing: document behaviour with PHPCS annotations

- src/Standards/PEAR/Sniffs/Commenting/FunctionCommentSniff.php
```
10 | ERROR | [ ] Missing function doc comment
20 | ERROR | [ ] Missing function doc comment
30 | ERROR | [ ] Missing function doc comment
```
```
10 | ERROR | [ ] Missing function doc comment: lorem()
20 | ERROR | [ ] Missing function doc comment: ipsum()
30 | ERROR | [ ] Missing function doc comment: dolor()
```
```
<?php
class Foo
{
public function lorem()
{
}
private function ipsum()
{
}
}
function dolor()
{
}
```
> Add function name on missing function doc comment

- src/Standards/PEAR/Sniffs/Commenting/ClassCommentSniff.php
- src/Standards/Squiz/Sniffs/Commenting/ClassCommentSniff.php
This pull-request modifies both PEAR and Squiz coding standards.
Normally, people define one class per file, in this case the name of the class may be redundant if the name of the file is the same. However, in cases where the developer is not adhering to this standard it may be helpful to know if all the classes contained in the same file have a proper DocBlock comment.
Also notice the _"Missing file doc comment"_ in the examples below. I will not submit a pull-request for this because adding the name of the file in front of the warning is really redundant considering that `phpcs` already prints the name of the file before the warning/error table.
The error message also follow the same format suggested [here](https://github.com/squizlabs/PHP_CodeSniffer/pull/1865#issuecomment-362099764). …
> Add class name on missing class doc comment

- src/Standards/Generic/Sniffs/Formatting/MultipleStatementAlignmentSniff.php
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc.fixed
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.php
Multi-line arrays interspersed with comments were treated differently than multi-line arrays without comments.
This aligns the behaviour of both to be the same.
> MultipleStatementAlignment: do not break on comments within arrays.

- src/Standards/PSR2/Sniffs/Namespaces/UseDeclarationSniff.php
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.8.inc
> PSR2/UseDeclaration: allow comments after the last USE statement

- src/Files/File.php
Looks like a copy/paste artifact.
> Documentation: fix documentation for the `recordMetric()` method

- src/Standards/PSR2/Sniffs/Namespaces/UseDeclarationSniff.php
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.10.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.10.inc.fixed
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.11.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.11.inc.fixed
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.12.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.12.inc.fixed
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.13.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.13.inc.fixed
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.14.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.14.inc.fixed
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.8.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.9.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.php
see #1898 
The test that was merged with #1893 didn't actually test that lines after a user statement weren't blank as PHPCS would determine this to be the end of the file due to lack of class declaration or other valid code lines.
> Prove regression from #1893

- src/Tokenizers/Tokenizer.php
- tests/Core/ErrorSuppressionTest.php
This PR should go into `3.2.3` as it fixes two bugs in how the tokenizer deals with the new PHPCS annotations.
This PR will be easiest to review by looking at each commit individually.
**Bug 1**:
PHPCS annotations in tab-indented multi-line block comments were not recognized nor tokenized correctly.
Includes extensive unit tests.
**Bug 2**:
A `phpcs:set` would always cause the whole line to be ignored, even when its used as an end-comment.
As `phpcs:set` annotations are not covered in the unit test file, I wasn't sure were to add the tests for this.
**Other**:
While staring at the code I saw a few minor other optimizations/typos, those have been fixed in separate commits.
> Fixed PHPCS annotations in multi-line tab-indented comments + not ignoring whole line for phpcs:set

- src/Standards/PEAR/Sniffs/ControlStructures/MultiLineConditionSniff.php
- src/Standards/PEAR/Tests/ControlStructures/MultiLineConditionUnitTest.inc
- src/Standards/PEAR/Tests/ControlStructures/MultiLineConditionUnitTest.inc.fixed
- src/Standards/PEAR/Tests/ControlStructures/MultiLineConditionUnitTest.js
- src/Standards/PEAR/Tests/ControlStructures/MultiLineConditionUnitTest.js.fixed
- src/Standards/PEAR/Tests/ControlStructures/MultiLineConditionUnitTest.php
Another one in the series to fix the sniffs to deal correctly with the new PHPCS annotations. Three more sniffs to go.
This PR should be tagged for the `3.2.3` release,
To review the PR, please look at the individual commits.
This PR fixes three issues in the `PEAR.ControlStructures.MultiLineCondition` sniff when it encountered PHPCS annotations within multi-line conditions:
1. It didn't allow for trailing PHPCS annotations.
2. When PHPCS annotations were encountered within a multi-line condition, it could occur that the same `StartWithBoolean` error would be thrown twice for the same line.
3. When a condition was spread out across multiple lines interspersed with comments and/or PHPCS annotations, the fixer would remove the comments.
Includes extensive unit tests.
The PR can be tested by …
> PEAR/MultiLineCondition: bug fix - deal correctly with PHPCS annotations

- src/Standards/Squiz/Sniffs/PHP/CommentedOutCodeSniff.php
- src/Standards/Squiz/Tests/PHP/CommentedOutCodeUnitTest.inc
- src/Standards/Squiz/Tests/PHP/CommentedOutCodeUnitTest.php
This implements option 3 and 5 as discussed in #1910:
* Ignore comments which only consist of a silence operator + one alphanumeric word.
This will prevent false positives on most (not all) ignore annotations from other tools.
* Ignore comments which result in only two or less non-whitespace tokens.
This will prevent false positives on `// Ok!` type of comments.
To implement this, I've elected to remove the open/close tags from the token array of the retokenized comment to prevent having to make the calculations more complicated.
Fixes #1910
Fixes #1912
> CommentedOutCode: ignore small comments and annotations from other tools

- src/Reports/Json.php
I had issues with a sniffer, which use class names in the source. These class names had (not escaped) namespaces included. This make the json output invalid.
After looking at the code, I was wondering, why PHP_CodeSniffer doesn't use json_encode for this task.
> use json_encode in JSON reports to fix invalid outputs

- tests/Standards/AllSniffs.php
By extracting the retrieval of the installed standards a third party ruleset/sniff developer, me, can easily create an extension of `AllSniffs` that only runs the sniffs of the ruleset in question.
This simple extraction will prevent doing cli magic like `--filter` and allow full configurability in a `phpunit.xml`.
Adds to #1756
> Improve testability of rulesets

- package.xml
- src/Standards/Generic/Docs/WhiteSpace/ArbitraryParenthesesSpacingStandard.xml
- src/Standards/Generic/Sniffs/WhiteSpace/ArbitraryParenthesesSpacingSniff.php
- src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.inc
- src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.php
While working on the big WP Core auto-fixing project, I realized there was no sniff available to check the whitespace around arbitrary parentheses. So, here goes.
This new sniff checks the spacing on the **_inside_** of arbitrary parentheses.
A conscious choice has been made not to check on the outside as this would very quickly conflict with other sniffs.
Arbitrary parentheses, for the purposes of this sniff, are all parentheses which do not belong to a control structure, function declaration, function call or language construct.
This is to prevent conflicts and duplication with rules for those type of constructs.
**Notes:**
* The sniff will throw (fixable) errors when an incorrect amount of whitespace (too much/too little) has been found on the inside or the parenthesis.
* The sniff …
> New Generic.WhiteSpace.ArbitraryParenthesesSpacing sniff

- autoload.php
- src/Runner.php
I've seen similar issues now in several external standards, where people are receiving a `Cannot declare class Standard\Sniffs\Category\SomethingSniff, because the name is already in use` error.
I've not been able to reproduce the issues, but noticed that - at least in some of the cases - this involved external sniffs which extend other external sniffs and use a `use` statement for the parent sniff.
I suspect that the fact that I cannot reproduce this, may be due to sniffs not loading in a predefined order, but depending on when the directive to include the sniff/standard is encountered in the ruleset.
I imagine that if a child sniff is included first and a parent sniff second, this causes the fatal error (though I haven't been able to reproduce it that way either).
Using `include_once` …
> Fix fatal 'class already declared' errors when using external standards

- src/Standards/Generic/Sniffs/Formatting/MultipleStatementAlignmentSniff.php
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc.fixed
This simplifies the fixes which were previously committed to fix #1870 and #1848, which were released in `3.2.3`.
Both those fixes try to prevent the sniff getting confused over (potentially) multi-line value assignments, such as closures and arrays.
The simplification removes the previously added code in favour of skipping to the end of a statement as soon as an assignment operator has been found.
This might also make the sniff marginally faster as the tokens between the assignment operator and the end of the statement will no longer be examined.
N.B.: The reason for going one back from the end of the assignment (line 241), is that otherwise the code addressing the issue covered by the unit test on line 220 / added in commit 579d39cac3163bdf05ce1b50a7e470acd452735b would not be …
> Generic/MultipleStatementAlignment: fix bug/list syntax before assignment operator

- package.xml
- src/Files/File.php
- src/Standards/Squiz/Tests/NamingConventions/ValidVariableNameUnitTest.inc
- src/Standards/Squiz/Tests/NamingConventions/ValidVariableNameUnitTest.php
- tests/Core/AllTests.php
- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
Adds dedicated unit tests for the `File::getMemberProperties()` method.
Also minor documentation update for the method itself.
Related to #1707
-----
I realized after I'd pulled it that I'd forgotten to add the new tests to the `tests/Core/AllTests.php` file. 
Once I added them, a bug with PHP4 `var $property` type declarations started showing.
I fixed that in a separate commit.
I also realized that the tests didn't yet cover "_group property declarations_". While these aren't very common in most PHP projects, they are supported by the language and therefore should be correctly handled by the `File::getMemberProperties()` method.
Once I added the additional unit tests, it became clear that _group property declarations_ which included value definitions were not (yet) supported by the …
> Tests: Add unit tests for the `File::getMemberProperties()` method

- src/Standards/Squiz/Sniffs/WhiteSpace/ScopeKeywordSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.php
Tenth PR in the series to fix fixer conflicts.
Fixer conflict can be reproduced by running the below command against `master`:
`phpcbf -p -s ./src/Standards/Squiz/Tests/NamingConventions/ValidVariableNameUnitTest.inc --standard=Squiz`
To fix this, I reviewed the whole sniff.
Notes:
* The sniff did not have a `fixed` file, so added that.
* The check for whether or not the scope keyword is used for a property or in another capacity, should be done in a style-independent manner. As it was, the sniff could trigger in undesired situations. Fixed + added unit tests to safeguard against this.
* When there would be more than one whitespace token between the keyword and the next content, only one whitespace token would be addressed by the fixer. The next whitespace token would fall through to the …
> Squiz/ScopeKeywordSpacing: improve sniff + fix fixer conflict

- src/Sniffs/AbstractScopeSniff.php
- src/Sniffs/AbstractVariableSniff.php
- src/Standards/Squiz/Sniffs/WhiteSpace/MemberVarSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.php
Related to #1715 and #1720, the other sniff involved in the fixer conflict mentioned in #1720.
**TL;DR>** Adds unit test cases with multi-line multi-property declarations and unit tests for class importing traits.
For the multi-line multi-property declarations I've adjusted the sniff to handle this more graciously as it would previously:
* correct the number of lines above the line for each variable
* not correct the number of lines above the line containing the scope keyword
IMHO this is incorrect and only the lines above the line containing the scope keyword should be checked & fixed.
By returning the `$stackPtr` of the semi-colon at the end of the property declaration, we skip past the additional variables.
As the abstract classes this class extends from did not allow for passing a …
>  Squiz/MemberVarSpacing: improved handling of multi-line property declarations

- src/Standards/Squiz/Sniffs/Commenting/InlineCommentSniff.php
- src/Standards/Squiz/ruleset.xml
Fourth fix in a series to fix the issues found.
When an inline comment is found at the end of a function, removing a blank line after it conflicts with the `Squiz.WhiteSpace.FunctionClosingBraceSpace` sniff which demands a blank line at the end of a function.
To reproduce the issue, run (against `master`):
`phpcbf -p -s --standard=Squiz ./src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.inc -vv`
I have chosen to fix this by adding a specific error code for that situation and excluding that error code from the `Squiz` ruleset.
This way, the backward-compatibility break for other standards using the …
> Squiz/InlineComment: fix fixer conflict when comment found at end of function

- src/Standards/Generic/Sniffs/Functions/OpeningFunctionBraceBsdAllmanSniff.php
- src/Standards/Generic/Sniffs/Functions/OpeningFunctionBraceKernighanRitchieSniff.php
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceBsdAllmanUnitTest.inc
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceBsdAllmanUnitTest.inc.fixed
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceBsdAllmanUnitTest.php
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceKernighanRitchieUnitTest.inc
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceKernighanRitchieUnitTest.inc.fixed
As discussed in #1931, moving a trailing `phpcs:ignore` annotation to the next line changes its meaning, which is what currently happens when the `ContentAfterBrace` error is triggered by one of the new PHPCS annotations in the `Generic.Functions.OpeningFunctionBraceKernighanRitchie` and `Generic.Functions.OpeningFunctionBraceBsdAllman` sniffs.
For the `Generic.Functions.OpeningFunctionBraceBsdAllman` sniff, this also impacts the fixer of the `BraceOnSameLine` errror which could also move the comment down.
This PR fixes that.
For this fix, I've chosen to ignore *all* the PHPCS annotations, not just the `phpcs:ignore` one. If so desired, I can change the PR to only make an exception for a trailing `phpcs:ignore` comment and to move `phpcs:disable/enable/set` comments to the next line, just …
> Generic opening brace placement sniffs incorrectly move PHPCS annotations

- src/Sniffs/AbstractVariableSniff.php
- src/Standards/Squiz/Sniffs/NamingConventions/ValidVariableNameSniff.php
- src/Standards/Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php
Duplicate code removal.
The list of PHP reserved variables was up to now defined in four places in two separate sniffs.
Both these sniffs extend the `AbstractVariableSniff`, so it makes sense to define the list as a property of that sniff and to re-use it in the individual sniffs instead.
Also changes the array format in a way that the more efficient `isset()` can be used instead of `in_array()`.
> AbstractVariableSniff: add list of PHP reserved variables

- src/Tokenizers/Tokenizer.php
I actually profiled and micro-benchmarked this line. I found that rtrim() is by far the fastest when applied on real-life content, 10 times faster than str_replace() and 2 times faster than ltrim(). Why? Because real-life code typically contains way more strings that are not exclusively made of whitespace. This check needs to be fast for these non-whitespace cases. Furthermore, if a string contains whitespace, that's typically not at the end of the string. rtrim() immediately stops doing anything in this case, while ltrim() needs to trim all tabs from the beginning of the string first, and str_replace() needs to replace all tabs, even tabs in the middle of the string that are not relevant for this check.
So this change is all about bailing out as early as possible.
> Improve Tokenizer::replaceTabsInToken performance

- src/Standards/Squiz/Sniffs/WhiteSpace/SuperfluousWhitespaceSniff.php
- src/Tokenizers/Tokenizer.php
The ignore setting for PHPCS annotations on their own line uses `['all' => true]` everywhere else, except for the `phpcs:set` annotation.
This has now been made consistent.
----
The change in the tokenizer exposed a bug in the `Squiz.WhiteSpace.SuperfluousWhitespace` sniff, where if the last non-whitespace token in a file is a PHPCS annotation, the fixer would not kick in.
Moving the fixer start token determination for JS/CSS files into the fixer code block, fixes this.
> phpcs:set annotations do not cause the line they are on to be ignored

- src/Tokenizers/Tokenizer.php
I was surprised to see the impact this minor optimization does have. In the example run I profiled Config::__get() was called about 88,000 times, and these calls accounted for about 4.6% of the total runtime.
With this optimization applied Config::__get() is now called 5,000 times, and these calls now account for 0.3% of the total runtime.
Yes, I'm talking total runtime. This means a run of 20 seconds total will be about a second faster.
Before:
After:
> Avoid calling Config::__get() in a loop

- src/Standards/Squiz/Sniffs/WhiteSpace/SuperfluousWhitespaceSniff.php
This does not have a measurable effect on runtime, but immensely reduces the number of calls to this function. In the run I profiled hasCondition() was called about 18,000 times before and 10,000 times after this patch. The total runtime for these calls went from 1.3% to 1.1%.
Note there are a few more sniffs where the exact same optimization can be applied.
> Avoid calling File::hasCondition() twice

- src/Standards/Generic/Sniffs/CodeAnalysis/AssignmentInConditionSniff.php
A `while()` condition is the only control structure in which it is sometimes legitimate to use an assignment in condition.
Having a separate error code will enable people to selectively exclude warnings for this.
> Generic/AssignmentInCondition: add separate errorcode for assignment found in while

- src/Standards/Squiz/Sniffs/Scope/MemberVarScopeSniff.php
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.inc
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.php
This fix builds upon the earlier fix in PR #1715, which improved the handling of group property declarations for the `File::getMemberProperties()` method.
This sniff now just defers to the `File::getMemberProperties()` method to determine whether the visibility of a property has been set.
Fixes #1963
> Squiz/MemberVarScope: fix handling of multi-line properties

- src/Standards/Squiz/Sniffs/Functions/MultiLineFunctionDeclarationSniff.php
- src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.inc
- src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.inc.fixed
Very easy fix ;-)
Should also solve any issues this particular check in the sniff has/had with trailing PHPCS annotations.
_Note: this sniff most likely does still have an issue with PHPCS annotations when fixing an incorrect multi-line function declaration._
Fixes #1959
> SquizMultiLineFunctionDeclaration: fix bug when param has trailing comment/PHPCS annotation

- src/Tokenizers/PHP.php
I actually profiled this and found Tokens::tokenName() is called hundreds of thousands of times here. Even if the method implementation appears to be trivial, it is expensive. The line touched in this patch always converts the same integer constant to a string, and compares the string then. In the profile run I did this line alone accounts for 3% of the total runtime. PHPs define() is much faster, even if called as often as it is the case here.
> Replace slow Tokens::tokenName() with define()

- src/Ruleset.php
Currently if we want override array property in ruleset we have to do:
```xml
<property name="forbiddenFunctions" type="array"
value="print=>echo,create_function=>null" />
```
It's fine as long as the array content is short.
With this feature the new method to define arrays in the ruleset is introduced:
```xml
<property name="forbiddenFunctions" type="array">
<element key="print" value="echo"/>
<element key="create_function" value="null"/>
</property>
```
> Feature - define arrays in ruleset

- src/Standards/Generic/Sniffs/Commenting/DocCommentSniff.php
- src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.inc
- src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.js
- src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.php
Fixes issue #1989 
In the existing code, when the short description was missing, then ``DocCommentSniff`` ``process()`` would return immediately. The parsing of the tag problems comes later, and so that did not happen.
With this PR, the various problems related to the description lines put inside an ``else`` of the ``Check for a comment description`` ``if`` statement - so that they are only processed if there is at least a description found. The "early" return is removed. This allows the code to continue, examining matters related to tags.
> Process doc tags when short description is missing

- autoload.php
- src/Reporter.php
This allows for external standards to provide portable custom reports while installed in an arbitrary directory.
* The external standard has to make sure it includes an `<autoload>` directive in the ruleset and sort out the loading of the custom report classes through a `spl_autoload_register()`-ed autoloader.
* The name of the custom report class can be provided either on the command line using `--report=...` or via the ruleset using `<arg name="report" value=".."/>`.
* The name of the custom report class can be either the Fully Qualified report class name òr the standard relative class name (i.e. without the top-level namespace for the standard).
- The FQN does not have to be prefixed with an `\`, but things will work just fine if it is.
- If just the class name is provided, PHPCS will …
> Allow requesting a custom report using the report name or FQN

- src/Files/File.php
`explode` function returns array and we should count number of elements in that array.
Comparison `ARR >= 3` always returns `true`.
Code (https://3v4l.org/NkdIT):
```php
var_dump([] >= 3);
var_dump([1] >= 3);
var_dump([1, 2] >= 3);
var_dump([1, 2, 3] >= 3);
var_dump([1, 2, 3, 4] >= 3);
```
Results:
```
bool(true)
bool(true)
bool(true)
bool(true)
bool(true)
```
> Fixed counting elements in array in if statements

- src/Standards/Generic/Sniffs/Formatting/MultipleStatementAlignmentSniff.php
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc.fixed
The case where PHP and HTML is mixed was not taken into account by the sniff up to now.
> Generic.Formatting.MultipleStatementAlignment does see PHP close tag as end of statement block

- src/Standards/Generic/Docs/PHP/LowerCaseTypeStandard.xml
- src/Standards/Generic/Sniffs/PHP/LowerCaseTypeSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.php
This PR ports over various things which were already covered by PR #1685, but not (yet) covered by the new `Generic.PHP.LowerCaseType` sniff.
@gsherwood As the `Generic.PHP.LowerCaseType` sniff is new to PHPCS 3.3.0, it would be advisable to merge this PR before releasing PHPCS 3.3.0.
All significant changes are accompanied by unit tests.
* `parent` is a valid type declaration and has been supported since the beginning, though only properly since PHP 5.2.
* `void` was added in PHP 7.1 (return type only).
* `object` was added in PHP 7.2.
Differentiate the error messages and error codes to enable modular usage of the sniff.
For (long) multi-line function declarations, it will be more helpful throwing the error on the line where the error actually occurs instead of on the line of the …
> 3.3.0: Generic/LowerCaseType: allow for nullable types and more

- src/Standards/PEAR/Sniffs/NamingConventions/ValidFunctionNameSniff.php
- src/Standards/PEAR/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
- src/Standards/PEAR/Tests/NamingConventions/ValidFunctionNameUnitTest.php
When a function name would contain more than one subsequent underscore, the `explode()` call will create entries containing an empty string in the `$nameBits` array.
The proposed fix will remove those empty entries before testing each `$bit`.
([`array_filter()` called without callback](http://php.net/manual/en/function.array-filter.php#example-6090) will remove everything which after juggling would evaluate to `false`).
**Note:** The resulting suggested `$newName` for the function will no longer contain a double underscore either.
If it would be desired to allow the double underscore, the alternative would be to change the `if ($bit{0} !== strtoupper($bit{0}))` condition to `if ($bit !== '' && $bit{0} !== strtoupper($bit{0}))`. This would also require an adjustment in the inner loop which …
> PEAR/ValidFunctionName: fix uninitialized string offset error

- src/Files/File.php
When a file uses tabs and a `tab-width` is set, the `content` will have spaces instead of tabs.
This could lead to situations where the output of `getTokensAsString()` when used to move content about would unintentionally replace tabs with spaces.
This small change allows for retrieving the original content by passing a third parameter.
I've chosen to add a parameter rather than change the default function behaviour to prevent breaks for existing sniffs relying on this behaviour, like the Squiz/ArrayDeclaration sniff: https://github.com/squizlabs/PHP_CodeSniffer/blob/2ca6cf56420616cb47a88249eb5e3520f0e31ac7/src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php#L477-L480
> `getTokensAsString()` method: Add option to respect original content

- package.xml
- src/Standards/Squiz/Sniffs/WhiteSpace/SuperfluousWhitespaceSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.3.inc
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.3.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.4.inc
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.4.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.5.inc
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.5.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.php
As unicode regexes can be even more expensive than regular regexes, I've moved the check for non-whitespace out of the loop.
Includes unit tests. The `5` file is the one with unicode. The other ones are just more confirmation that the sniff works as expected.
Fixes #2038
> Squiz/SuperfluousWhitespace: recognize unicode whitespace at start/end of file

- src/Standards/Squiz/Sniffs/Scope/MemberVarScopeSniff.php
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.inc
- src/Standards/Squiz/Tests/Scope/MemberVarScopeUnitTest.php
Encountered this fatal error when running the `Squiz` standard over the `Squiz` tests files.
The error can be reproduced on `master` by running `phpcs -p -s ./src/Standards/Squiz/Tests/Classes/ValidClassNameUnitTest.inc --standard=Squiz --sniffs=Squiz.Scope.MemberVarScope`
```
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_specified in /PHPCS/src/Standards/Squiz/Sniffs/Scope/MemberVarScopeSniff.php on line 33 in /PHPCS/src/Runner.php on line 562
PHP_CodeSniffer\Exceptions\RuntimeException: Undefined index: scope_specified in /PHPCS/src/Standards/Squiz/Sniffs/Scope/MemberVarScopeSniff.php on line 33 in /PHPCS/src/Runner.php on line 562
Call Stack:
0.0000     349528   1. {main}() \PHP_CodeSniffer\bin\phpcbf:0
0.0050 …
```
> Squiz.Scope.MemberVarScope throws fatal error when a property is found in an interface

- src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.inc.fixed
Fixer conflict can be reproduced by running the below command against `master`:
`phpcbf -p -s ./src/Standards/Generic/Tests/Files/LineEndingsUnitTest.inc --standard=Squiz`
Basically, the `Squiz.WhiteSpace.FunctionSpacing` sniff demands 2 blank lines between functions, while the `Squiz.PHP.EmbeddedPHP` sniff demands no blank lines at the start of an embedded PHP block, which causes a fixer conflict if a function is declared at the top of an embedded PHP block.
To fix this, I've given precedence to the `EmbeddedPHP` sniff - i.e. no blank lines between the PHP open tag and the start of the function declaration -.
The `FunctionSpacing` will now ignore functions at the start of an embedded PHP block.
----
Side-note: the docblock at the top of the …
> Squiz/FunctionSpacing: fix fixer conflict - ignore function at start of embedded PHP

- .travis.yml
- src/Config.php
- src/Standards/Generic/Sniffs/PHP/SyntaxSniff.php
- src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.php
- src/Standards/Generic/Tests/Files/EndFileNewlineUnitTest.php
- src/Standards/Generic/Tests/Files/EndFileNoNewlineUnitTest.php
- src/Standards/Generic/Tests/PHP/DisallowAlternativePHPTagsUnitTest.php
- src/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.php
- src/Standards/PSR2/Tests/Files/EndFileNewlineUnitTest.php
- src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.php
HHVM LTS 3.24 is the last version to support PHP 5 compatibility
the third paragraph of the announcement states "HHVM will not aim to target PHP7" and further down "We do not intend to be the runtime of choice for folks with pure PHP7 code." (HHVM will only support HACK going forward)
https://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html
> Drop HHVM testing

- package.xml
- src/Standards/PSR2/Sniffs/Namespaces/UseDeclarationSniff.php
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.16.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.16.inc.fixed
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.17.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.5.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.5.inc.fixed
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.php
**Note**: This PR will be easiest to review by looking at the individual commits.
As of PHP 7.2 grouped use statements can have trailing comma's after the last child statement.
Ref: https://wiki.php.net/rfc/list-syntax-trailing-commas
The sniff's fixer did not take this into account up to now and would cause a run-away fixer run which wouldn't stop until PHP ran out of memory.
This has now been fixed.
Also:
While fixing this I also looked into how comments and PHPCS annotations were handled and have adjusted the code for improved fixing of the whitespace between `use` statements without interferring with the comments/annotations.
Prevent accidentally removing code between a group use statement with a forgotten semi-colon (parse error) and the next statement …
>  PSR2/UseDeclaration: fix runaway fixer and more

- src/Standards/Generic/Sniffs/Functions/FunctionCallArgumentSpacingSniff.php
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.php
This PR addresses a fixer conflict between the `Generic.Functions.FunctionCallArgumentSpacing` and the `PEAR.Functions.FunctionCallSignature` sniffs when these sniffs encounter a multi-line function call.
The fixer conflict can be reproduced by running:
`phpcbf -p -s ./test.php --standard=PEAR --sniffs=Generic.Functions.FunctionCallArgumentSpacing,PEAR.Functions.FunctionCallSignature`
against the following code:
```php
my_function_call(
'a'
/* Comment */
,'b'
, 'c' // Comment.
,'d'
,'e' // phpcs:ignore Standard.Category.Sniff -- for reasons.
, 'f'
);
```
If given half a chance, the fixer in the `Generic.Functions.FunctionCallArgumentSpacing` sniff would change multi-line function calls to single-line.
This PR fixes this.
Includes unit tests
> Generic/FunctionCallArgumentSpacing: fix fixer conflict

- src/Reports/Source.php
Probably a copy/paste artifact or a left over from an old(er) implementation.
> Reports/Source: remove some code which is never used

- src/Reports/Source.php
The original sort order of the sources in the source report was based on the error/warning count alone.
This would make the resulting order for errors with the same count unpredictable and different on each run, making it more difficult to compare between runs.
The change proposed in this PR sorts the list first on the error/warning count and secondary on the source code, stabilizing the sort order.
> Reports/Source: sort sources on count and source

- src/Files/File.php
- src/Tokenizers/CSS.php
- src/Tokenizers/Tokenizer.php
As of PHP 7.3, using `continue` to target a `switch` control structure will throw an `E_WARNING`.
Applying `continue` to a `switch` is equivalent to using `break` and more often than not, a `continue` targeting a higher level control structure is actually intended.
To target the higher level control structure, a numeric argument has to be passed to `continue`.
Refs:
* http://php.net/manual/en/control-structures.continue.php
* https://github.com/php/php-src/pull/3364
* https://wiki.php.net/rfc/continue_on_switch_deprecation
This change has been recently committed to PHP itself and will break the build against `nightly` for the current `master` already.
See: https://travis-ci.org/jrfnl/PHP_CodeSniffer/jobs/401533444 (this branch, but without commits, so equal to the current PHPCS `master`). …
> Fix compatibility with PHP 7.3/nightly

- src/Reports/Junit.php
'errors' attribute is required by xunit jenkins plugin (that's weird cause junit itself seems to define that parameter optional). Still it would be good to have PHP_CodeSniffer junit xml report compatible with Jenkins xunit plugin.
https://github.com/jenkinsci/xunit-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/xunit/types/model/xsd/junit-10.xsd
> added errors attribute with value zero to junit report testsuites

- src/Reports/Info.php
As discussed in #2102, this PR makes the following changes to improve the readability of the `Info` report for multi-line metrics:
1. Start the first metric value on a new line.
2. Align the arrows, and by extension the counts, of the metrics.
3. Move the totals to a separate line underneath the list of metric values.
4. Right align the counts.
5. Add thousands separators to the counts.
6. Right align the percentages.
7. Stop it reporting 0% for metrics and report <0.01% instead.
Fixes #2102
> Report Info: various fixes to improve readability of multi-line metrics

- tests/Standards/AbstractSniffUnitTest.php
Just a pet peeve.
Some IDE/code editors create `.bak` files when a file has been edited which cause the unit test runs to fail as these files would be tested as if they were intentional test case files.
This minor fix prevents this from happening.
> Unit test runner: ignore `bak` files

- src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.php
When too many blank lines are found before a function, the `Before/BeforeFirst` fixer would unnecessarily also remove the indentation of the `$nextContent` line, meaning that this sniff would **always** need to be accompanied by one or more sniffs to fix the indentation again.
As this sniff is about blank lines between functions, not about indentation, I consider this a bug.
This minor change fixes it.
Includes unit tests demonstrating the issue.
> Squiz.WhiteSpace.FunctionSpacing is removing indents from the start of functions when fixing

- src/Reports/Info.php
Just realized that I hadn't added this to the previous PR #2103 yet.
As the metric keys may be numeric, the `SORT_NATURAL` flag (introduced in PHP 5.4) will ensure that numbers with equal counts will be sorted properly, i.e.:
Without this these would be sorted like:
```
1  => 10 (... %)
12 => 10 (... %)
2  => 10 (... %)
```
Now they will be sorted like so:
```
1  => 10 (... %)
2  => 10 (... %)
12 => 10 (... %)
```
> Report info: minor sorting improvement

- src/Standards/Squiz/Sniffs/PHP/DisallowMultipleAssignmentsSniff.php
- src/Standards/Squiz/Tests/PHP/DisallowMultipleAssignmentsUnitTest.inc
A variable assignment in the condition of a `while` loop may well be enclosed in additional parenthesis to prevent issues with operator precedence when comparing the assigned value within the same condition.
Example:
```php
while ( ( $csvdata = fgetcsv( $handle, 2000, $separator ) ) !== false ) {}
```
Previously only the lowest level `parenthesis_owner` would be examined to determine whether or not to report this as an error. Now, for `while` loops only, the parenthesis owners of all nested parenthesis will be examined.
Examining them early on in the sniff as the rest of the logic is superfluous if the assignment should be ignored anyway.
> Squiz.PHP.DisallowMultipleAssignments false positive in while loop conditions

- src/Files/File.php
- tests/Core/File/FindExtendedClassNameTest.inc
- tests/Core/File/FindExtendedClassNameTest.php
The method used the class scope closer to end searches, which meant that a non-extended class which contained a nested extended class would return the extended class name of the nested class, instead of `false`.
Switching this to the scope opener, fixes this.
Included unit tests.
> File::findExtendedClassName() doesn't support nested classes

- tests/Core/File/FindExtendedClassNameTest.inc
- tests/Core/File/FindExtendedClassNameTest.php
* Replace all the individual tests which are basically all duplicates of each other, with one test method and a data provider.
* Add two more tests
Redundancy - just making sure for now and later that the method will not get confused over class declarations which both `extend` as well as `implement`.
> FindExtendedClassNameTest: Girlscouting & two additional tests

- tests/Core/File/FindImplementedInterfaceNamesTest.inc
- tests/Core/File/FindImplementedInterfaceNamesTest.php
* Replace all the individual tests which are basically all duplicates of each other, with one test method and a data provider.
* Add two more tests
Redundancy - just making sure for now and later that the method will not get confused over class declarations which both `extend` as well as `implement`.
> FindImplementedInterfaceNamesTest: Girlscouting & two additional tests

- tests/Core/File/FindImplementedInterfaceNamesTest.inc
Looks like this line was copied/pasted at some point, but has no function in this test file, so removing it.
> FindImplementedInterfaceNamesTest: Remove redundant line

- src/Standards/Generic/Sniffs/PHP/NoSilencedErrorsSniff.php
... by showing a snippet of the context in which the error silence operator was found.
> Generic/NoSilencedErrors: improve the usefulness of the error message

- src/Standards/Squiz/Sniffs/PHP/CommentedOutCodeSniff.php
- src/Standards/Squiz/Tests/PHP/CommentedOutCodeUnitTest.inc
- src/Standards/Squiz/Tests/PHP/CommentedOutCodeUnitTest.php
Updated the regex used to detect annotations from other tools, to also allow for PHPMD suppression annotations.
This gets rid of the false positive on unit test case file line 138.
Depending on end-user reports, the regex can be improved further.
After the changes I made in PR #1839, this code now added to the unit test case file was incorrectly no longer recognized as commented out code.
This PR further iterates on the previous changes and implements the following:
* Treat a line comment followed by a block comment (and visa versa) as two separate comments.
* Allow for blank lines within block comments, but not within line comment blocks.
> Squiz/CommentedOutCode: fix false positive + false negative

- src/Standards/PSR2/Sniffs/Namespaces/UseDeclarationSniff.php
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.2.inc
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.2.inc.fixed
- src/Standards/PSR2/Tests/Namespaces/UseDeclarationUnitTest.php
Currently works correctly with curly braces, but turns function and constant uses into classes.
> PSR2.Namespaces.UseDeclaration does not properly fix "use function" and "use const" statements

- src/Standards/Generic/Sniffs/Classes/DuplicateClassNameSniff.php
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.1.inc
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.2.inc
- src/Standards/Generic/Tests/Classes/DuplicateClassNameUnitTest.php
- src/Standards/PSR2/Sniffs/Methods/MethodDeclarationSniff.php
- src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.php
- src/Standards/Squiz/Sniffs/Classes/ClassFileNameSniff.php
- src/Standards/Squiz/Tests/Classes/ClassFileNameUnitTest.inc
- src/Standards/Squiz/Tests/Classes/ClassFileNameUnitTest.php
Was expecting to see traits follow the same rules.
> Include traits in ClassFileName and DuplicateClassName

- src/Standards/Generic/Sniffs/NamingConventions/ConstructorNameSniff.php
- src/Standards/Generic/Tests/NamingConventions/ConstructorNameUnitTest.inc
- src/Standards/Generic/Tests/NamingConventions/ConstructorNameUnitTest.php
Based on the bug report and test case in issue #2178, I've had a look at this sniff.
Turns out the `processTokensWithinScope()` method gets called for each whitelisted scope a `T_FUNCTION` token exists in.
In effect, this means that the first time it gets called for the `nested()` method, it is because it is within the scope of the `Nested` class, the second time the function gets called, it is for the method being in the scope of the anonymous class.
The fix I've now applied checks that the scope for which the method is called is actually the deepest scope first and bows out if it's not. This fixes the false positive.
Additionally, the `loadFunctionNamesInScope()` method would examine every token within the class and the resulting function list would therefore include the names of …
> Generic/ConstructorName: fix bug with nested anonymous classes and more

- src/Standards/Generic/Sniffs/Files/InlineHTMLSniff.php
- src/Standards/Generic/Sniffs/PHP/CharacterBeforePHPOpeningTagSniff.php
- src/Standards/Generic/Tests/Files/InlineHTMLUnitTest.6.inc
- src/Standards/Generic/Tests/Files/InlineHTMLUnitTest.7.inc
- src/Standards/Generic/Tests/Files/InlineHTMLUnitTest.php
- src/Standards/Generic/Tests/PHP/CharacterBeforePHPOpeningTagUnitTest.3.inc
Having a BOM currently triggers `Generic.Files.InlineHTML` and `Generic.PHP.CharacterBeforePHPOpeningTag`, duplicating `Generic.Files.ByteOrderMark`. This causes them to ignore it.
> Ignore BOM in Generic.Files.InlineHTML and Generic.PHP.CharacterBeforePHPOpeningTag

- .travis.yml
- phpcs.xml.dist
- src/Standards/Generic/ruleset.xml
- src/Standards/MySource/ruleset.xml
- src/Standards/PEAR/ruleset.xml
- src/Standards/PSR1/ruleset.xml
- src/Standards/PSR12/ruleset.xml
- src/Standards/PSR2/ruleset.xml
- src/Standards/Squiz/ruleset.xml
- src/Standards/Zend/ruleset.xml
Notes:
* Runs only once per build as the results are independent of the PHP version.
* Indent is set at four spaces as per commit 232f7da .
* I've elected to add this check to the smallest (fastest) build, so the build time will be spread more evenly.
* Not linting the PHPCS native ruleset as it's being run anyway, so is automatically checked.
> Build/Travis: validate rulesets against XSD and check code style consistency

- src/Standards/Generic/Sniffs/CodeAnalysis/UnusedFunctionParameterSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/UnusedFunctionParameterUnitTest.inc
- src/Standards/Generic/Tests/CodeAnalysis/UnusedFunctionParameterUnitTest.php
This PR contains one improvement to the existing code and two enhancements. It also contains two minor efficiency tweaks.
Each change is contained in its own commit.
* Don't make a function call in a loop control structure
* Bow out early if the function doesn't have any parameters
The sniff currently allowed for unused parameters in functions with empty bodies to allow for selective interface implementation.
The sniff, however, did not verify if the function was in a class which implemented an interface.
This has now been fixed.
The function signature of methods in extended classes has to mirror the method as defined in the parent class/interface.
The overloaded method may, however, not use all params.
~~This change introduces a new `$ignore_extended_classes` property which defaults to …
> Improvements for the Generic.CodeAnalysis.UnusedFunctionParameter sniff

- src/Files/File.php
As discussed in issue #2042, this adds an exception to the `File::getTokensAsString()` method for when the value of the `$start` parameter is invalid.
As for the `$length` parameter, I've chosen to just bow out early in that case.
Note: I've tested adding an exception for the `$length` parameter as well, but that would actually give issues with at least one existing PHPCS native sniff, so this is the more elegant solution.
The existing issue is with the function call on line 309 of the `AbstractPatternSniff` in combination with the `PEAR.ControlStructures.ControlSignature` sniff. I haven't looked into that issue any deeper though.
Fixes #2042
> File::getTokensAsString(): prevent endless loop

- src/Standards/Generic/Sniffs/WhiteSpace/IncrementDecrementSpacingSniff.php
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.inc
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.js
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.js.fixed
- src/Standards/Generic/Tests/WhiteSpace/IncrementDecrementSpacingUnitTest.php
New sniff to check that there are no spaces (or comments) between an incrementor/decrementor and the variable it applies to.
The sniff can examine both PHP as well as JS files for this, though I suspect there may be some false positive reports for JS at some point as `T_STRING` is quite a generic token to check for.
Includes auto-fixer.
Includes code-consistency metrics.
I've made a conscious decision to not make the number of spaces accepted between the in/decrementor and the variable configurable as it is a widely accepted convention that there should be no spaces between them.
If it would be so desired, I can add a public property to make this configurable.
Fixes #2172
> New Generic.WhiteSpace.IncrementDecrementSpacing sniff

- src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
Adding T_OPEN_CURLY_BRACKET to the list of tokens that indicate that the following token does not
belong to an arithmetic operation.
e.g. `$myString{-1}`
See https://secure.php.net/manual/en/language.types.string.php#language.types.string.substr
> Squiz.WhiteSpace.OperatorSpacing throws error for negative index when using curly braces for string access

- src/Standards/PSR2/Sniffs/Methods/MethodDeclarationSniff.php
- src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.inc.fixed
The `PSR2.Methods.MethodDeclaration` sniff would get unnecessarily confused over comments between the modifier keywords.
This minor changes fixes that.
Includes (adjusted) unit tests demonstrating the issue.
> PSR2.Methods.MethodDeclaration gets confused over comments between modifier keywords

- src/Standards/PSR2/Sniffs/Namespaces/UseDeclarationSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.inc.fixed
- src/Tokenizers/PHP.php
Added example to the test for `Squiz.WhiteSpace.FunctionSpacing` which has a problem with this (refs https://github.com/libero/php-coding-standard/pull/30).
> FUNCTION and CONST in use groups being tokenised as T_FUNCTION and T_CONST

- src/Files/File.php
- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
Method parameters were recognized as if they were class properties.
Looks like I already included an initial unit test case for this in #1715, but that case was not being tested.
The change in this PR should fix the issue, activates the existing unit test and adds some extra as well.
> File::getMemberProperties() is recognizing method params as properties

- package.xml
- src/Standards/Squiz/Tests/WhiteSpace/CastSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/CastSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/CastSpacingUnitTest.php
- src/Tokenizers/PHP.php
As reported in [my last comment](https://github.com/squizlabs/PHP_CodeSniffer/issues/1574#issuecomment-435278428) on the original issue #1574, the fix to the tokenizer does not take whitespace inside of the binary cast parentheses into account.
This PR fixes this.
It also adds a unit test which will guard against regressions to the `Squiz.WhiteSpace.CastSpacing` sniff.
As that sniff did not have a `fixed` file, while it _does_ in actual fact contain a fixer, the `.fixed` file has also been added.
> Tokenizer: fix binary cast recognition with inside parentheses whitespace

- src/Standards/Generic/Tests/Formatting/NoSpaceAfterCastUnitTest.inc
- src/Standards/Generic/Tests/Formatting/NoSpaceAfterCastUnitTest.inc.fixed
- src/Standards/Generic/Tests/Formatting/NoSpaceAfterCastUnitTest.php
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.php
- src/Standards/Squiz/Sniffs/Formatting/OperatorBracketSniff.php
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.inc
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.php
This PR adds some additional unit tests dealing with binary casts to various sniffs which look for the `$castTokens`.
It includes a very minor fix for the `Squiz.Formatting.OperatorBracket` sniff  when - no matter how unlikely - the sniff is triggered in combination with a `b"something $foo"` syntax.
Related to #1574 and https://github.com/squizlabs/PHP_CodeSniffer/commit/f36eecf11e97576f7d0860741dfbe73b7e7a7fcc
> Binary cast change / add some additional unit tests

- src/Standards/Generic/Sniffs/NamingConventions/CamelCapsFunctionNameSniff.php
- src/Standards/Generic/Tests/NamingConventions/CamelCapsFunctionNameUnitTest.inc
The list of `$methodsDoubleUnderscore` from the SoapClient extension was missing the `__getCookies()` method.
Ref: http://php.net/manual/en/class.soapclient.php
Includes ordering the list in alphabetic order.
> Generic.NamingConventions.CamelCapsFunctionName not ignoring SoapClient __getCookies() method

- package.xml
- src/Standards/Generic/Sniffs/CodeAnalysis/EmptyPHPStatementSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.inc
- src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.inc.fixed
- src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.php
New sniff to detect superfluous semi-colons and empty PHP open-close tag combinations.
Includes an auto-fixer.
Fixes #1119
> New `Generic.CodeAnalysis.EmptyPHPStatement` sniff

- src/Standards/Generic/Sniffs/Formatting/SpaceBeforeCastSniff.php
- src/Standards/Generic/Tests/Formatting/SpaceBeforeCastUnitTest.inc
- src/Standards/Generic/Tests/Formatting/SpaceBeforeCastUnitTest.inc.fixed
- src/Standards/Generic/Tests/Formatting/SpaceBeforeCastUnitTest.php
... which verifies that there is exactly one space before a type cast.
Sister-sniff to the `Generic.Formatting.SpaceAfterCast` sniff.
Depending on the coding-standard in which this sniff is included, this sniff may throw "duplicate" messages, i.e. given `$a =(bool) $b;`, a lot of coding standards will throw an error already demanding a space after the assignment operator.
All the same, type casts can be used in all sorts of code constructs, so there may well be situations in which the preceding token would not trigger an error, in which case, this sniff becomes relevant.
Notes:
* If the preceding whitespace is indentation, the sniff bows out.
* If the type cast is at the start of line, the sniff bows out.
> New `Generic.Formatting.SpaceBeforeCast` sniff

- package.xml
- src/Standards/PSR2/Sniffs/Classes/PropertyDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.php
IMO the feature request made in #2198 is unequivocally covered by PSR2 (emphasis in the quote is mine):
> Visibility MUST be declared on all **_properties_** and methods; `abstract` and `final` MUST be declared before the visibility; `static` MUST be declared after the visibility.
Ref: https://www.php-fig.org/psr/psr-2/#1-overview
With that in mind, I've adjusted the `PSR2.Classes.PropertyDeclaration` sniff to include a check for the modifier keyword order.
Notes:
* As the sniff didn't have any fixers up to now, I've added a `.fixed` file.
* The fixer tries to gracefully handle any comments found between the keywords and the property variable.
* The sniff now defers to the `File::getMemberProperties()` method for the information on whether scope (and static) is …
> PSR2/PropertyDeclaration: add modifier order error + fixing

- src/Standards/Generic/Sniffs/NamingConventions/CamelCapsFunctionNameSniff.php
- src/Standards/Generic/Tests/NamingConventions/CamelCapsFunctionNameUnitTest.inc
- src/Standards/Generic/Tests/NamingConventions/CamelCapsFunctionNameUnitTest.php
- src/Standards/PEAR/Sniffs/NamingConventions/ValidFunctionNameSniff.php
- src/Standards/PEAR/Tests/NamingConventions/ValidFunctionNameUnitTest.inc
- src/Standards/PEAR/Tests/NamingConventions/ValidFunctionNameUnitTest.php
- src/Standards/PSR1/Sniffs/Methods/CamelCapsMethodNameSniff.php
- src/Standards/PSR1/Tests/Methods/CamelCapsMethodNameUnitTest.inc
- src/Standards/PSR1/Tests/Methods/CamelCapsMethodNameUnitTest.php
- src/Standards/PSR2/Sniffs/Methods/MethodDeclarationSniff.php
- src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Methods/MethodDeclarationUnitTest.php
- src/Standards/Squiz/Sniffs/Scope/MethodScopeSniff.php
- src/Standards/Squiz/Sniffs/Scope/StaticThisUsageSniff.php
- src/Standards/Squiz/Tests/Scope/MethodScopeUnitTest.inc
- src/Standards/Squiz/Tests/Scope/MethodScopeUnitTest.php
- src/Standards/Squiz/Tests/Scope/StaticThisUsageUnitTest.inc
- src/Standards/Squiz/Tests/Scope/StaticThisUsageUnitTest.php
These fixes are all loosely related to and inspired by the test case provided in #2178 and fixed via #2182.
There were a number of other sniffs using the `AbstractScopeSniff` as a basis which would throw the same error twice for functions nested in anonymous classes.
I've reviewed most of these now and have fixed them in separate commits.
All fixes include unit tests.
The reasoning and solution used is the same as previously applied in #2182 for the `Generic.NamingConventions.ConstructorName` sniff.
> Turns out the `processTokensWithinScope()` method gets called for each whitelisted scope a `T_FUNCTION` token exists in.
>
> In effect, this means that the first time it gets called for the `nested_function()` method, it is because it is within the scope of the `Nested` class, the second …
> Bugfixes for 6 sniffs / `processTokensWithinScope()` vs nested classes

- src/Standards/PSR2/Docs/Classes/PropertyDeclarationStandard.xml
In PR #2218, I updated the `PSR2.Classes.PropertyDeclaration` sniff and added a new check, but I forgot to update the associated documentation.
Sorry about that. This should fix it.
> PSR2/PropertyDeclaration: update docs

- src/Standards/PEAR/Sniffs/Functions/FunctionCallSignatureSniff.php
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.inc
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.php
When `$allowMultipleArguments` is set to false and the sniff would encounter a trailing PHPCS annotation in a function call, it would incorrectly throw a _"Only one argument is allowed per line in a multi-line function call"_ error.
The sniff did handle normal trailing comments correctly, so only needed a minimal adjustment to allow for the PHPCS annotations.
Additional notes:
* This commit also adds a few unit test cases using trailing comma's in function calls - as allowed per PHP 7.3 - to confirm that the sniff handles these correctly and safeguard this for the future.
* Also includes a minor unit test case documentation fix.
> PEAR.Functions.FunctionCallSignature incorrect error when encountering trailing PHPCS annotation

- src/Standards/Squiz/Sniffs/WhiteSpace/ObjectOperatorSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.php
Efficiency fix. Prevents the fixer having to be triggered multiple times when, for instance, whitespace + newline + whitespace or several new lines are found between the object operator and the token before/after.
Existing unit tests already cover this change.
The effect of the change can be seen by running `phpcbf -v --standard=Squiz ./src/Standards/Squiz.Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.inc --sniffs=Squiz.WhiteSpaceObjectOperatorSpacing` first on `master` (3 passes needed), then on this branch (2 passes needed).
Includes minor improvement to an existing unit test checking the handling of whitespace in combination with comments.
> Squiz/ObjectOperatorSpacing: fix whitespace in one loop

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
Minor improvement by moving $isSpecialMethod to the next lines. This way in case you return to the if statement before you save a not needed comparison.
> [Minor] Move isSpecialMethod

- package.xml
- src/Standards/Squiz/Sniffs/Functions/LowercaseFunctionKeywordsSniff.php
- src/Standards/Squiz/Tests/Functions/LowercaseFunctionKeywordsUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Functions/LowercaseFunctionKeywordsUnitTest.php
* Also check closures and the `abstract` and `final` method prefixes.
* Make the error fixable.
* Minor code duplication removal.
Includes improved unit tests + added a `fixed` file.
> Squiz/LowercaseFunctionKeywords: various improvements

- src/Standards/Squiz/Sniffs/Classes/SelfMemberReferenceSniff.php
- src/Standards/Squiz/Tests/Classes/SelfMemberReferenceUnitTest.inc
- src/Standards/Squiz/Tests/Classes/SelfMemberReferenceUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Classes/SelfMemberReferenceUnitTest.php
This PR takes care of the issues identified in https://github.com/squizlabs/PHP_CodeSniffer/pull/2185#issuecomment-430027868 as well as some other bugs.
**Note**: As the sniff is now more directly targeted at the use of `self` in the right places, I would strongly recommend for the whitespace related errors - `SpaceBefore` and `SpaceAfter` - to be removed from this sniff.
The `Squiz.WhiteSpace.ObjectOperatorSpacing` sniff already handles this anyway and handles this better.
Fixes #2232
... when the double colon is preceded by whitespace/comments.
Prevent the sniff from not throwing the whitespace errors when the `NotUsed` error is also found.
Loosely related to #2150
... to prevent the name comparison breaking.
The PR includes unit tests for all fixes.
> Squiz/SelfMemberReference: various bug fixes

- package.xml
- src/Standards/Squiz/Sniffs/Objects/ObjectMemberCommaSniff.php
- src/Standards/Squiz/Tests/Objects/ObjectMemberCommaUnitTest.js.fixed
- src/Standards/Squiz/Tests/Objects/ObjectMemberCommaUnitTest.php
Notes:
* While this constitutes a BC-break, the error code used by this sniff was incorrect as the error is thrown when a comma is _found_, not when it's _missing_.
* Added an additional unit test documenting that the sniff correctly skips over PHPCS annotations and comments.
* Removed some redundant code from the unit test file.
> Squiz.Objects.ObjectMemberComma: add fixed file and minor fix

- src/Tokenizers/CSS.php
Came across this while working on some of the Squiz CSS sniffs.
This code sample:
```css
.HelpWidgetType-new-bug-title {}
```
Was tokenized as:
```
0 :: L001 :: C1 :: T_OPEN_TAG :: (0) ::
1 :: L001 :: C1 :: T_STRING_CONCAT :: (1) :: .
2 :: L001 :: C2 :: T_STRING :: (14) :: HelpWidgetType
3 :: L001 :: C16 :: T_MINUS :: (1) :: -
4 :: L001 :: C17 :: T_NEW :: (3) :: new
5 :: L001 :: C20 :: T_STRING :: (10) :: -bug-title
6 :: L001 :: C30 :: T_WHITESPACE :: (1) ::
7 :: L001 :: C31 :: T_OPEN_CURLY_BRACKET :: (1) :: {
8 :: L001 :: C32 :: T_CLOSE_CURLY_BRACKET :: (1) :: }
```
...while I would expect the class identifier to be tokenized as one T_STRING `HelpWidgetType-new-bug-title` instead.
This commit fixes that and the code sample is now tokenized as:
```
0 :: L001 :: C1 :: T_OPEN_TAG :: (0) :: …
```
> CSS tokenizer does not tokenize class names correctly when they contain the string NEW

- src/Files/File.php
Minified files are not processed by the tokenizer and when such files are encountered PHPCS throws an `Internal.Tokenizer.Exception` warning.
In the progress report these files show up with a `W` because of this warning.
However, as the file isn't really processed at all, indicating these files as "skipped" with an `S` in the progress report seems more appropriate.
Also, when there is a tokenizer error, the rest of the processing in the `File::process()` method can be skipped.
This commit makes that change.
The existing warning is left in place, but the progress report will now report these files with an `S`.
To test this change:
* Grab any project with minified CSS and/or JS files.
* While on `master`, run `phpcs -p . --standard=PSR2 --report=summary,source` on the project and take note …
> Progress reporting: Report files with tokenizer errors as skipped

- src/Standards/PSR1/ruleset.xml
- src/Standards/PSR2/ruleset.xml
Use complete sniff name instead of partial file name reference to avoid confusion what with there being sniffs with the same name in different standards.
> PSR1/PSR2 rulesets: improve inline documentation

- tests/Standards/AbstractSniffUnitTest.php
- tests/Standards/AllSniffs.php
- tests/bootstrap.php
This commit adds an additional line below a unit test run, listing how many sniff test case files were examined. This information can be used as input to check and debug unit test runs.
> Unit Tests: report on number of sniff test case files tested

- src/Standards/Squiz/Sniffs/Operators/ComparisonOperatorUsageSniff.php
- src/Standards/Squiz/Tests/Operators/ComparisonOperatorUsageUnitTest.inc
This bug caused false positives from Sniff.Operators.ComparisonOperatorUsage for inline if statements that were completely surrounded by a pair of parentheses, e.g. from a function call.
> Squiz.Operators.ComparisonOperatorUsage false positive when inline IF contained in parentheses

- src/Standards/Generic/Docs/Formatting/SpaceAfterNotStandard.xml
- src/Standards/Generic/Sniffs/Formatting/SpaceAfterNotSniff.php
- src/Standards/Generic/Tests/Formatting/SpaceAfterNotUnitTest.inc
- src/Standards/Generic/Tests/Formatting/SpaceAfterNotUnitTest.inc.fixed
- src/Standards/Generic/Tests/Formatting/SpaceAfterNotUnitTest.php
This PR makes the `Generic.Formatting.SpaceAfterNot` sniff configurable as discussed in PR https://github.com/squizlabs/PHP_CodeSniffer/pull/2057#issuecomment-396093803.
Notes:
* Adds a public `spacing` property. Defaults to `1` to maintain BC.
* Adds a public `ignoreNewLines` property. Defaults to `false` to maintain BC.
* Adds a new non-fixable `CommentFound` error for when non-whitespace tokens are found between the NOT operator and the next non-empty token.
* Adjusts the error message for the `Incorrect` error to allow for the flexibility now needed, what with the configurable `spacing` property.
Note: the error **code** has not been changed to prevent a BC-break.
* Makes the fixer more efficient compared to before.
Previously, if a whitespace + new line + whitespace would be found …
> Generic/SpaceAfterNot: make the sniff configurable

- src/Standards/Generic/Sniffs/Formatting/NoSpaceAfterCastSniff.php
- src/Standards/Generic/Sniffs/Formatting/SpaceAfterCastSniff.php
- src/Standards/Generic/Tests/Formatting/SpaceAfterCastUnitTest.inc
- src/Standards/Generic/Tests/Formatting/SpaceAfterCastUnitTest.inc.fixed
- src/Standards/Generic/Tests/Formatting/SpaceAfterCastUnitTest.php
This PR makes the `Generic.Formatting.SpaceAfterCast` sniff configurable as discussed in PR https://github.com/squizlabs/PHP_CodeSniffer/pull/2057#issuecomment-396103995 and deprecates the `Generic.Formatting.NoSpaceAfterCast` sniff.
Notes:
* Adds a public `spacing` property. Defaults to `1` to maintain BC.
* Adds a public `ignoreNewLines` property. Defaults to `false` to maintain BC.
* Adds a new non-fixable `CommentFound` error for when non-whitespace tokens are found between the type cast and the next non-empty token.
* Adds a new fixable `TooLittleSpace` error code for when `$spacing` is set to more than `1` and there is whitespace, but not enough.
* Adjusts the error message for the `NoSpace` and `TooMuchSpace` errors to allow for the flexibility now needed, what with the …
> Generic/SpaceAfterCast: make the sniff configurable & deprecates NoSpaceAfterCast

- tests/bootstrap.php
PR #2289 added a count of the number of test case files to the test output, however did not take into account that when only the unit tests for the utility functions would be run, i.e. via for instance `phpunit --filter FindExtendedClassNameTest`, the `$GLOBALS['PHP_CODESNIFFER_SNIFF_CASE_FILES']` variable would not have any arrays in it.
This adds some minor defensive coding which gets rid of the PHP error message which would be generated in that situation.
> Test bootstrap/printPHPCodeSnifferTestOutput(): bug fix

- autoload.php
- src/Config.php
- src/Reporter.php
- src/Ruleset.php
- src/Runner.php
- src/Sniffs/AbstractPatternSniff.php
- src/Standards/MySource/Sniffs/Channels/IncludeSystemSniff.php
- src/Tokenizers/CSS.php
- src/Tokenizers/JS.php
- src/Tokenizers/Tokenizer.php
* Use FQN for exceptions in `@throws` tags and add missing `@throws` tags
* Use FQN in `@param` tags and add missing type declaration
* One minor documentation correction
> Girlscouting: various minor documentation fixes

- src/Sniffs/AbstractPatternSniff.php
- src/Standards/Generic/Sniffs/Functions/CallTimePassByReferenceSniff.php
- src/Standards/PSR12/Sniffs/Operators/OperatorSpacingSniff.php
- src/Standards/PSR2/Sniffs/Classes/PropertyDeclarationSniff.php
- src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
Array union `+` is much faster than `array_merge()`, though the behaviour is different.
The differences are:
-- | Array union | Array merge
-- | -- | --
Numeric keys | Will keep the keys which already exist | Will renumber & add keys for all values
String keys | Will keep the keys which already exist | Will keep the keys which already exist
Values | Will *not overwrite* existing value | Will *overwrite* existing value
As the arrays which are defined in the `Tokens` class have the same keys as well as values, using array union on those token arrays will be:
* more efficient than using a function call to `array_merge()`;
* will auto-deduplicate the arrays, so no need for a call to `array_unique()`;
* and the result will be the same.
Similarly, using straight assignments to an array is also …
> Efficiency fixes

- package.xml
See #2148
This should probably also be adjusted in https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.4.0
> Changelog 3.4.0: fix incorrect entry

- package.xml
- src/Standards/Squiz/Sniffs/CSS/SemicolonSpacingSniff.php
- src/Standards/Squiz/Tests/CSS/SemicolonSpacingUnitTest.css.fixed
- src/Standards/Squiz/Tests/CSS/SemicolonSpacingUnitTest.php
While I was at it, I've reviewed the sniff and applied any improvements I could think of:
* The sniff will now bow out during live coding.
* The sniff did not take multiple CSS declarations on a single line into account.
* The sniff did not take multi-line CSS declarations into account.
The error messages will now be thrown on the last line of the CSS declaration, not on the line containing the `T_STYLE` token.
* The sniff did not take multi-line whitespace between the end of a declaration and the semi-colon into account.
- The error message has been adjusted to provide better information in that case.
- The fixer has been adjusted to now fix this in one go.
* The sniff did not take comments or …
> Squiz.CSS.SemicolonSpacing: add fixed file and various improvements

- package.xml
- src/Standards/Squiz/Sniffs/CSS/ClassDefinitionClosingBraceSpaceSniff.php
- src/Standards/Squiz/Tests/CSS/ClassDefinitionClosingBraceSpaceUnitTest.css.fixed
- src/Standards/Squiz/Tests/CSS/ClassDefinitionClosingBraceSpaceUnitTest.php
[Fixer conflict series PR] + [Missing fixed files series PR]
While I was at it, I've reviewed the sniff and applied any improvements I could think of:
* The sniff did not handle multiple statements on the same line correctly.
* The fixer would inadvertently remove line indentation. Indentation is not the concern of this sniff, so should be left alone.
* The sniff did not take trailing comments or PHPCS annotations into account, which would cause a fixer conflict with itself.
- The fixer has been adjusted to handle trailing comments correctly.
Includes additional unit tests for all fixes.
> Squiz.CSS.ClassDefinitionClosingBrace: add fixed file and various improvements

- package.xml
- src/Standards/Squiz/Tests/CSS/ColourDefinitionUnitTest.css.fixed
Includes adding some additional unit tests documenting and making sure only HEX colours are examined.
> Squiz.CSS.ColourDefinition: add fixed file

- package.xml
- src/Standards/Squiz/Tests/CSS/DisallowMultipleStyleDefinitionsUnitTest.css
- src/Standards/Squiz/Tests/CSS/DisallowMultipleStyleDefinitionsUnitTest.css.fixed
- src/Standards/Squiz/Tests/CSS/DisallowMultipleStyleDefinitionsUnitTest.php
Includes tests documenting how the sniff handles inline comments and annotations.
> Squiz.CSS.DisallowMultipleStyleDefinitions: add fixed file

- package.xml
- src/Standards/Squiz/Tests/WhiteSpace/LogicalOperatorSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/LogicalOperatorSpacingUnitTest.js.fixed
The sniff contains fixers, but didn't have `fixed` files.
> Squiz/LogicalOperatorSpacing: add fixed file

- package.xml
- src/Standards/Squiz/Tests/ControlStructures/ElseIfDeclarationUnitTest.inc.fixed
> Squiz/ElseIfDeclaration: add fixed file

- package.xml
- src/Standards/Squiz/Sniffs/ControlStructures/LowercaseDeclarationSniff.php
- src/Standards/Squiz/Tests/ControlStructures/LowercaseDeclarationUnitTest.inc
- src/Standards/Squiz/Tests/ControlStructures/LowercaseDeclarationUnitTest.inc.fixed
The `Squiz.ControlStructures.LowercaseDeclaration` sniff contains fixers, but didn't have a `fixed` file.
Includes minor efficiency fix (code duplication).
> Squiz/LowercaseDeclaration: add fixed file and minor efficiency fix

- package.xml
- src/Standards/PSR2/Tests/Files/ClosingTagUnitTest.5.inc.fixed
- src/Standards/PSR2/Tests/Files/ClosingTagUnitTest.6.inc
- src/Standards/PSR2/Tests/Files/ClosingTagUnitTest.6.inc.fixed
- src/Standards/PSR2/Tests/Files/ClosingTagUnitTest.php
The sniff contains fixers, but the `ClosingTagUnitTest.5.inc` file - which does contain fixable errors - didn't have a `fixed` file.
Includes adding one new unit test to cover "closing tag as last token/no new line at end of file".
> PSR2/ClosingTag: add missing fixed file + additional test

- package.xml
- src/Standards/Squiz/Sniffs/Classes/LowercaseClassKeywordsSniff.php
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.inc
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Classes/LowercaseClassKeywordsUnitTest.php
The sniff contain a fixer, but didn't have a `fixed` file.
While I was at it, I've reviewed the sniff and applied any improvements I could think of:
* The sniff will now also examine the `class` keyword for anonymous classes.
* Minor code de-duplication fix.
Includes additional unit tests for all fixes.
> Squiz/LowercaseClassKeywords: add fixed file and minor improvements

- package.xml
- src/Standards/Generic/Sniffs/Files/LineEndingsSniff.php
- src/Standards/Generic/Tests/Files/LineEndingsUnitTest.css.fixed
- src/Standards/Generic/Tests/Files/LineEndingsUnitTest.js.fixed
The sniff contain a fixer, but didn't have a `fixed` file for the CSS and JS test case files.
While creating the `fixed` files, I noticed that the `T_CLOSE_TAG`, which for CSS and JS files is empty, would also be replaced with a new line, resulting in an extra, superfluous new line at the end of a file.
This has now been fixed.
> Generic/LineEndings: add fixed files + minor bug fix

- package.xml
In the WordPressCS repo we received a bug report from someone using PHPCS 3.4.0 but missing the `Generic.WhiteSpace.LanguageConstructSpacing` sniff.
Ref: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1614
Turned out that that sniff is missing from the `package.xml` file which is why it's not available when someone is using a PEAR install of PHPCS.
I've now done a comprehensive check of all relevant files in the repo versus the files listed in the `<contents>` tag of the `package.xml` file and found some more discrepancies with this commit as a result.
As this basically means that the PEAR install is currently "broken" with regards to the `Code` report (PHPCS 3.0), the `Generic.Formatting.SpaceBeforeCast` sniff (PHPCS 3.4.0) as well as the …
> Hotfix for PEAR install

- .travis.yml
- scripts/FileList.php
- scripts/ValidatePEARPackageXML.php
- scripts/validate-pear-package.php
This PR adds a custom script which will validate the `<contents>` and `<phprelease>`  tags in the PEAR-targeted `package.xml` file.
The script executes the following checks to verify the validity of the tags:
* Check that every file mentioned in the `<contents>` tag exists.
* Check that the value of the `role` attribute for a `<file>` tag is valid.
* Check that the value of the `baseinstalldir` attribute for a `<file>` tag is valid.
* Checks that all files in the `src` and `tests` directories are listed in the `<contents>` tag.
* Check that every file mentioned in the `<phprelease>` tags exists.
* Check that the value of the `as` attribute for a `<install>` tag is valid.
* Checks that all files in the `tests` directory are listed in the `<phprelease>` tags.
More/improved checks can be …
> Travis: add additional validation for the PEAR package.xml file

- src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php
Based on an analysis of some runs with [BlackFire](https://blackfire.io/), this small tweak will lower the memory usage of any run which includes the `Generic.WhiteSpace.ScopeIndent` - and by extension, the `PEAR.WhiteSpace.ScopeIndent` - sniff significantly.
A comparison between a run on `master` and a run on this branch can be found here: https://blackfire.io/profiles/compare/7adc96c7-09a4-4ec8-8821-bbf9d5906b2f/graph
**Note**: this comparison is only available for 24 hours.
The benchmark was created by running PHPCS over itself with the native ruleset and this command:
`phpcs -p --report-source --no-cache`.
For when the comparison isn't available anymore, this is the significant part:
> Generic/ScopeIndent: lower memory usage

- src/Standards/Generic/Sniffs/Classes/OpeningBraceSameLineSniff.php
- src/Standards/Generic/Sniffs/Functions/FunctionCallArgumentSpacingSniff.php
- src/Standards/PEAR/Sniffs/ControlStructures/MultiLineConditionSniff.php
- src/Standards/PEAR/Sniffs/Formatting/MultiLineAssignmentSniff.php
- src/Standards/PEAR/Sniffs/Functions/FunctionCallSignatureSniff.php
- src/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php
- src/Standards/PEAR/Sniffs/WhiteSpace/ObjectOperatorIndentSniff.php
- src/Standards/PSR2/Sniffs/Classes/ClassDeclarationSniff.php
- src/Standards/PSR2/Sniffs/ControlStructures/ControlStructureSpacingSniff.php
- src/Standards/Squiz/Sniffs/Classes/SelfMemberReferenceSniff.php
- src/Standards/Squiz/Sniffs/Commenting/DocCommentAlignmentSniff.php
- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/Squiz/Sniffs/ControlStructures/ControlSignatureSniff.php
- src/Standards/Squiz/Sniffs/ControlStructures/ForEachLoopDeclarationSniff.php
- src/Standards/Squiz/Sniffs/Functions/FunctionDeclarationArgumentSpacingSniff.php
- src/Standards/Squiz/Sniffs/PHP/EmbeddedPhpSniff.php
- src/Standards/Squiz/Sniffs/WhiteSpace/LogicalOperatorSpacingSniff.php
The `$tokens` array already contains the `length` of each and every token, so there is no need to (re-)calculate this in individual sniffs, unless we're examining `T_COMMENT` or `T_INLINE_HTML` tokens.
Using the `length` from the tokenizer array should also be more accurate when tabs have been replaced with spaces or when dealing with Unicode texts.
Fixes #2285
> Remove unnecessary strlen() function calls

- src/Standards/Squiz/Sniffs/CSS/ClassDefinitionNameSpacingSniff.php
- src/Standards/Squiz/Tests/CSS/ClassDefinitionNameSpacingUnitTest.css
Improves the resilience of the sniff against syntax/parse errors and during live coding.
> Squiz.CSS.ClassDefinitionNameSpacing: fix "Undefined index: bracket_closer" error

- src/Standards/Squiz/Sniffs/CSS/DuplicateStyleDefinitionSniff.php
- src/Standards/Squiz/Tests/CSS/DuplicateStyleDefinitionUnitTest.css
Improves the resilience of the sniff against syntax/parse errors and during live coding.
> Squiz.CSS.DuplicateStyleDefinition: fix "Undefined index: bracket_closer" error

- src/Standards/Squiz/Sniffs/CSS/MissingColonSniff.php
- src/Standards/Squiz/Tests/CSS/MissingColonUnitTest.css
Improves the resilience of the sniff against syntax/parse errors and during live coding.
> Squiz.CSS.MissingColon: fix "Undefined index: bracket_closer" error

- src/Standards/MySource/Sniffs/Objects/CreateWidgetTypeCallbackSniff.php
- src/Standards/Squiz/Sniffs/WhiteSpace/SemicolonSpacingSniff.php
- src/Tokenizers/JS.php
Related to #2273 - I've done a quick search of rest of the code base and adjusted any usage of the `end()` / `key()` functions in combination with the `$tokens` array.
All relevant instances of this in the existing code base have now been fixed for the memory leakage.
> Few more minor memory management tweaks

- package.xml
- src/Standards/Generic/Tests/PHP/DeprecatedFunctionsUnitTest.inc
- src/Standards/Generic/Tests/PHP/DeprecatedFunctionsUnitTest.php
[Sniff completeness series PR]
Note: PHP internally doesn't always correctly register functions as deprecated, so this sniff will only work when it has (as the information is otherwise not available to the Reflection extension).
Some trial and error showed that the two functions now in the tests are correctly registered, but numerous other functions I tried to add to the test case file failed as PHP didn't provide the expected information.
> Generic/DeprecatedFunctions: add missing unit tests

- package.xml
- src/Standards/Generic/Tests/VersionControl/SubversionPropertiesUnitTest.inc
- src/Standards/Generic/Tests/VersionControl/SubversionPropertiesUnitTest.php
[Sniff completeness series PR]
This sniff cannot be tested as it needs to read out information from files in a `.svn` directory which cannot easily be simulated.
The files now added just document why there are no unit tests.
> Generic/SubversionProperties: add perfunctory unit test files

- src/Standards/Squiz/Sniffs/ControlStructures/ControlSignatureSniff.php
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc.fixed
[Fixer conflict series PR]
The check to prevent the sniff from kicking in during live coding/at the end of a file wasn't stable enough and allowed the sniff to kick in anyway if there was a new line or comment after the control structure keyword.
This, in turn, would cause a fixer conflict with `EndFileNewLine` sniffs and - depending on the control structure - other sniffs.
The fixer conflict can be reproduced using this code sample:
```php
<?php
foreach
```
and this command:
`phpcbf ./testfile.php --standard=Squiz`
And while PSR2 does not generate a fixer conflict for this code sample, incorrect fixes would still be made resulting in (more) parse errors.
Using this code sample:
```php
<?php
for
```
Using the following command:
`phpcbf ./testfile.php --standard=PSR2`
This would be fixed …
> Squiz/ControlSignature: fix fixer conflict

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentThrowTagSniff.php
This simplifies the check on whether or not the sniff should run.
> Squiz/FunctionCommentThrowTag: remove some redundant code

- src/Standards/PSR12/Sniffs/Keywords/ShortFormTypeKeywordsSniff.php
- src/Standards/PSR12/Tests/Keywords/ShortFormTypeKeywordsUnitTest.inc
- src/Standards/PSR12/Tests/Keywords/ShortFormTypeKeywordsUnitTest.inc.fixed
- src/Standards/PSR12/Tests/Keywords/ShortFormTypeKeywordsUnitTest.php
The PSR 12 standard (currently) says nothing about whether or not spaces within type casts are allowed.
As it was, the `PSR12.Keywords.ShortFormTypeKeywords` sniff would throw a false positive for a short form type cast like `( bool )` and "fix" it by removing the spaces, which is not the concern of this sniff.
If at some point the PSR12 standard would take a stand about spaces within type casts, the `Squiz.WhiteSpace.CastSpacing` sniff could be added to check & fix these issues.
In the mean time, the `ShortFormTypeKeywords` sniff should be space-agnostic.
This PR takes care of that.
It also makes the error message slightly more descriptive by being explicit about the type cast found in the error message.
> PSR12/ShortFormTypeKeywords: bug fix / false positive

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentThrowTagSniff.php
- src/Standards/Squiz/Tests/Commenting/FunctionCommentThrowTagUnitTest.inc
When it isn't clear what type of Exception a `throw` will generate, but there are more than one `throw`s in a function, the "unknown" exceptions wouldn't be taken into account when determining whether the correct number of exceptions were being thrown.
(In case anyone is wondering: the `Prefix_Invalid_Argument_Exception::invalid_string_parameter()` method returns an instance of `self` in the code where I encountered this issue.)
The code did not take into account that Fully Qualified names could be used in the `@throws` tag while a relative Exception name may be used in the `throw` statement.
Includes unit tests (probably a few too many, but I wanted to be sure that I understood how the sniff was dealing with this).
> Squiz/FunctionCommentThrowTag: two bug fixes

- package.xml
- src/Standards/Generic/Sniffs/Formatting/DisallowMultipleStatementsSniff.php
- src/Standards/Generic/Tests/Formatting/DisallowMultipleStatementsUnitTest.inc.fixed
- src/Standards/Generic/Tests/Formatting/DisallowMultipleStatementsUnitTest.php
The sniff contain a fixer, but didn't have a `fixed` file.
The fixer did not yet take the new PHPCS annotations into account. The only one which is problematic if it's moved, is the `T_PHPCS_IGNORE` token, so if that token would be encountered, the error will still be thrown, but will no longer be fixable.
Includes additional unit test covering this.
> Generic/DisallowMultipleStatements: add fixed file + minor bug fix

- src/Sniffs/Sniff.php
Because custom tokens are strings.
> Fixed docblock

- src/Standards/Squiz/Sniffs/WhiteSpace/SuperfluousWhitespaceSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.php
Similar to the issues which were fixed in #2182 and #2192, the `Squiz.WhiteSpace.SuperfluousWhitespace` sniff also did not yet take nested anonymous classes into account.
Spacing around properties and functions within nested anonymous classes have their own rules and the "multiple empty lines in a row" error should not be triggered for these.
This fixes a fixer conflict between the `FunctionSpacing` sniff and this one.
> Squiz/SuperfluousWhitespace: fix fixer conflict with nested anonymous functions

- package.xml
- src/Standards/Squiz/Sniffs/ControlStructures/ForLoopDeclarationSniff.php
- src/Standards/Squiz/Tests/ControlStructures/ForLoopDeclarationUnitTest.inc
- src/Standards/Squiz/Tests/ControlStructures/ForLoopDeclarationUnitTest.inc.fixed
- src/Standards/Squiz/Tests/ControlStructures/ForLoopDeclarationUnitTest.js
- src/Standards/Squiz/Tests/ControlStructures/ForLoopDeclarationUnitTest.js.fixed
- src/Standards/Squiz/Tests/ControlStructures/ForLoopDeclarationUnitTest.php
[Fixer conflict series PR] + [Missing fixed files series PR]
**Note**: This PR will be easiest to review by looking at the individual commits.
The sniff contains fixers, but didn't have `fixed` files.
Tests covering:
* Missing first expression.
* First/Last expression missing in combination with non-zero `requiredSpacesAfterOpen`/`requiredSpacesBeforeClose`.
* Expressions interlaces with comments.
* Multi-line expressions.
* Multi-line whitespace which needs to be removed.
* Expressions including code which itself contains a semi-colon.
* The parse error warning.
Report errors for multi-line `for` control structures on the line they refer to, i.e. opening brace, close brace, semicolon line, instead of the line the `for` keyword is on.
This improves the usability of the error messages for …
> Squiz/ForLoopDeclaration: add fixed file + fix fixer conflict + fix other bugs

- package.xml
- src/Standards/Generic/Tests/Debug/CSSLintUnitTest.css
- src/Standards/Generic/Tests/Debug/CSSLintUnitTest.php
[Sniff completeness series PR]
Note: it may be worth it to check if `csslint` is available on Travis by default or do a `npm i csslint` in the Travis `before_script` section to install it, so the sniff will actually be tested properly.
> Generic/CSSLint: add missing unit tests

- package.xml
- src/Standards/Generic/Tests/Debug/ClosureLinterUnitTest.js
- src/Standards/Generic/Tests/Debug/ClosureLinterUnitTest.php
[Sniff completeness series PR]
It may be worth it to add `sudo apt-get install python-pip && sudo pip install https://github.com/google/closure-linter/zipball/master` in the Travis `before_script` section to install it, so the sniff will actually be tested properly, though trying to get this running locally was quite a struggle as the tool is deprecated and has issues when run on Python 3.
> Generic/ClosureLinter: add missing unit tests

- package.xml
- src/Standards/Squiz/Sniffs/CSS/ForbiddenStylesSniff.php
- src/Standards/Squiz/Tests/CSS/ForbiddenStylesUnitTest.css.fixed
> Squiz.CSS.ForbiddenStyles: add missing fixed file

- package.xml
- src/Standards/Squiz/Sniffs/CSS/ShorthandSizeSniff.php
- src/Standards/Squiz/Tests/CSS/ShorthandSizeUnitTest.css
- src/Standards/Squiz/Tests/CSS/ShorthandSizeUnitTest.css.fixed
- src/Standards/Squiz/Tests/CSS/ShorthandSizeUnitTest.php
* Fix a unit test which is invalid CSS.
Valid values for `page-break-inside` are `auto|avoid|initial|inherit`, not a size indication, so changed the style to one which does take size indicators (`tab-size`).
* Add unit test with multi-line style values which should use shorthand.
* Minor improvement to the inline documentation of the tests.
* Add tests documenting how the sniff handles style values interlaced with comments and/or PHPCS annotations. Current behaviour is to ignore these completely.
* Add a parse error test.
* Bow out early for parse errors/live coding.
* Don't remember submatches of the regex which don't need to be used anyhow.
* Minor improvements in whitespace handling.
> Squiz.CSS.ShorthandSize: add missing fixed file and minor tweaks

- src/Filters/GitModified.php
Deleted files cause realpath($path) to return false. When this value
enters the while loop, it will run indefinitely as the condition will
never be matched.
> The gitmodified filter will infinitely loop when encountering deleted file paths

- src/Files/File.php
Because custom tokens are strings.
> Fixed docblocks

- src/Standards/Generic/Sniffs/Functions/FunctionCallArgumentSpacingSniff.php
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.php
The `Tokens::$functionNameTokens` array includes a number of tokens which will never trigger errors from this sniff as they only expect one parameter. Think: `empty()`, `exit()`.
However, as the tokens are registered for the sniff, the sniff will be triggered each time those tokens are encountered.
I have changed the `register()` method to only register the tokens which will/could actually trigger errors, making the sniff more efficient.
Added an extra unit test to confirm that the sniff handles PHP 7.3 trailing commas in function calls correctly.
Spacing around equal operators within anonymous classes should be ignored by this sniff, but wasn't.
This fixes false positives being thrown by this sniff and most likely also fixes a fixer conflict, though I haven't gone looking for specifics, …
> Generic/FunctionCallArgumentSpacing: minor tweaks + bug fix for anonymous classes

- src/Runner.php
This adjusts the `Runner::checkRequirements()` method to check all PHP extension requirements as listed in the `composer.json` `require` section.
This ensures that requirements are also properly checked for PHAR, PEAR and git-clone based installs.
Fixes #2369
N.B.: While I've tested the message display, I have not been able to test the actual PR as I don't have a PHP compilation available which is missing any of the required three extensions....
@jrchamp Could you test the PR as you originally reported the issue ?
> Runner::checkRequirements(): check all required extensions

- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc.fixed
``each()`` is deprecated from PHP 7.2 http://php.net/manual/en/function.each.php
My IDE was complaining about this in an example test file.
Even though the test examples are not required to be strictly-valid PHP (they are more for testing format parsing), it seems reasonable to remove this sort of deprecated stuff from examples.
> Remove deprecated each() function from test examples

- phpcs.xml.dist
- tests/Core/File/FindEndOfStatementTest.inc
- tests/Core/File/FindExtendedClassNameTest.inc
- tests/Core/File/FindImplementedInterfaceNamesTest.inc
- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodPropertiesTest.inc
- tests/Core/File/IsReferenceTest.inc
.. and make the pattern for ignoring the Sniff test case files slightly more specific.
Includes removing existing `phpcs:ignoreFile` comments from utility test case files.
> Native PHPCS ruleset: ignore Utility method test case files

- scripts/ValidatePEAR/ValidatePEARPackageXML.php
* Add a new line between the different checks.
* Allow for utility method tests using a JS or CSS test case file.
* Allow for utility method tests using a XML ruleset test file. (see PR #2392 / https://github.com/wvega/PHP_CodeSniffer/pull/1)
> ValidatePEARPackageXML: minor tweaks

- .travis.yml
Nightly has become PHP 8.0 since PHP 7.4 has been branched, so to continue to also test against PHP 7.4, it needs to be added separately.
As PHPStan can't currently be run (yet) on PHP 8, the environment variable for it has also been moved to PHP 7.4.
Refs:
* https://twitter.com/nikita_ppv/status/1089839541828112384
* https://twitter.com/nikita_ppv/status/1094897743594770433
PHPUnit 8 adds `void` return type declarations to the PHPUnit methods used by PHPCS, making it neigh impossible to make the unit test suite cross-version compatible for the PHP versions supported by PHPCS.
Officially, PHPUnit 7 is compatible with PHP 7.1, 7.2 and 7.3. However for the functionality used by the PHPCS test suite, it looks to be compatible with PHP 7.4 as well (for now).
Ref: …
> Travis: test builds against PHP 7.4 & improve PHPUnit 8 fix

- src/Files/File.php
`unset()` will silently fail if the array key/variable to unset doesn't exist, so there is no need to wrap this in an `isset()`.
> File::findStartOfStatement/findEndOfStatement(): minor tweak

- README.md
- package.xml
Some of these were typos in sniff names - so fixing will make it easier for people to go from the text, copy the sniff name and search for it elsewhere.
> Typos in package.xml and README.md

- src/Standards/Squiz/Sniffs/CSS/SemicolonSpacingSniff.php
- src/Standards/Squiz/Tests/CSS/SemicolonSpacingUnitTest.css
- src/Standards/Squiz/Tests/CSS/SemicolonSpacingUnitTest.css.fixed
Allow for the IE < 7 star-prefix hack before style property names.
Fixes #2453
> Squiz/SemicolonSpacing: bug fix

- package.xml
It avoids installing them with the PEAR package.
> Mark recent tests as such

- scripts/ValidatePEAR/ValidatePEARPackageXML.php
This minor change means that the `role` attributes for typical test and sniff files will now be checked to prevent the issue reported and fixed in #2457.
Note: the build won't pass until #2457 has been merged.
> Minor improvement to ValidatePEARPackageXML script

- src/Standards/PSR12/ruleset.xml
As [PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) is now [in review](https://www.php-fig.org/psr/#review) again, an update of the ruleset to reflect the current version was needed.
* Updated all inline documentation texts with the texts as currently in PSR-12.
* Added any new statements which were added to PSR-12.
* Added the `Generic.WhiteSpace.IncrementDecrementSpacing` sniff to satisfy the `There MUST NOT be any whitespace between the increment/decrement operators and the variable being incremented/decremented.` rule.
* Added the `Squiz.WhiteSpace.CastSpacing` sniff to satisfy the `There MUST NOT be any spaces inside the type casting parentheses.` rule.
Note: The `5.3.1`/`5.3.2` split is my doing as it is otherwise completely …
> PSR-12: update the ruleset to reflect current version as under review

- src/Standards/MySource/Sniffs/PHP/AjaxNullComparisonSniff.php
A RuntimeException is thrown in File::getTokensAsString() if the first parameter is not an int or if the supplied int does not exist as a position in the token stack.
AjaxNullComparisonSniff ends up throwing this exception on every file that contains functions with no comment blocks.
> MySource.PHP.AjaxNullComparison throws error when first function has no doc comment

- src/Exceptions/RuntimeException.php
I'm not sure if this is a controversial change or not. 
I can fully understand it being rejected outright, however it is a change I would personally appreciate.
I develop a lot of sniffs in my work, and PhpStorm barks about `PHP_CodeSniffer\Exceptions\RuntimeException` being unhandled. I can add it to the list of handled exceptions but I end up doing this on every project, and I touch hundreds. 
PhpStorm however specifically does _not bark_ about things that extend \RuntimeException out of the box - and it my book it makes sense for `PHP_CodeSniffer\Exceptions\RuntimeException` to extend `\RuntimeException`
> PHP_CodeSniffer\Exceptions\RuntimeException extends \RuntimeException

- package.xml
- src/Filters/GitStaged.php
With the new file added in this commit, a new filter becomes available which can be used in a `pre-commit` git hook, as in:
```bash
phpcs --filter=gitstaged
```
... to only examine the files which you are about to commit.
> Filters: New `GitStaged` filter

- src/Standards/PSR2/Sniffs/ControlStructures/ControlStructureSpacingSniff.php
- src/Standards/PSR2/Tests/ControlStructures/ControlStructureSpacingUnitTest.inc
- src/Standards/PSR2/Tests/ControlStructures/ControlStructureSpacingUnitTest.inc.fixed
- src/Standards/PSR2/Tests/ControlStructures/ControlStructureSpacingUnitTest.php
For the consistency with other sniffs we should allow spaces after opening parenthesis in control structures when the next content is a comment.
Fixes #2411
> Consistency fix to allow space after opening parenthesis in control structures

- src/Standards/Generic/Sniffs/WhiteSpace/ArbitraryParenthesesSpacingSniff.php
- src/Util/Tokens.php
`list()`, just like `array()` is a language construct.
While the parentheses for `array()` would receive the `array` token as the `parenthesis_owner`, the parentheses for `list()` did not.
This commit fixes that inconsistency.
Tested by removing the `T_LIST` token from the "additional tokens indicating that parenthesis are not arbitrary" list in the `Generic.WhiteSpace.ArbitraryParenthesesSpacing` sniff.
> Tokenizer: assign a parenthesis_owner for list() parenthesis

- src/Standards/Squiz/Sniffs/Commenting/BlockCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.php
Just like with scope openers, if a block comment is the first thing after a PHP open tag, no blank line should be required.
> Squiz/BlockComment: don't require a blank line between PHP open tag and block comment

- src/Standards/Squiz/Sniffs/PHP/DisallowMultipleAssignmentsSniff.php
As per the feature request in #2083, the errorcode of the sniff has now been split into two:
* `FoundInControlStructure` when the assignment is within a control structure (with the exception of `while` statements and the first leaf of a `for` statement as those won't be reported anyway).
* `Found` for all other cases.
Fixes #2083
Fixes #1679
> Squiz/DisallowMultipleAssignments: split errorcode

- src/Standards/Generic/Sniffs/Functions/FunctionCallArgumentSpacingSniff.php
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.php
As discussed in #2387, there are dedicated sniffs for checking the spacing around assignment operators:
* `PSR12.Operators.OperatorSpacing`
* `Squiz.WhiteSpace.OperatorSpacing`
Both of these are more comprehensive and more appropriate to use than the limited assignment operator spacing check in this sniff.
Removing the assignment operator spacing checks from this sniff, lowers the risk of fixer conflicts regarding operator spacing and gets rid of duplicate notices in the `PSR12` and `Squiz` standard and inappropriate notices for the `PEAR`, `PSR2` and `Zend` standard.
Includes adjusted unit tests.
> Generic/FunctionCallArgumentSpacing: remove assignment operator spacing checks

- package.xml
- src/Filters/Filter.php
- tests/Core/AllTests.php
- tests/Core/Filters/Filter/AcceptTest.inc
- tests/Core/Filters/Filter/AcceptTest.php
- tests/Core/Filters/Filter/AcceptTest.xml
This PR includes a test to check that paths that include the name of a standard with associated exclude-patterns are still accepted for the list of files to be checked.
The test reproduces https://github.com/squizlabs/PHP_CodeSniffer/issues/2391. 
I followed the coding standards (`php bin/phpcs` reports no problems) but I'm not sure if I added the test to the right place or used the correct approach by using `AcceptTest.inc` as the XML file with the custom standard that reproduces the problem.
I'll be happy to make modifications if the test is considered valid and additional instructions are provided.
As for the solution, I could try to provide one, but I'm not sure what's the right approach in this case. It seems to me that the ignore patterns that are specific to a standard, category or …
> Check paths are accepted if no exclude-pattern matches

- phpcs.xsd
While validating a custom ruleset against the PHPCS XSD schema, I realized that the `phpcs-only` and the `phpcbf-only` attributes were not accounted for in the schema.
Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset#selectively-applying-rules
This PR fixes that.
Notes:
* I have added the `attributeGroup` to nearly all XML elements/nodes, with the exception of:
- The toplevel `ruleset` and the `description` element as per the documentation.
- The `autoload` element as not using autoload for either `phpcs` or `phpcbf` would most likely break the standard using the element.
- The `message` element of the `ruleType` as this only applies to `phpcs` anyway.
- The individual `element` nodes within an array `<property>` group.
* Includes adjusting the `extend` attribute …
> XSD schema: allow for phpcs-only and phpcbf-only attributes

- src/Generators/Text.php
If an individual line of the code sample in the code comparison would be longer than 47/48 characters, a `Warning: str_repeat(): Second argument has to be greater than or equal to 0` would be thrown.
This fixes the error.
Note: this fix does not introduce code-wrapping as that would probably reduce the readability of the code too much.
Instead, the line will just be longer than other lines.
:bulb: **Idea**: should this class respect a `report_width` if set by the user either in their `CodeSniffer.conf` or via the command-line ?
> Text generator throws error when code sample line is too long

- src/Reports/Xml.php
It looks like the `XMLWriter` extension does not respect the OS-specific `PHP_EOL` character, but always uses `\n`, though I have not been able to test this on various OS-es to confirm.
This could be regarded as a bug in PHP itself which may or may not be fixed at some point.
With the above in mind, I have created a fix which contains some redundancy, but should be stable on all OS-es, including if/when the PHP native issue would be fixed.
Alternatively, the whole snippet could be replaced by the code on line 81 of the patch.
Fixes #2526
> Report/XML: bug fix for output on Windows

- src/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php
- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.1.inc
The `T_ENDSWITCH` token wasn't being taken into account as a potential end token.
Fixes #2512
> Squiz/NonExecutableCode: fix bug with alternative switch control structures

- src/Reports/Gitblame.php
- src/Reports/Hgblame.php
- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
`implode()` takes two parameters, `$glue` and `$pieces`.
For historical reasons, `implode()` accepted these parameters in either order, though it was recommended to use the documented argument order of `implode( $glue, $pieces )`.
PHP 7.4 is slated to deprecate the tolerance for passing the parameters for `implode()` in reverse order.
PHP 8.0 is expected to remove the tolerance for this completely.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix
* https://php.net/manual/en/function.implode.php
These instances were discovered while testing a new PHPCompatibility sniff to detect this issue.
> PHP 7.4 compatibility fix / implode argument order

- src/Standards/PEAR/Sniffs/Commenting/FileCommentSniff.php
- src/Standards/PEAR/Tests/Commenting/FileCommentUnitTest.inc
- src/Standards/PEAR/Tests/Commenting/FileCommentUnitTest.php
What with new TLDs being accepted all the time and lots of them being longer then 7 characters, the character limit seems out of date.
Fixes #2566
> PEAR/FileComment: remove the TLD character limit

- package.xml
- src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.7.inc
Prevent creating incorrect fixes and getting into a fixer conflict when both short and long open tags are used in combination with alternative control structures and the short open tags are not recognized because the system on which the scan is run has `short_open_tag=Off`.
Solved by bowing out early when an alternative control structure is detected which was not recognized as such (`scope_opener` not set).
Fixes #2565
> Generic/InlineControlStructure: bug fix

- src/Config.php
Fixes #2549 
`is_readable` will return false if the passed directory falls outside of a set `open_basedir` php.ini directive, while also raising a warning that is suppressed here. I assume that phpcs is initially run from a directory inside the `open_basedir` directive. I wasn't sure if/how one might add tests for this.
> Check if currentDir is readable on loop iteration when initializing Config

- src/Standards/Squiz/Sniffs/ControlStructures/ControlSignatureSniff.php
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc.fixed
The `while()`control structure is special cased to deal with `do {} while();` syntax, but the special casing didn't allow for inline `while()` structures.
Fixes #2562
> Squiz/ControlSignature: fix false positive with inline while()

- src/Standards/PSR12/Tests/Functions/NullableTypeDeclarationUnitTest.inc
- src/Standards/PSR12/Tests/Functions/NullableTypeDeclarationUnitTest.inc.fixed
- src/Tokenizers/PHP.php
The `static` keyword is both used as a modifier keyword for functions and variables as well as for late static binding.
The tokenizer did not take late static binding into account when determining whether a `?` is a `T_NULLABLE` token and because of that would make the determination between `T_NULLABLE` and `T_INLINE_THEN` too early.
This has now been fixed.
Includes unit test via the `PSR12.Functions.NullableTypeDeclaration` sniff.
Fixes #2552
> Tokenizer/PHP: fix recognition of T_NULLABLE

- src/Standards/PSR12/ruleset.xml
As [PSR-12](https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md) is now [in review](https://www.php-fig.org/psr/#review) again, an update of the ruleset to reflect the current version was needed.
This includes all changes as merged to PSR-12 since March 25 / PR #2460.
Refs:
* https://github.com/php-fig/fig-standards/pull/1154
* https://github.com/php-fig/fig-standards/pull/1155
* https://github.com/php-fig/fig-standards/pull/1156
* https://github.com/php-fig/fig-standards/pull/1160
* https://github.com/php-fig/fig-standards/pull/1161
* https://github.com/php-fig/fig-standards/pull/1162
* https://github.com/php-fig/fig-standards/pull/1163
* https://github.com/php-fig/fig-standards/pull/1164
> PSR-12: update ruleset inline documentation

- src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.js
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.js.fixed
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.php
I would like to enforce checking of spaces around assignments as I'm not allowing statements alignment. This simple change (no BC-break) allows me to do so.
> Add option to allow checking assignment operators

- src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
[Fixer conflict series]
The sniff had a potential fixer conflict with the `SuperfluousWhiteSpace` and the `EndFileNewline` sniffs.
This minor change fixes this by bowing out from analysing the space after the operator if the operator is the last non-whitespace token in a file.
Fixer conflict can be reproduced by running the below command over the unit test added by this patch (without the included fix):
`phpcbf ./squiz/tests/whitespace/operatorspacingunittest.inc --standard=Squiz -vv`
> Squiz/OperatorSpacing: fix potential fixer conflict

- src/Standards/Generic/Sniffs/VersionControl/SubversionPropertiesSniff.php
- src/Standards/Squiz/Sniffs/Files/FileExtensionSniff.php
s/getFileName/getFilename
I assume these two are trying to reference this function (like the other instances of the correct spelling/capitalization):
https://github.com/squizlabs/PHP_CodeSniffer/blob/a7403540490022691559380cfc8bfc1342890998/src/Files/File.php#L1212-L1216
> Fix capitalization of getFilename function

- src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php
- src/Standards/Squiz/Sniffs/WhiteSpace/MemberVarSpacingSniff.php
For repos not yet using these sniffs, having metrics available will be useful to find out what the prevalent number of blank lines between properties/functions is.
This will make it more easy to determine what to set for the value of the various properties available.
> Squiz/FunctionSpacing + MemberVarSpacing: add metrics

- package.xml
- scripts/ValidatePEAR/ValidatePEARPackageXML.php
- scripts/validate-pear-package.php
- tests/Core/AbstractMethodUnitTest.php
- tests/Core/AllTests.php
- tests/Core/File/FindEndOfStatementTest.php
- tests/Core/File/FindExtendedClassNameTest.php
- tests/Core/File/FindImplementedInterfaceNamesTest.php
- tests/Core/File/GetMemberPropertiesTest.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/File/GetMethodPropertiesTest.inc
- tests/Core/File/GetMethodPropertiesTest.php
- tests/Core/File/IsReferenceTest.inc
- tests/Core/File/IsReferenceTest.php
- tests/FileList.php
Note: this PR will be easiest to review by looking at the individual commits.
I've created this PR as a precursor to #2189 (move utility methods to static classes) as most of the new utility functions which are mentioned in that issue will be accompanied by unit tests when they are pulled.
Improving the setup of the utility function testing, as done in this PR, will make that so much simpler.
---
Refactor to remove duplicate code.
This new class abstracts out the `setUp()` and `tearDown()` methods which were included in nearly all the utility method test classes.
The methods have been changed to static `setUpBeforeClass()` and `tearDownAfterClass()` with a static property as the initial processed `File` doesn't change between tests, so there is no need to tokenize and process the unit …
> Core tests: set up abstract class and remove code duplication

- package.xml
- src/Standards/Generic/Sniffs/WhiteSpace/ArbitraryParenthesesSpacingSniff.php
- src/Tokenizers/PHP.php
- src/Util/Tokens.php
- tests/Core/Tokenizer/PHP/T_AnonClassParenthesisOwnerTest.inc
- tests/Core/Tokenizer/PHP/T_AnonClassParenthesisOwnerTest.php
Code:
```php
$anonClass = new class($arg) {};
```
As anonymous classes have a distinct token, it makes sense to me to assign that token as the parenthesis owner, along the same lines as is done for anonymous functions.
The main difference is that for anonymous classes, the parenthesis are optional.
Assigning an owner for them can not be done from within the `Tokenizer::createTokenMap()` as at that point in time the `PHP::processAdditional()` method hasn't run yet, so the token is still a `T_CLASS`.
It can however be adjusted from within the `PHP::processAdditional()` method when the `T_CLASS` token is changed to a `T_ANON_CLASS` token.
This commit implements this.
This means that for the `class` token in the above code snippet will now have a `parenthesis_owner`, `parenthesis_opener` and …
> Tokenizer: assign a parenthesis_owner for anonymous classes with parentheses

- src/Config.php
- src/Files/File.php
- src/Files/FileList.php
- src/Reporter.php
- src/Reports/Cbf.php
- src/Reports/Gitblame.php
- src/Reports/Hgblame.php
- src/Reports/Svnblame.php
- src/Ruleset.php
- src/Runner.php
- src/Sniffs/AbstractScopeSniff.php
- src/Standards/Squiz/Sniffs/Debug/JavaScriptLintSniff.php
- src/Standards/Zend/Sniffs/Debug/CodeAnalyzerSniff.php
- src/Tokenizers/Tokenizer.php
- tests/Core/File/GetMemberPropertiesTest.php
Following up on https://github.com/squizlabs/PHP_CodeSniffer/pull/2351/commits/bd961bbe7277aca4689b8059acfe6cbac647cbfa, a further review of the Exceptions being thrown showed some inconsistencies.
As far as I can see, Exceptions thrown by sniffs/utility methods when, for instance, a wrong token is passed, should be `RuntimeException`s, while Exceptions thrown by the `Tokenizer` classes should be `TokenizerException`s.
In a number of places this was applied inconsistently. This has now been fixed.
Aside from that, for quite a number of methods, the `Exception` being thrown has now been documented.
> Use Exceptions consistently

- package.xml
- src/Standards/Generic/Docs/WhiteSpace/SpreadOperatorSpacingAfterStandard.xml
- src/Standards/Generic/Sniffs/WhiteSpace/SpreadOperatorSpacingAfterSniff.php
- src/Standards/Generic/Tests/WhiteSpace/SpreadOperatorSpacingAfterUnitTest.inc
- src/Standards/Generic/Tests/WhiteSpace/SpreadOperatorSpacingAfterUnitTest.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/SpreadOperatorSpacingAfterUnitTest.php
This introduces a new sniff which checks the whitespace between the spread operator and the variable/function call it applies to.
This new sniff has two `public` properties:
* `$spacing` which defaults to `0`, i.e. no space.
* `$ignoreNewlines` which defaults to `false`.
Includes fixers.
Includes documentation.
~~Includes adding this sniff to the PSR12 ruleset.~~
Note: PSR12 only specifies _There MUST NOT be a space between the variadic three dot operator and the argument name_ for **function declarations**.
This sniff, however, checks the spacing for the spread operator in all circumstances in which it can be used, i.e.:
* In function declarations (PHP 5.6).
* In function calls (PHP 5.6).
* In array declarations (PHP 7.4).
> New Generic.WhiteSpace.SpreadOperatorSpacingAfter sniff (PSR12 related)

- src/Generators/Text.php
While new lines were (accidentally) being respected by the existing code, the line length count was not being reset when a new line character was encountered, causing weird line wrapping.
This has been fixed now by:
* First splitting the received text into individual lines.
* Then doing the line wrapping calculations for each line individually.
Includes:
* Reducing the code complexity by removing an `else` and using an early `continue` instead.
* Removing some duplicate function calls.
* Make sure you are on the `master` branch and:
- Create a `Standard/Docs/Category/SomeSniffStandard.xml` file with the following content:
<details>
<summary>XML Documentation code sample</summary>
```xml
<documentation title="Yoda Conditions">
<standard>
<![CDATA[
When doing logical comparisons involving …
```
> Text doc generator does not allow for multi-line rule explanations

- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Classes/ClassDeclarationUnitTest.php
MR for an extra testcase, as mentioned in #2609
> Add extra testcase for PSR2.Classes.ClassDeclaration.SpaceAfterKeyword

- src/Util/Standards.php
Install paths defined via the `installed_paths` configuration option do sometimes contain relative paths that may not exist depending on the current environment.
Resolving such non-existent paths causes `false` to be included in the results, which when used for looking up files/folders, can cause wrong locations to be looked up, and/or errors being thrown. [**`\PHP_CodeSniffer\Util\Standards::getInstalledStandardDetails()`**](https://github.com/squizlabs/PHP_CodeSniffer/blob/3.4.2/src/Util/Standards.php#L85-L88) would for example look for `/ruleset.xml`, ie in the root of the current drive, which could trigger an open basedir restriction error.
> Unresolvable installed_paths can lead to open_basedir errors

- src/Standards/PEAR/Sniffs/WhiteSpace/ObjectOperatorIndentSniff.php
- src/Standards/PEAR/Tests/WhiteSpace/ObjectOperatorIndentUnitTest.inc
- src/Standards/PEAR/Tests/WhiteSpace/ObjectOperatorIndentUnitTest.inc.fixed
- src/Standards/PEAR/Tests/WhiteSpace/ObjectOperatorIndentUnitTest.php
This PR adds supports for multilevel indenting to the amazing sniff `ObjectOperatorIndentSniff` created by @gsherwood.
Multilevel indenting contributes to improve code readability in long chained method calls. This convention is [widely used by Symfony in configuration definitions](https://symfony.com/doc/current/components/config/definition.html#variable-nodes):
```php
$rootNode
->children()
->booleanNode('auto_connect')
->defaultTrue()
->end()
->scalarNode('default_connection')
->defaultValue('default')
->end()
->end()
;
```
The option `multilevel` allows enabling/disabled the new behavior, which is disabled by default to be backward compatible with previous versions.
The sniff can automatically fix violations by adjusting the number of spaces based on the value of property `indent` and …
> Add support for multiline indenting to ObjectOperatorIndentSniff

- src/Standards/Squiz/Sniffs/WhiteSpace/MemberVarSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.php
Squiz/MemberVarSpacing: bug fix - don't remove comments before first member var
If there would be comments (or commented out code) before the first member variable, the fixer as it was, would remove those comments, including potential PHPCS annotations.
By allowing for other comments between the class opener/trait import `use` statement and a property, this is prevented.
The fix now implemented means that if there is anything between the class opener/trait import `use` and the first property, other than a property docblock/comment, the property will be treated as any property and won't get the special "first property" treatment.
> Squiz.WhiteSpace.MemberVarSpacing removes comments before first member var during auto fixing

- src/Standards/PSR12/Sniffs/Files/FileHeaderSniff.php
When dealing with the following code:
```php
<?php
namespace Example\Project;
```
The error message `Header blocks must be followed by a single blank line` was confusing to me.
I realise that PSR-12 calls `<?php` a block, but intuitively it's not, so this PR aims to make the message easier to understand in this situation
> Clarify that blocks should be separated rather than followed by a blank line

- src/Standards/Generic/Sniffs/Files/InlineHTMLSniff.php
- src/Standards/Generic/Sniffs/PHP/CharacterBeforePHPOpeningTagSniff.php
- src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php
- src/Standards/PSR12/Sniffs/Files/FileHeaderSniff.php
- src/Standards/PSR12/Sniffs/Files/OpenTagSniff.php
- src/Standards/PSR2/Sniffs/Files/ClosingTagSniff.php
While working on #2660 I noticed that the declared `@return` for the `process()` method was not correct, I did a quick search for find any other instances where `$phpcsFile->numTokens` is returned and this PR corrects them all
> Correct the return type of process() when jumping to the end of the tokens

- src/Files/File.php
Given the following code sample:
```php
function foo( ?bool $a, $b ) {}
```
In the resulting array, the second parameter `$b` will have the `'type_hint_end_token'` index set to the stack pointer for the end of the type declaration for `$a`, instead of it being the expected `false`.
Caused by the `$typeHintEndToken` not being reset for the next parameter.
I've re-ordered the variable reset now to be the same as the order used for the initial variable declarations before the loop to make it more obvious.
While not necessarily a bug, the `$currVar` variable was also not being reset. That's also been fixed now.
I've not added a unit test as the existing tests do not check the token positions in the array.
> File::getMethodParameters() setting typeHintEndToken for vars with no type hint

- src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
Not all tokens were handled, so I added them + refactored the code a bit.
I also added a bunch of test code to test all the possible (hopefully) variants.
On a side note: I think that the "fix tests" are somewhat broken. I would expect that the code I added won't be altered at all during the fixing process (because the sniffs should ignore it completely) but it seems that some other sniffs "fixes it" - is that right? Is that expected behaviour?
> Squiz.WhiteSpace.OperatorSpacing false positives for some negation operators

- src/Standards/PSR12/Sniffs/Operators/OperatorSpacingSniff.php
- src/Standards/PSR12/Tests/Operators/OperatorSpacingUnitTest.inc
- src/Standards/PSR12/Tests/Operators/OperatorSpacingUnitTest.inc.fixed
PR #2640 made it so the `Squiz.WhiteSpace.OperatorSpacing` sniff now sets a property with the `$nonOperandTokens` from the `register()` method.
However, the PSR12 sniff for the same extends the Squiz sniff, but overloads the `register()` method to set different targets.
This means that the `$nonOperandTokens` array was empty and therefore the `isOperator()` method would nearly always return `true`, which was often incorrect.
Fixed by calling the `parent::register()` method before setting the `$targets` for the PSR12 sniff.
Includes adding unit tests to the PSR12 sniff related to the exclusions handled via the `isOperator()` method, to prevent breakage like this from being able to be merged in the future.
Fixes #2696
> PSR12/OperatorSpacing: hot fix

- src/Sniffs/AbstractArraySniff.php
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc.fixed
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.php
Fixes #2694
I have find out that the issue is also when using coalesce operator.
Example, which is valid code, but has no sens would be:
```php
$array = [
'foo' => 'foo',
'bar' => $baz ? ['abc'] : ['def'],
'hey' => $baz ?? ['one'] ?? ['two'],
];
```
Without fix we have 5 elements in `$indices` but we should have 3.
Added tests to cover changes.
> Hotfix: correct array indicies when using ternary or coalesce ops

- src/Standards/Generic/Sniffs/PHP/LowerCaseKeywordSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.php
- src/Standards/Squiz/Sniffs/Functions/LowercaseFunctionKeywordsSniff.php
- src/Standards/Squiz/Tests/Functions/LowercaseFunctionKeywordsUnitTest.inc
- src/Standards/Squiz/Tests/Functions/LowercaseFunctionKeywordsUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Functions/LowercaseFunctionKeywordsUnitTest.php
Updated sniffs:
- Generic.PHP.LowerCaseKeyword
- Squiz.Functions.LowercaseFunctionKeywords
> Hotfix: PHP 7.4 fn keyword should be lowercase

- src/Sniffs/AbstractArraySniff.php
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc.fixed
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.php
Example code:
```php
<?php
$array = [
1 => '1',
2 => fn ($x) => yield 'a' => $x,
3 => '3',
];
```
Array indices:
```
Array
(
[0] => Array
(
[index_start] => 9
[index_end] => 9
[arrow] => 11
[value_start] => 13
)
[1] => Array
(
[index_start] => 17
[index_end] => 17
[arrow] => 19
[value_start] => 21
)
[2] => Array
(
[index_start] => 21  // <---- the same as value start in 1, WRONG
[index_end] => 31
[arrow] => 33
[value_start] => 35
)
[3] => Array
(
[index_start] => 39
[index_end] => 39
[arrow] => 41
[value_start] => 43
)
)
```
> Hotfix: array indices with PHP 7.4 fn closure

- src/Tokenizers/PHP.php
For type hints and return type we usually have T_STRING, but we have couple
different tokens, and these are:
- T_CALLABLE
- T_PARENT
- T_SELF
We need to skip them here.
Related to #2523
> Hotfix: PHP 7.4 fn closure Return type hint tokens

- src/Standards/Squiz/Tests/PHP/DisallowInlineIfUnitTest.inc
- src/Standards/Squiz/Tests/PHP/DisallowInlineIfUnitTest.php
- src/Tokenizers/PHP.php
Fix #2713
Missing unit test for:
```php
$fn = fn ($a) => $a ? fn () : string => 'a' : fn () : string => 'b';
```
> Hotfix: PHP 7.4 fn closure tokenizer with ternary

- src/Standards/PEAR/Sniffs/Functions/ValidDefaultValueSniff.php
- src/Standards/PEAR/Tests/Functions/ValidDefaultValueUnitTest.inc
- src/Standards/PEAR/Tests/Functions/ValidDefaultValueUnitTest.php
> Adds support for PHP 7.4 arrow functions in PEAR.Functions.ValidDefaultValue sniff

- .travis.yml
As [PHP 7.4 has been released](https://www.php.net/archive/2019.php#2019-11-28-1), the build against PHP 7.4 should no longer be allowed to fail.
As that build was combined with the PHPStan check which - for now - should be allowed to fail, I've split the build into two:
1. a "normal" PHP 7.4 build which is not allowed to fail.
2. a PHPStan specific build which is allowed to fail.
> Travis: don't allow PHP 7.4 build to fail

- src/Ruleset.php
Problem: autoload files are confused with globally available files. See https://github.com/pfrenssen/coder/issues/54
If you specify `<autoload>./autoload.php</autoload>` in your ruleset.xml file then a completely different autoload.php file from your system might be executed, even although you specified a relative path.
Steps to reproduce:
1. Clone https://github.com/klausi/test_phpcs
2. Run `composer install`
3. Run `./vendor/bin/phpcs --standard=./standard test.php`
Output:
`PHP Parse error:  syntax error, unexpected 'invalid' (T_STRING) in test_phpcs/autoload.php on line 3`
Which means the wrong autoload.php file was included.
Proposed solution: Try to include relative paths first, then try global paths.
Not sure how we can test this, any tips for that?
> Autoload relative paths first to avoid confusion with files from the global include path

- src/Config.php
Closes #2698
Checks for the existence of the `shell_exec` function before attempting to use it to determine shell width, falling into the `else` clause where the width will be set to `0`, similar to what would happen if `stty` program did not exist or failed to run if `shell_exec` did exist.
> Fix warning determining shell width on system without shell_exec

- package.xml
- src/Standards/Generic/Docs/PHP/DisallowRequestSuperGlobalStandard.xml
- src/Standards/Generic/Sniffs/PHP/DisallowRequestSuperGlobalSniff.php
- src/Standards/Generic/Tests/PHP/DisallowRequestSuperGlobalUnitTest.inc
- src/Standards/Generic/Tests/PHP/DisallowRequestSuperGlobalUnitTest.php
Create a new sniff which will listen on the variable constant ($). If the $_REQUEST super global is detected, add the following error: 
> The $_REQUEST super global should not be used. Use $_GET, $_POST or $_COOKIE instead
This implements #2373
> Disallow the use of $_Request

- src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.1.js.fixed
These tests need an update each time the year changes as the `.fixed` file checks for the hard-coded current year.
Happy new year!
> Squiz/FileComment: update the "fixed" files copyright year

- src/Standards/Generic/Tests/Files/ExecutableFileUnitTest.php
Windows doesn't have the concept of executable files this sniff targets, so the test would always fail.
> Generic/ExecutableFile: skip tests on Windows

- src/Files/File.php
- src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php
- src/Util/Tokens.php
I'm integrating [Psalm](https://psalm.dev/) into my custom standard, and code like this:
```php
// Find the position of each EOL sequence.
while (($pos = $phpcsFile->findNext(T_WHITESPACE, $start, null, false, $phpcsFile->eolChar))) {
// Count the number of EOL sequences directly following the current token.
$innerStart = ($pos + 1);
```
... is an issue, because `findNext` is documented to return `int|bool`, when in fact it returns `int|false`. The `while` loop removes `false` from the type, so `$pos` is then `int|true` when it should be just `int`, and adding `1` to a variable that is possibly `true` is a problem.
I decided to fix all cases of `int|bool` that I could find where the method only returns `false` and not `true`. There were also two cases where `bool` wasn't even included in …
> Return int|false instead of int|bool

- src/Standards/PSR12/Tests/Functions/NullableTypeDeclarationUnitTest.inc
- src/Standards/PSR12/Tests/Functions/NullableTypeDeclarationUnitTest.inc.fixed
- src/Tokenizers/PHP.php
This is an attempt to make the differentiation between `T_NULLABLE` and `T_INLINE_THEN` more stable.
There is only a limited set of tokens which can be used for type declarations. If a `?` is not followed by one of these, we can be certain that it is a ternary operator `T_INLINE_THEN`.
The more resource intensive "walking back" check will now only be done when it could be either.
The "walking back" token logic could probably still do with an additional check for `T_INSTANCEOF`, but the changes now made, should prevent the majority of issues where `T_INLINE_THEN` is misidentified as `T_NULLABLE`.
Includes unit tests via the PSR12.Functions.NullableTypeDeclaration sniff.
Fixes #2791
Note: the build failure is unrelated to this PR and will be fixed via #2793
> Tokenizer: improve tokenization of T_NULLABLE vs T_INLINE_THEN

- package.xml
- src/Standards/PSR12/Sniffs/Files/ImportStatementSniff.php
- src/Standards/PSR12/Tests/Files/ImportStatementUnitTest.inc.fixed
This can be easily fixable, just be removing the slash.
Added .fixed file with expected result of the fixer.
> Feature: fixable LeadingSlash error in PSR12.Files.ImportStatement

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillNumericSeparatorTest.inc
- tests/Core/Tokenizer/BackfillNumericSeparatorTest.php
1. Remove a stray invisible whitespace character/null byte from the test case file.
2. Add a large number of additional test cases.
1. Fixed reversed order of the parameters in the `assertSame()`. The first parameter is `$expected`, the second `$result`.
Having the parameters in the correct order makes debugging the tests easier as the messages send by PHPUnit will be correct.
2. Test that the final token has the correct code **and** the correct type.
3. Correct the expected type for two test cases based on how PHP 7.4 tokenizes these.
4. Add datasets for the new test cases which are to be handled by the backfill.
Add tests to verify that numbers using numeric separators which are considered parse errors and/or which aren't relevant to the backfill, do not incorrectly trigger the backfill …
> [Hotfix] Tokenizer / numeric separators backfill: fix all known issues

- package.xml
- src/Ruleset.php
- tests/Core/Ruleset/RuleInclusionAbsoluteLinuxTest.php
- tests/Core/Ruleset/RuleInclusionAbsoluteLinuxTest.xml
- tests/Core/Ruleset/RuleInclusionAbsoluteWindowsTest.php
- tests/Core/Ruleset/RuleInclusionAbsoluteWindowsTest.xml
- tests/Core/Ruleset/RuleInclusionTest-include.xml
- tests/Core/Ruleset/RuleInclusionTest.php
- tests/Core/Ruleset/RuleInclusionTest.xml
This fixes a bug where properties set for rules included via a path to the sniff file or to an included standards file, would be disregarded if the slashes used in the path did not match the slashes expected for the OS on which the ruleset is being run.
Includes adding initial integration tests for the Ruleset class.
Fixes #2497
> Ruleset::processRule(): fix handling of rules included via path

- src/Standards/PSR12/Sniffs/ControlStructures/ControlStructureSpacingSniff.php
- src/Standards/PSR12/Tests/ControlStructures/ControlStructureSpacingUnitTest.inc
- src/Standards/PSR12/Tests/ControlStructures/ControlStructureSpacingUnitTest.inc.fixed
PSR12 does not forbid comments interlaced in the conditions of a (multi-line) control structure.
However, the sniff didn't handle those correctly.
With the example code added to the unit test case file, the sniff, as it was, would throw an unsolvable error which would also cause fixer conflicts with the sniff itself:
```
82 | ERROR | [x] Each line in a multi-line control structure must be indented at least once; expected at least 8 spaces, but found 0
|       |     (PSR12.ControlStructures.ControlStructureSpacing.LineIndent)
```
```
PHP_CodeSniffer version 3.5.3 (stable) by Squiz (http://www.squiz.net)
PHPCBF RESULT SUMMARY
----------------------------------------------------------------------------------------------------------------------------------------
FILE …
```
> PSR12.ControlStructures.ControlStructureSpacing does not ignore comments between conditions

- src/Tokenizers/PHP.php
- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
Typed properties are explicitly also supported for PHP 4-style properties using just the `var` or `static` keyword.
However, in that case, the nullable indicator `?` was not converted from `T_INLINE_THEN` to `T_NULLABLE`.
Fixed now.
Includes unit tests via the `File::getMemberProperties()` method.
Ref: https://wiki.php.net/rfc/typed_properties_v2
> PHP4-style typed properties not tokenized correctly

- src/Standards/Generic/Sniffs/Files/LineLengthSniff.php
I'm overriding this method in Coder and then PHPStan complains that the return type is not correct. Should be void.
> docs(LineLength): Method does not return anything, so return type is void

- src/Files/File.php
PHPStan error report in Coder:
```
Parameter #2 $ignore of method PHP_CodeSniffer\Files\File::findStartOfStatement() expects array|int|null, string given.
```
But token types can also be strings, let's fix the data types in the doc blocks here.
> docs(File): Fix data type of token types that can also be string

- src/Sniffs/AbstractArraySniff.php
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc.fixed
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.php
I've changed the approach completely. In my opinion it much clearer.
Added tests to cover the issue described in #2745.
Fixes #2745
It solves also the problem when we had `["value_start" => false]` for an empty array.
> Hotfix: correct array indices

- src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.1.inc
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/FunctionSpacingUnitTest.php
Similar to #2656
If there would be comments (or commented out code) before the first method or after the last method in an OO structure, the fixer as it was, would - depending on the various `$spacing` settings, potentially remove the space between the method and the comment which would easily conflict with other comment rules.
By allowing for comments before the first method/after the last method, this is prevented.
The fix now implemented means that if there is anything between the class opener/trait import `use` and the first method, other than a function docblock/comment, the method will be treated as any method and won't get the special "first method" treatment.
Similarly, when there is anything between the last method and the class closer, other than a trailing comment, the method …
> Squiz.WhiteSpace.FunctionSpacing can remove spaces between comment and first/last method during auto-fixing

- src/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
- src/Standards/PSR1/Tests/Files/SideEffectsUnitTest.1.inc
- src/Tokenizers/PHP.php
The `declare` language construct can also use the alternative control structure syntax, but in that case would not get assigned `scope_opener` or `scope_closer` indexes.
This fixes that.
Includes unit test via the `PSR1.Files.SideEffects` sniff, which also needed as small tweak to disregard the semicolon after the `enddeclare`.
> Tokenizer does not support alternative syntax for declare statements

- src/Standards/PSR12/Docs/Functions/NullableTypeDeclarationStandard.xml
* The line length of the code samples was too long.
* The second code sample would not be shown as it was not accompanied by a `valid` case, nor wrapped in its own `code_comparison` block.
> NullableTypeDeclaration: fix CLI documentation

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillFnTokenTest.inc
- tests/Core/Tokenizer/BackfillFnTokenTest.php
Defensive coding for the arrow functions backfill. This fixes a number of "undefined index" PHP notices when arrow functions are being declared during live coding.
```
Notice: Undefined offset: 561 in /path/to/PHP_CodeSniffer/src/Tokenizers/PHP.php on line 1807
Notice: Undefined offset: 561 in /path/to/PHP_CodeSniffer/src/Tokenizers/PHP.php on line 1808
Notice: Undefined offset: 561 in /path/to/PHP_CodeSniffer/src/Tokenizers/PHP.php on line 1815
```
It also fixes a bug where an inner for loop was using the wrong variable for the condition part.
> Undefined Offset notice during live coding of arrow functions

- src/Files/File.php
- src/Sniffs/AbstractPatternSniff.php
- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillFnTokenTest.inc
- tests/Core/Tokenizer/BackfillFnTokenTest.php
This commit implements the proposal as outlined in https://github.com/squizlabs/PHP_CodeSniffer/issues/2859#issuecomment-583695917.
The `fn` keyword will now only be tokenized as `T_FN` if it really is an arrow function, in which case it will also have the additional indexes set in the token array.
In all other cases - including when the keyword is used in a function declaration for a named function or method -, it will be tokenized as `T_STRING`.
Includes numerous additional unit tests.
Includes removing the changes made to the `File::getDeclarationName()` function and the `AbstractPatternSniff` in commit 37dda44ed3bf34dbaad6e0dd1e9e10b03d67ed00 as those are no longer necessary.
Fixes #2859
> [Hotfix] PHP Tokenizer: improve arrow function backfill consistency

- src/Reports/Info.php
This partially reverts the change made to this particular file in e9ebf5253a3e6dd3cc4b584ce54b1f4c34fcb1f3
The `floor( $countWidth / 3)` was causing an _undefined variable_ notice as the original definition of the variable was removed.
> Undefined variable error when using Info report

- tests/Core/Tokenizer/BackfillFnTokenTest.inc
- tests/Core/Tokenizer/BackfillFnTokenTest.php
Follow up on #2860. This fixes the tests.
* Adds tests with mixed case `fn` keyword.
* Removes a few redundant tests (weren't testing anything which wasn't covered already).
* Adds a couple of tests which were missing from the data provider.
* Updates the test itself to use a `$testContent` parameter to allow for the `fn` in the tests being non-lowercase.
> Tokenizer arrow functions backfill tests: fix it ;-)

- src/Config.php
close #2861
I've moved description from property comment to class level annotaion
> move Config::$settings description to class annotations

- src/Standards/Generic/Sniffs/PHP/DeprecatedFunctionsSniff.php
This code snippet was introduced in ec29df437d7ce83bf63f73cdf6c4583b5ea91d8e to allow for running the sniff on HHVM, but HHVM support has been dropped in PHPCS 3.3.1.
In native PHP, the `ReflectionFunctionAbstract::isDeprecated()` method is available since PHP 5.2, so this check is redundant.
Ref: https://www.php.net/manual/en/reflectionfunctionabstract.isdeprecated.php
Loosely related to #2742
> Generic/DeprecatedFunctions: remove redundant `method_exists()`

- src/Tokenizers/PHP.php
PR #2860 made a change to the tokenizer which changes the token type of an `fn` keyword (back) to `T_STRING` if it turns out not to be an arrow function.
That change did not include a verbose message for tokenizer debugging. Fixed now.
> PHP tokenizer: add missing verbose message

- src/Standards/Squiz/Sniffs/PHP/DisallowMultipleAssignmentsSniff.php
- src/Standards/Squiz/Tests/PHP/DisallowMultipleAssignmentsUnitTest.inc
The `Squiz.PHP.DisallowMultipleAssignments` intended to ignore property declarations, but did not allow for PHP 7.4 typed properties.
I've now moved the _"is this a property ?"_ check up to bow out earlier for all properties.
I've also added tests for multi-property declarations. While it is debatable whether or not this sniff should report on these, the existing behaviour was to ignore them. This behaviour has been maintained and is now documented and safeguarded via the test.
Fixes #2787
> Squiz/DisallowMultipleAssignments: fix ignoring of property declarations

- .travis.yml
In contrast to 60a91b37cb1705468439798856e5ce3e026d53f2, testing against PHP `nightly` can actually be done already, we just need to tell Composer to ignore the PHPUnit PHP requirements ;-)
Currently testing against nightly results in two failed tests:
```
1) PHP_CodeSniffer\Standards\Generic\Tests\PHP\DeprecatedFunctionsUnitTest::testSniff
[LINE 3] Expected 1 error(s) in DeprecatedFunctionsUnitTest.inc but found 0 error(s).
[LINE 4] Expected 1 error(s) in DeprecatedFunctionsUnitTest.inc but found 0 error(s).
```
Both test failures are caused by PHP 8 having removed the functions being tested, i.e. Reflection doesn't see them as deprecated anymore as the function doesn't exist anymore.
> PHPCS 4.x: test against nightly

- tests/Core/File/FindEndOfStatementTest.php
* Use the `AbstractMethodUnitTest::getTargetToken()` method instead of doing a `findNext()` with a calculation.
This makes the `$start` token retrieval more descriptive.
* Assert based on the token pointers, not the sub-array value.
As for both the "expected" as well as "found" values, the token sub-array is retrieved from the same `$tokens` variable, if the token pointers are the same, the sub-arrays will be too, so doing the comparison based on the sub-array doesn't add any extra value to the test.
Also: doing an array assertion is more expensive than doing a simple integer based assertion.
* Remove redundant calls to the `getTokens()` method.
> FindEndOfStatementTest: simplify the tests

- src/Standards/Squiz/Sniffs/Scope/StaticThisUsageSniff.php
- src/Standards/Squiz/Tests/Scope/StaticThisUsageUnitTest.inc
- src/Standards/Squiz/Tests/Scope/StaticThisUsageUnitTest.php
Related #2523
I am not sure about this change as this is actually invalid code.
We cannot use `$this` even inside closure, as then closure is not gonna
be usable. The same in case of normal closure.
Maybe here we should have another fix then?
> Hotfix: fn arrow closure - Squiz.Scope.StaticThisUsage

- src/Files/File.php
- tests/Core/File/GetMethodPropertiesTest.inc
- tests/Core/File/GetMethodPropertiesTest.php
As of PHP 8.0, `static` will be allowed as a return type.
Ref: https://wiki.php.net/rfc/static_return_type
This commit adjusts the `File::getMethodProperties()` utility method to allow for that.
> File::getMethodProperties(): allow for return type "static"

- src/Util/Cache.php
PHPCS uses the `iconv` extension, if available, to determine the length of tokens. The results of sniffs can be different if the length has changed.
While not in use in PHPCS itself, external standards _may_ use additional PHP extension which may or may not be loaded and can influence the results of a run.
Think: a sniff which checks the naming conventions of function/class/variable names and takes the file encoding into account. This sniff may be using the Mbstring PHP extension and the sniff could either be skipped if Mbstring is not available or fall back to a less reliable way of determining compliance with the naming conventions.
With the above in mind, I believe the cache should keep a hash of the loaded PHP extensions and invalidate the cache if the set of loaded extensions has …
> Invalidate the cache when a different set of PHP extensions are loaded

- src/Files/File.php
- tests/Core/File/IsReferenceTest.inc
- tests/Core/File/IsReferenceTest.php
The `&` in a closure declared to return by reference was not recognized as a reference.
Fixed now.
> File::isReference() does not detect return by reference for closures

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillFnTokenTest.inc
- tests/Core/Tokenizer/BackfillFnTokenTest.php
Follow up on #2952 which was merged for PHPCS `3.5.6` - @gsherwood with that in mind, can this PR also be earmarked for PHPCS 3.5.6 ?
> PHP 8.0 | Tokenizer/PHP: add support for `static` return type to arrow functions

- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/File/GetMethodPropertiesTest.inc
- tests/Core/File/GetMethodPropertiesTest.php
PHP 8.0 will introduce a new pseudo-type `mixed`.
This PR adds tests to the `Core` testsuite for the `File::getMethodParameters()`, `File::getMethodProperties()` and `File::getMemberProperties()` utility methods confirming that the `mixed` type is handled correctly by these methods without further changes.
Refs:
* https://wiki.php.net/rfc/mixed_type_v2
Partially addresses #2968
Partially replaces  PR #3009, #3010, #3011
> PHP 8.0 | File::get[Method|Member][Parameters|Properties](): add unit test with "mixed" type

- package.xml
- src/Tokenizers/PHP.php
- src/Util/Tokens.php
- tests/Core/Tokenizer/ShortArrayTest.inc
- tests/Core/Tokenizer/ShortArrayTest.php
As of PHP 8, magic constants can be dereferenced, however, the square brackets are incorrectly tokenized as _short array_ brackets instead of as "normal" square brackets.
Fixed by:
* Adding a new `$magicConstants` array to the `Util\Tokens` calls.
* Adding the `$magicConstants` to the allowed tokens for leaving the brackets alone in the `Tokenizers\PHP` class.
Includes adding unit tests for this section of the `PHP::processAdditional()` method.
I've added as many relevant syntaxes as I could come up with, but won't claim that the unit test case file covers every possible scenario. Should be a good start though.
Ref: https://wiki.php.net/rfc/variable_syntax_tweaks#constants_and_magic_constants
> PHP 8.0 | Tokenizer/PHP: support PHP8 magic constant dereferencing

- .gitattributes
- package.xml
- phpcs.xml.dist
- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/StableCommentWhitespaceTest.inc
- tests/Core/Tokenizer/StableCommentWhitespaceTest.php
- tests/Core/Tokenizer/StableCommentWhitespaceWinTest.inc
- tests/Core/Tokenizer/StableCommentWhitespaceWinTest.php
As described in issue #3002, in PHP 8 a trailing new line is no longer included in a `T_COMMENT` token.
This commit "forward-fills" the PHP 5/7 tokenization of `T_COMMENT` tokens for PHP 8, i.e. the PHP 8 comment tokenization is undone and changed back to how comments followed by a new line were tokenized in PHP 5/7.
Includes extensive unit tests. I'm hoping to have caught everything affected :fingers_crossed:
The initial set of unit tests `StableCommentWhitespaceTest` use Linux line endings `\n`.
The secondary set of unit tests `StableCommentWhitespaceWinTest` use Windows line endings `\r\n` to test that the fix is stable for files using different line ending.
For the tests with Windows line endings, both the test case file as well as the actual test file have been set up to use Windows …
> PHP 8.0 | Tokenizer/PHP: stabilize comment tokenization

- tests/Core/Tokenizer/BackfillFnTokenTest.php
The scope closers weren't being tested properly as the local `$closer` variable was looking for the wrong array index.
Once that was enabled, it exposed another issue in the tests: nested arrow functions with a scope closer being shared with the "outer" arrow function did not have the correct expectations set.
Fixed now by:
* Selectively skipping the 'scope_condition' check for the scope closer in the `backfillHelper()` method.
* Checking that the `scope_opener` for such shared `scope_closer`s actually points to the "outer" arrow function.
> BackfillFnTokenTest: fix bug in the tests

- src/Generators/Markdown.php
> Markdown generator does not output headings correctly

- src/Tokenizers/PHP.php
PHP 8.0 elevates a number of notices/warnings to errors, which now exposes a bug in the `goto` tokenizer logic.
Error: `Trying to access array offset on value of type null`
Fixed by making sure that the token being accessed is an array before trying to access it.
Discovered via a failing unit test in WordPressCS.
> Error generated during tokenizing of goto statements on PHP 8

- src/Standards/Generic/Sniffs/NamingConventions/CamelCapsFunctionNameSniff.php
- src/Standards/PEAR/Sniffs/NamingConventions/ValidFunctionNameSniff.php
This adds `serialize` and `unserialize` to list of known magic methods and fixes #3029. I also updated list a bit to match the same order as [list in PHP documentation](https://www.php.net/manual/en/language.oop5.magic.php) to make comparing lists in the future easier.
> Add serialize and unserialize to list of known magic methods

- src/Standards/PSR12/Sniffs/Functions/NullableTypeDeclarationSniff.php
- src/Standards/PSR12/Tests/Functions/NullableTypeDeclarationUnitTest.inc
- src/Standards/PSR12/Tests/Functions/NullableTypeDeclarationUnitTest.inc.fixed
- src/Standards/PSR12/Tests/Functions/NullableTypeDeclarationUnitTest.php
PHP 8.0 introduces `static` as a valid return type. This PR adjusts the `PSR12.Functions.NullableTypeDeclaration` sniff to handle that return type as well.
> PHP 8.0 | PSR12/NullableTypeDeclaration: allow for static return type

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/StableCommentWhitespaceTest.inc
- tests/Core/Tokenizer/StableCommentWhitespaceTest.php
- tests/Core/Tokenizer/StableCommentWhitespaceWinTest.inc
- tests/Core/Tokenizer/StableCommentWhitespaceWinTest.php
Follow up on #3027 which handled this for slash-style comments.
Hash-style comments were not addressed in the earlier change. This oversight has now been fixed.
Fixes #3069
> PHP 8.0 | Stabilize comment tokenization for hash comments

- .travis.yml
As there is already a PHP 7.4 build in place running exactly the same build as the PHP 7.4 PHPStan build, with the exception of the actual PHPStan run, we can skip the "normal" build checks for the PHPStan build and just and only run PHPStan.
If so desired, I could also move the XML lint & PEAR validation check to a separate build running only those checks, simplifying the Travis script some.
> Travis: simpify PHPStan build

- package.xml
- src/Tokenizers/PHP.php
- src/Tokenizers/Tokenizer.php
- src/Util/Tokens.php
- tests/Core/Tokenizer/NullsafeObjectOperatorTest.inc
- tests/Core/Tokenizer/NullsafeObjectOperatorTest.php
- tests/Core/Tokenizer/ShortArrayTest.inc
- tests/Core/Tokenizer/ShortArrayTest.php
This PR addresses the tokenizer changes needed for #3040. Once this PR has been merged, the sniff specific changes will be pulled with a PR per sniff.
PHP 8 introduces a new object chaining operator `?->` which short-circuits moving to the next expression if the left-hand side evaluates to `null`.
This operator can not be used in write-context, but that is not the concern of the PHPCS `Tokenizers\PHP` class.
This commit:
* Defines the token constant for PHP < 8.0.
* Adds a backfill for the nullsafe object operator for PHP < 8.0 to the PHP tokenizer.
* Adds the token to applicable token lists in the PHP and base tokenizer class, like the one used in the short array re-tokenization.
* Adds perfunctory unit tests for the nullsafe object operator backfill.
* Adds a unit test using the …
> PHP 8.0 | Tokenizer/PHP: add support for nullsafe object operator

- src/Filters/Filter.php
- tests/Core/Filters/Filter/AcceptTest.php
This is a suggested fix for #3007 
To unit test this properly, you'd need to mock the `is_dir` function on [Filter.php#L237](https://github.com/squizlabs/PHP_CodeSniffer/blob/a957a73e3533353451eb9fd62ee58bd0aba2773c/src/Filters/Filter.php#L237).  Sorry, I couldn't find a neat way to do that in the time I had available.
> Fixed bug #3007: Directory exclude pattern improperly excludes directories with names that start the same

- .travis.yml
The builds are failing a little too often for my taste on the below error.
```
[Composer\Downloader\TransportException]
Peer fingerprint did not match
```
I'm prefixing the `composer install` commands now with `travis_retry` in an attempt to get round this problem.
Ref:
* https://docs.travis-ci.com/user/common-build-problems/#timeouts-installing-dependencies
> Travis: retry composer install on failure

- src/Standards/Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php
- src/Standards/Zend/Tests/NamingConventions/ValidVariableNameUnitTest.inc
- src/Standards/Zend/Tests/NamingConventions/ValidVariableNameUnitTest.php
> PHP 8.0 | Zend/ValidVariableName: allow for nullsafe object operator

- src/Standards/Squiz/Sniffs/PHP/LowercasePHPFunctionsSniff.php
- src/Standards/Squiz/Tests/PHP/LowercasePHPFunctionsUnitTest.inc
- src/Standards/Squiz/Tests/PHP/LowercasePHPFunctionsUnitTest.inc.fixed
> PHP 8.0 | Squiz/LowercasePHPFunctions: allow for nullsafe object operator

- src/Standards/Squiz/Sniffs/WhiteSpace/ObjectOperatorSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ObjectOperatorSpacingUnitTest.php
This adds sniffing for the spacing around nullsafe object operators to the sniff.
> PHP 8.0 | Squiz/ObjectOperatorSpacing: sniff for nullsafe object operator

- src/Standards/Squiz/Sniffs/PHP/DisallowSizeFunctionsInLoopsSniff.php
- src/Standards/Squiz/Tests/PHP/DisallowSizeFunctionsInLoopsUnitTest.inc
> PHP 8.0 | Squiz/DisallowSizeFunctionsInLoops: allow for nullsafe object operator

- src/Standards/Squiz/Sniffs/NamingConventions/ValidVariableNameSniff.php
- src/Standards/Squiz/Tests/NamingConventions/ValidVariableNameUnitTest.inc
- src/Standards/Squiz/Tests/NamingConventions/ValidVariableNameUnitTest.php
> PHP 8.0 | Squiz/ValidVariableName: allow for nullsafe object operator

- src/Standards/Squiz/Sniffs/Operators/IncrementDecrementUsageSniff.php
- src/Standards/Squiz/Tests/Operators/IncrementDecrementUsageUnitTest.inc
- src/Standards/Squiz/Tests/Operators/IncrementDecrementUsageUnitTest.php
Note: there is quite a lot more which can do with improvement in this sniff, as the sniff is not code style independent, nor does it take all allowed syntaxes into account, such as array in/decrementing `$a[0]++` or nested property in/decrementing `--$obj->prop->nested` and more along those lines, but that's outside the scope of this PR.
> PHP 8.0 | Squiz/IncrementDecrementUsage: allow for nullsafe object operator

- src/Standards/PSR12/Sniffs/Classes/ClassInstantiationSniff.php
- src/Standards/PSR12/Tests/Classes/ClassInstantiationUnitTest.inc
- src/Standards/PSR12/Tests/Classes/ClassInstantiationUnitTest.inc.fixed
- src/Standards/PSR12/Tests/Classes/ClassInstantiationUnitTest.php
> PHP 8.0 | PSR12/ClassInstantiation: allow for nullsafe object operator

- package.xml
- src/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
- src/Standards/PSR1/Tests/Files/SideEffectsUnitTest.13.inc
- src/Standards/PSR1/Tests/Files/SideEffectsUnitTest.14.inc
- src/Standards/PSR1/Tests/Files/SideEffectsUnitTest.15.inc
- src/Standards/PSR1/Tests/Files/SideEffectsUnitTest.16.inc
- src/Standards/PSR1/Tests/Files/SideEffectsUnitTest.php
Note: adding the token to the second condition (test 15/16) seems redundant and the original `T_OBJECT_OPERATOR` could be removed here too as, if an instantiated object is seen before the `defined()`, a side-effect would already have registered for the variable anyway.
> PHP 8.0 | PSR1/SideEffects: allow for nullsafe object operator

- src/Standards/Generic/Sniffs/PHP/ForbiddenFunctionsSniff.php
- src/Standards/Generic/Tests/PHP/ForbiddenFunctionsUnitTest.inc
> PHP 8.0 | Generic/ForbiddenFunctions: allow for nullsafe object operator

- src/Standards/Generic/Sniffs/PHP/SAPIUsageSniff.php
- src/Standards/Generic/Tests/PHP/SAPIUsageUnitTest.inc
> PHP 8.0 | Generic/SAPIUsage: allow for nullsafe object operator

- src/Standards/Generic/Sniffs/NamingConventions/UpperCaseConstantNameSniff.php
- src/Standards/Generic/Tests/NamingConventions/UpperCaseConstantNameUnitTest.inc
> PHP 8.0 | Generic/UpperCaseConstantName: allow for nullsafe object operator

- src/Files/File.php
The `File::getMethodParameters()` returns a `reference_token` index, so no need to do any token walking.
> File::isReference(): simplify logic

- src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.1.inc
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.2.inc
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.2.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/ScopeIndentUnitTest.php
> PHP 8.0 | Generic/ScopeIndent: allow for nullsafe object operator

- src/Standards/PEAR/Sniffs/WhiteSpace/ObjectOperatorIndentSniff.php
- src/Standards/PEAR/Tests/WhiteSpace/ObjectOperatorIndentUnitTest.inc
- src/Standards/PEAR/Tests/WhiteSpace/ObjectOperatorIndentUnitTest.inc.fixed
- src/Standards/PEAR/Tests/WhiteSpace/ObjectOperatorIndentUnitTest.php
This adds sniffing for the indentation of nullsafe object operators to the sniff.
> PHP 8.0 | PEAR/ObjectOperatorIndent: sniff for nullsafe object operator

- tests/Standards/AbstractSniffUnitTest.php
At the bottom of a test run a message along the lines of `4 sniff test files generated 2 unique error codes; 0 were fixable (0%)` is shown.
The unique error codes, as well as the fixable count and percentage would only include `error` codes and would totally disregard the codes coming from `warning`s.
Fixed now.
> AbstractSniffUnitTest: bug fix - warnings not counted in total

- package.xml
- src/Files/File.php
- src/Tokenizers/PHP.php
- src/Tokenizers/Tokenizer.php
- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/File/GetMethodPropertiesTest.inc
- tests/Core/File/GetMethodPropertiesTest.php
- tests/Core/Tokenizer/BackfillFnTokenTest.inc
- tests/Core/Tokenizer/BackfillFnTokenTest.php
- tests/Core/Tokenizer/ScopeSettingWithNamespaceOperatorTest.inc
- tests/Core/Tokenizer/ScopeSettingWithNamespaceOperatorTest.php
Follow up on https://github.com/squizlabs/PHP_CodeSniffer/pull/3063#issuecomment-683476495
The `namespace` keyword as an operator is perfectly valid to be used as part of a type declaration.
See: https://3v4l.org/hvjlL
This usage was so far not supported in the tokenizer for the determination whether a `?` is a nullable type token or a ternary, nor was it taken into account for skipping over the return type for an arrow function in the backfill.
Lastly, this usage was so far not supported in the `File::getMethodParameters()`, `File::getMethodProperties()` and the `File::getMemberProperties()` methods.
Fixed now.
Includes select unit tests covering the functionality.
--- 
[Edit]
I've added an additional commit fixing the `Tokenizer::recurseScopeMap()` method as when the namespace keyword …
> No support for namespace operator used in type declarations

- package.xml
- src/Tokenizers/PHP.php
- src/Util/Tokens.php
- tests/Core/Tokenizer/UndoNamespacedNameSingleTokenTest.inc
- tests/Core/Tokenizer/UndoNamespacedNameSingleTokenTest.php
As per the proposal in #3041.
This effectively "undoes" the new PHP 8.0 tokenization of identifier names for PHPCS 3.x.
Includes extensive unit tests to ensure the correct re-tokenization as well as that the rest of the tokenization is not adversely affected by this change.
Includes preventing `function ...` within a group use statement from breaking the retokenization.
Includes fixing the nullable tokenization when combined with any of the new PHP 8 identifier name tokens.
Fixes #3041 for PHPCS 3.x
> PHP 8.0 | "undo" namespaced names as single token

- src/Tokenizers/PHP.php
Noticed (while working on something else) there were some typical scope closers missing from the array.
> Tokenizer/PHP: add missing scope closers

- src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc.fixed
> Ignore tokens that belong to array element declaration

- src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.php
> Do not attempt to fix ArrayDeclaration.SpaceBeforeComma if there is a comment in between

- src/Standards/Generic/Sniffs/Arrays/ArrayIndentSniff.php
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.inc.fixed
- src/Standards/Generic/Tests/Arrays/ArrayIndentUnitTest.php
> Ignore the previous element's T_COMMA when looking up the beginning of the previous expression

- .travis.yml
Further iteration after #3067.
This commit does a couple of things:
1. It adds a new build against PHP 7.4 which runs just and only the PEAR package file validation and the XML related checks.
That build doesn't need to do a `composer install` and, as it has it's own script, will show just the output of those checks.
2. It adds a separate `script` section to the two builds being run with custom PHP `ini` files (and moves those down in the matrix).
The end result of this is:
* We can get rid of all the conditions in the `script` section.
* Builds will show much cleaner output, so it is easier to find out what went wrong.
For the "custom builds", the Travis script now has a separate "name" for these, so they can still be easily identified for what they are, without the environment variables …
> Travis: further tweaks for cleaner output

- src/Standards/Squiz/Sniffs/Strings/ConcatenationSpacingSniff.php
This can happen when PHPCS runs on a file that is currently being worked on, but not yet completed. The file might end with a dot. We can not assume there are always 2 more tokens after a dot.
> Undefined offset in Squiz.Strings.ConcatenationSpacing during live coding

- src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php
… a bracket
While live coding, there might not only be an incomplete `if ():` at the end of a file, it might as well be an incomplete `if () {`. The most minimal example I found is `<?php if ( 1 ) { break;`. The auto-fix currently turns this into `<?php if ( 1 ) { { { { { { { { { { { { { { { { { { { { { { { { { { break;}}}}}}}}}}}}}}}}}}}}}}}}}`. 😲
> Incorrect auto-fixing in Generic.ControlStructures.InlineControlStructure during live coding

- .travis.yml
Ok, don't ask me why as I'm not 100% sure myself, but removing the file name from the PHPUnit command fixes the issue.
The `phpunit.xml.dist` configuration already has the file set up as the one to be scanned for tests anyway.
Tested and found working on PHPUnit `8.1.5`, `8.4.2`, `8.5.8`, `9.0.2`, `9.1.2`, `9.1.5`, `9.2.6, `9.3.10` (versions I had around on my system anyway).
Also verified the Travis builds for my branch build and all builds now show 567 tests.
Fixes #3120
> PHPCS 4.x | Tests: fix incomplete test suite runs

- .travis.yml
Sister-PR to PRs #3067 and #3073 for the PHPCS 4.x branch.
Basically does the same thing:
1. Skip the "normal" build checks for the PHPStan build and just and only run PHPStan.
2. Add a new build against PHP 7.4 which runs just and only the XML related checks.
That build doesn't need to do a `composer install` and, as it has it's own script, will show just the output of those checks.
3. Add a separate `script` section to the build being run with custom a PHP `ini` file (and moves those down in the matrix).
For the "custom builds", the Travis script now has a separate "name" for these, so they can still be easily identified for what they are, without the environment variables (which is what used to show).
> PHPCS 4.x | Travis: tweaks for cleaner output

- tests/AllTests.php
- tests/bootstrap.php
The global `$PHP_CODESNIFFER_PEAR` variable is used by the `Core` test and those test don't necessarily need to use the generic `AllTests` file as an entry point.
They can also be run using `phpunit ./tests/Core/AllTests.php`.
In that case, however, the `$PHP_CODESNIFFER_PEAR` variable is not defined leading to `Undefined index: PHP_CODESNIFFER_PEAR` errors.
By setting the global in the bootstrap, which is always loaded, this is avoided.
> Tests: stabilize an expected global

- autoload.php
Since PHP 7.4 get_declared_classes() does not guarantee any order. That
implies that parent classes aren't the first any more, rendering the
array_reverse() technique futile for the loop & break code that follows.
So, additionally, let's try to reduce the list of candidates by removing all
the classes known to be "parents". That way, at the end, only the "main"
class just included with remain.
Source:
https://raw.githubusercontent.com/php/php-src/PHP-7.4/UPGRADING
Text:
Previously get_declared_classes() always returned parent classes before
child classes. This is no longer the case. No particular order is guaranteed
for the get_declared_classes() return value.
----
Part of the move to phpcs3 we were getting some [strange errors with phpunit, only reproducible with …
> Fix PHP 7.4 regression, changed behavior of get_declared_classes()

- src/Tokenizers/Tokenizer.php
A very recent change in PHP 8.0 changes the possible return values of the `substr()` function from:
> Pre-PHP 8:
> Returns the extracted part of string; or FALSE on failure, or an empty string.
> PHP 8-RC1:
> Returns the extracted part of string; or an empty string.
This is an insidious change as basically all code (strict) checking the return value of `substr()` against `false` will now be broken.
Checking the return value with `empty()` will fix this in a cross-version compatible manner as it allows for both `false` as well as an empty string being returned.
This change broke the ignore annotations as implemented in PHPCS.
The existing unit tests for the ignore annotations cover this change.
Includes removing some unnecessary, duplicate function calls to `substr()`.
Ref: …
> Ignore annotations are broken on PHP 8.0

- src/Standards/PSR12/Tests/Operators/OperatorSpacingUnitTest.inc
- src/Standards/PSR12/Tests/Operators/OperatorSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
A plus/minus directly after the arrow of an arrow function, will always be a unary plus/minus and should therefore be ignored by these sniffs.
Includes two additional simplifications:
* `T_DOUBLE_ARROW` is already part of the `Tokens::$assignmentTokens` array, so doesn't need to be added separately.
* The cast tokens array was incomplete (missing `T_BINARY_CAST`) and can be replaced by the more complete `Tokens::$castTokens` array anyhow.
Fixes #3043
> Squiz/PSR12/OperatorSpacing: bug fix - unary plus/minus in arrow function return

- src/Files/File.php
This prevents code passed via `STDIN` from not being scanned because `STDIN` is not part of an include/exclude pattern.
I've made the same adjustment to both the `File::process()`, as well as the `File::addMessage()` method.
Note: using `trim()` to remove potential quotes around `STDIN` which are sometimes passed by IDEs. (based on previous experiences with sniffs checking file names).
Also note that the changes look more extensive than they really are due to the indentation change. Looking at the files while ignoring whitespace changes will show the real diff (4 lines).
Fixes #3107
> Bug fix: don't apply include/exclude patterns to STDIN

- src/Standards/PEAR/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
Close https://github.com/squizlabs/PHP_CodeSniffer/issues/2077
> [PEAR.Commenting.FunctionComment] Add option to disable the check for protected/private function

- README.md
PSR-2 is deprecated, they advice to use PSR-12 from now onwards.
> PSR-2 is officially deprecated, use PSR-12

- src/Util/Cache.php
While debugging #2992, I noticed that `.bak` files were being used for the "PHPCS native file hash".
As non-php files in the PHPCS directories have no effect on the actual run output, we may as well skip them from being part of the hash.
> Result caching: minor optimization tweak

- package.xml
- src/Files/File.php
- src/Tokenizers/PHP.php
- src/Util/Tokens.php
- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/File/GetMethodPropertiesTest.inc
- tests/Core/File/GetMethodPropertiesTest.php
- tests/Core/Tokenizer/BackfillFnTokenTest.inc
- tests/Core/Tokenizer/BackfillFnTokenTest.php
- tests/Core/Tokenizer/BitwiseOrTest.inc
- tests/Core/Tokenizer/BitwiseOrTest.php
- tests/Core/Tokenizer/UndoNamespacedNameSingleTokenTest.php
Implements support for PHP 8.0 union types in the PHP tokenizer and the `File::getMethodParameters()`, `File::getMethodProperties()` and the `File::getMemberProperties()` methods.
Note: Individual sniffs which examine the parameter/return/property type returned by those methods will have to implement support for union types by using `explode('|', ltrim($type, '?'))` on the type returned by these methods to get to the individual types or walk the tokens from the start of the type to the end of the type.
Ref: https://wiki.php.net/rfc/union_types_v2
Implementation as discussed in #2968. Partially fixes #2968.
... which will indicate the `|` character in PHP 8.0 union types.
This adds a new block of logic to the `PHP::processAdditional()` method which changes the token code and type of …
> PHP 8.0 | Support union types in PHP Tokenizer and File class utility methods

- src/Files/File.php
- src/Standards/Generic/Sniffs/PHP/LowerCaseTypeSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.php
With union types, even non-class return types may consist of multiple tokens, so having access to the stackPtr for the exact end of the return type becomes relevant for sniffs which include fixers.
This commit adds a `return_type_end_token` index key to the array return value of the `File::getMethodProperties()` method.
... to verify and safeguard that spacing within a type cast is not touched by the sniff.
Move the `$phpTypes` array to a property and add the new types introduced in PHP 8.0 to it.
Extract duplicate code out to a separate method and call the method instead.
Allow for union types, as introduced in PHP 8.0, in return and parameter type declarations.
PHP 7.4 introduced typed properties, but this sniff did not examine those yet. …
> PHP 7.4/8.0 | Generic/LowerCaseType: add support for union types and typed properties

- src/Files/File.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
PHP 8 introduces constructor property promotion.
This commit adds support for constructor property promotion to the `File::getMethodParameters()` method.
This change introduces two new keys - `property_visibility` and `visibility_token` - to the return array which will only be included if constructor property promotion is detected.
The method does not check whether property promotion is _valid_ in the function/method in which it is used. That is not the concern of this method.
Ref: https://wiki.php.net/rfc/constructor_promotion
Implementation as discussed in #2968. Partially fixes #2968.
> PHP 8.0 | File::getMethodParameters(): add support for PHP 8 constructor property promotion

- .gitattributes
Commit 5c40919e9cbc32db69e7e31843c2d19a038acd65 removed a little too much when ported to the 4.x branch, as there is still a committed `testingConfig.ini` file which is used by the test runs and is not needed for end-users.
> PHPCS 4.x | .gitattributes: minor tweak

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/ShortArrayTest.inc
- tests/Core/Tokenizer/ShortArrayTest.php
As of PHP 8, interpolated text strings can be dereferenced, however, the square brackets are incorrectly tokenized as _short array_ brackets instead of as "normal" square brackets.
Fixed by adding the `T_DOUBLE_QUOTED_STRING` token to the allowed tokens for leaving the brackets alone in the PHP Tokenizer class.
Ref: https://wiki.php.net/rfc/variable_syntax_tweaks#interpolated_and_non-interpolated_strings
> PHP 8.0 | Tokenizer/PHP: support dereferencing of text strings with interpolated variables

- src/Standards/PSR2/Sniffs/Namespaces/NamespaceDeclarationSniff.php
- src/Standards/PSR2/Tests/Namespaces/NamespaceDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Namespaces/NamespaceDeclarationUnitTest.inc.fixed
When the `namespace` keyword was used as an operator, the sniff would incorrectly throw an error too.
Fixed now.
> PSR2.Namespace.NamespaceDeclaration false positive on namespace operator

- package.xml
- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/GotoLabelTest.inc
- tests/Core/Tokenizer/GotoLabelTest.php
The logic could get confused when `goto` would be used in a mixed PHP/HTML file.
Includes adding a limited set of unit tests for the `T_GOTO_LABEL` tokenization.
> Incorrect tokenization of GOTO statements in mixed PHP/HTML files

- package.xml
- src/Tokenizers/PHP.php
- src/Util/Tokens.php
- tests/Core/Tokenizer/NamedFunctionCallArgumentsTest.inc
- tests/Core/Tokenizer/NamedFunctionCallArgumentsTest.php
PHP 8.0 introduces named function call parameters:
```php
array_fill(start_index: 0, num: 100, value: 50);
// Using reserved keywords as names is allowed.
array_foobar(array: $array, switch: $switch, class: $class);
```
Ref: https://wiki.php.net/rfc/named_params
This PR adds support to PHPCS for named function call arguments by adding a special custom token `T_PARAM_NAME` and tokenizing the _labels_ in function calls using named arguments to that new token, as per the proposal in #3159.
I also ensured that the colon _after_ a parameter label is always tokenized as `T_COLON`.
Includes some minor efficiency fixes to the code which deals with the colon vs inline else determination as there is no need to run the "is this a return type" or the "is this a `case` statement" checks if it has …
> PHP 8.0 | Add support for named function call arguments

- src/Standards/Squiz/Sniffs/WhiteSpace/ScopeKeywordSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.php
This adds some additional safeguards to the sniff to prevent it from triggering when `static` is used in a return type declaration, as allowed since PHP 8.0.
Fixes #3188
> PHP 8.0 | Squiz/ScopeKeywordSpacing: fix false positive on static as return type

- src/Standards/Generic/Sniffs/CodeAnalysis/UnusedFunctionParameterSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/UnusedFunctionParameterUnitTest.inc
Sometimes you have to implement interface but not all required parameters are needed to use. For example in symfony/console.
```php
public function execute(InputInterface $input, OutputInterface $output): int
{
$output->writeln('Do something without using of $input');
return 0;
}
```
> Generic.CodeAnalysis.UnusedFunctionParameter: Add possibility to specify excludes

- src/Standards/Generic/Sniffs/WhiteSpace/ArbitraryParenthesesSpacingSniff.php
As `declare()` is recognized as a parentheses owner, there is no need for it to be listed in the "additional tokens indicating that parenthesis are not arbitrary" list.
Tested via an existing test: https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.inc#L29
> Generic/ArbitraryParenthesesSpacing: minor clean up

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
https://github.com/squizlabs/PHP_CodeSniffer/issues/2770 and numerous previous closed issues have requested supporting `{@inheritdoc}` for function comments. This PR adds an optional property to the sniff that skips erroring on missing `@param`, `@return`, or `@throws` if the whole contents of the docblock are exactly `{@inheritdoc}` (case-insensitive).
Example usage:
```
<rule ref="Squiz.Commenting.FunctionComment">                               
<properties>
<property name="skipIfInheritdoc" value="true"/>
</properties>
</rule>
```
> Add a property to Squiz.Commenting.FunctionComment to skip processing for {@inheritdoc} (issue #2770)

- src/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php
I was running into this while working on another sniff. One trivial example I found to demonstrate the bug is `<?php return array_map(`. This can happen when PHPCS runs on a file I'm currently typing in, but the file is not complete yet.
~~I believe it's safe to assume the `parenthesis_closer` array key only exists on T_OPEN_PARENTHESIS tokens, and the `bracket_closer` key only on T_OPEN_CURLY_BRACKET tokens. I had a quick look at the tokenizer and I believe this is indeed the case. But I might be wrong.~~
Sorry for not providing a test. I would love to, but I'm not familiar enough with the test setup here.
> Fix possible index error in NonExecutableCodeSniff

- src/Files/File.php
- src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.php
- src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.1.js.fixed
This fix the issue reported here: https://github.com/squizlabs/PHP_CodeSniffer/issues/2800
I added tests.
Edit: Also close #3192
> [SwitchDeclarationSniff] Handle nested switch

- src/Standards/Squiz/Sniffs/Debug/JSLintSniff.php
The `$name` passed to `Config::getExecutablePath()` appears to be incorrect which would result in a duplicate `jslint jslint` command.
> JSLint: bug fix

- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.php
This verifies that named function call arguments do not affect the functioning of the sniff as-is.
> Generic/FunctionCallArgumentSpacing: add test with named function call args

- src/Tokenizers/PHP.php
Prevents some unnecessary token changes of the type `token # changed from T_STRING to T_STRING`.
> Tokenizer/PHP: minor tweak

- src/Util/Tokens.php
The values of the PHPCS native token types are normally prefixed with `PHPCS_`. This wasn't the case for the three most recent additions, `T_FN_ARROW` as introduced in PHPCS 3.5.3, `T_TYPE_UNION` and `T_PARAM_NAME` as will be introduced in PHPCS 3.6.0 (not yet released).
While the change to the value for `T_FN_ARROW` could be considered a breaking change, it is exceedingly rare for a sniff to use the _value_ of a token constant, so IMO opinion, this is a safe change to make.
As for the other two tokens, as they have not been in a release yet, they can be safely updated no matter what.
> Tokens: fix up some PHPCS native token values

- src/Reports/Notifysend.php
- src/Standards/Generic/Sniffs/Debug/CSSLintSniff.php
- src/Standards/Generic/Sniffs/Debug/ClosureLinterSniff.php
- src/Standards/Generic/Sniffs/Debug/ESLintSniff.php
- src/Standards/Generic/Sniffs/Debug/JSHintSniff.php
- src/Standards/Generic/Sniffs/PHP/SyntaxSniff.php
- src/Standards/Squiz/Sniffs/Debug/JSLintSniff.php
- src/Standards/Squiz/Sniffs/Debug/JavaScriptLintSniff.php
- src/Standards/Zend/Sniffs/Debug/CodeAnalyzerSniff.php
- src/Util/Common.php
The `escapeshellcmd()` function apparently does not escape spaces within a path on Windows which can result in broken functionality.
While the sniffs and report affected by this are apparently not used that much based on the lack of bug reports, fixing it still seemed like the _right thing to do_.
Noticed while running the unit tests on a fresh install on Windows 10.
At some point over the past years, Node has apparently changed their default install directory on Windows and the order in which they register their paths to the Windows system `PATH`.
This means that `where csslint` may result in a `$cmd` path like `C:\Program Files\nodejs\csslint.cmd`, which would be escaped to `C:^\Program Files^\nodejs^\csslint.cmd` on Windows, which in turn results in a `'C:\Program' is not recognized as …
> Windows: fix escaping of external commands

- tests/Core/Tokenizer/BackfillFnTokenTest.php
* Simplify the arrow function testing by using a helper function to check the token positions.
* Fix incorrect parameter order of the `$expected` vs `$result` parameters in `assertSame()`.
While when the test passes, this makes no difference, it does make a difference in the error output when a test fails.
This addresses the same issues as in the previous commit for those functions which need custom "error" messages or have a shared scope closer, resulting in the `opener` for the `scope_closer` pointing to another construct
* Remove duplicate calculations of the scope opener/closer positions.
* Fix incorrect parameter order of the `$expected` vs `$result` parameters in `assertSame()`.
While when the test passes, this makes no difference, it does make a difference in the error output when …
> Arrow function tests: simplify and improve the tests

- tests/Core/Tokenizer/BackfillFnTokenTest.php
Follow-up on #3215 which made these redundant, but didn't remove them.
> Arrow function tests: remove some stray function calls

- package.xml
- src/Tokenizers/PHP.php
- src/Util/Tokens.php
- tests/Core/Tokenizer/BackfillFnTokenTest.inc
- tests/Core/Tokenizer/BackfillFnTokenTest.php
- tests/Core/Tokenizer/BackfillMatchTokenTest.inc
- tests/Core/Tokenizer/BackfillMatchTokenTest.php
- tests/Core/Tokenizer/DefaultKeywordTest.inc
- tests/Core/Tokenizer/DefaultKeywordTest.php
- tests/Core/Tokenizer/DoubleArrowTest.inc
- tests/Core/Tokenizer/DoubleArrowTest.php
PHP 8.0 introduces a new type of control structure: match expressions.
> A match expression is similar to a `switch` control structure but with safer semantics and the ability to return values.
Ref: https://wiki.php.net/rfc/match_expression_v2
This PR adds support for PHP 8.0 match expressions to PHPCS by backfilling the token for older PHP versions.
It also retokenizes the `default` keyword when used in match expressions to `T_MATCH_DEFAULT` and the double arrow separating the "case" from the return expression to `T_MATCH_ARROW`.
Note: if this PR is accepted as is, then, in contrast to the `switch` control structure, "cases" (including a potential `default` case)  in match expressions will not be considered scope owners and will not have any `scope_*` array indexes set.
The match …
> PHP 8 | Tokenizer/PHP: add support for match expressions

- src/Standards/Generic/Sniffs/CodeAnalysis/AssignmentInConditionSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/AssignmentInConditionUnitTest.inc
- src/Standards/Generic/Tests/CodeAnalysis/AssignmentInConditionUnitTest.php
Allows the sniff to also check for assignments in condition in the condition part of a match expression.
> PHP 8.0 | Generic/AssignmentInCondition: include match expressions

- src/Standards/Generic/Sniffs/CodeAnalysis/EmptyStatementSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/EmptyStatementUnitTest.inc
- src/Standards/Generic/Tests/CodeAnalysis/EmptyStatementUnitTest.php
Allows the sniff to also check for empty match expressions.
> PHP 8.0 | Generic/EmptyStatement: include match expressions

- src/Standards/Generic/Sniffs/PHP/LowerCaseKeywordSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.php
This adds the PHP 8.0 `match` keyword to the list handled by this sniff, as well as the `default` keyword when used in a match control structure.
> PHP 8.0 | Generic/LowerCaseKeyword: add match to keyword list

- src/Tokenizers/PHP.php
Oops.. still missed that one, even though I'd run the tests on various PHP versions locally so many times.... luckily CI caught it anyhow with one of the sniffs.
> Tokenizer/PHP: minor bugfix for match tokenization

- src/Standards/Squiz/Sniffs/Commenting/PostStatementCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/PostStatementCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/PostStatementCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/PostStatementCommentUnitTest.php
Allows the sniff to make an exception for comments within the condition of a match expression, just like it does for other control structures.
> PHP 8.0 | Squiz/PostStatementComment: include match expressions

- src/Standards/Squiz/Sniffs/ControlStructures/LowercaseDeclarationSniff.php
- src/Standards/Squiz/Tests/ControlStructures/LowercaseDeclarationUnitTest.inc
- src/Standards/Squiz/Tests/ControlStructures/LowercaseDeclarationUnitTest.inc.fixed
- src/Standards/Squiz/Tests/ControlStructures/LowercaseDeclarationUnitTest.php
This adds the PHP 8.0 `match` keyword to the list handled by this sniff.
> PHP 8.0 | Squiz/LowercaseDeclaration: add match to keyword list

- src/Standards/Squiz/Sniffs/Formatting/OperatorBracketSniff.php
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.inc
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.php
Make the same exception for match expressions as was already in place for switch control structures.
While at the same time safeguarding that the sniff will still apply itself correctly for code within a `match` expression, whether in a "case condition" or when in the value.
> PHP 8.0 | Squiz/OperatorBracket: make exception for match expressions

- src/Standards/Squiz/Sniffs/Objects/ObjectInstantiationSniff.php
- src/Standards/Squiz/Tests/Objects/ObjectInstantiationUnitTest.inc
This change ensures that when `new Class` is returned by a match control structure or an arrow function, the sniff will not throw a false positive.
> PHP 8.0 | Squiz/ObjectInstantiation: prevent false positives on match/fn expressions

- src/Standards/PSR12/Sniffs/ControlStructures/BooleanOperatorPlacementSniff.php
- src/Standards/PSR12/Tests/ControlStructures/BooleanOperatorPlacementUnitTest.inc
- src/Standards/PSR12/Tests/ControlStructures/BooleanOperatorPlacementUnitTest.inc.fixed
- src/Standards/PSR12/Tests/ControlStructures/BooleanOperatorPlacementUnitTest.php
Allows the sniff to also check the placement of boolean operators in match expressions.
> PHP 8.0 | PSR12/BooleanOperatorPlacement: include match expressions

- src/Standards/Squiz/Sniffs/ControlStructures/ControlSignatureSniff.php
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc.fixed
- src/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.php
This adds support for checking the signature of `match` expressions to this sniff.
> PHP 8.0 | Squiz/ControlSignature: check signature of match expressions

- src/Standards/Squiz/Sniffs/PHP/DisallowMultipleAssignmentsSniff.php
- src/Standards/Squiz/Tests/PHP/DisallowMultipleAssignmentsUnitTest.inc
- src/Standards/Squiz/Tests/PHP/DisallowMultipleAssignmentsUnitTest.php
The `Squiz.PHP.DisallowMultipleAssignments` sniff differentiates in the error code between "normal" assignments which aren't the only thing on a line and assignments in control structure conditions.
This adds `match` to the list of control structures, so it gets the correct error code.
> PHP 8.0 | Squiz/DisallowMultipleAssignments: correct errorcode for assignment in match expression

- src/Standards/Squiz/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ControlStructureSpacingUnitTest.php
This adds support for checking the spacing for `match` expressions to the Squiz sniff.
> PHP 8.0 | Squiz/ControlStructureSpacing: check match expressions

- src/Ruleset.php
The `Util\Standards::getInstalledStandardPath()` method returns either a string or `null`, however the `strpos()` method which is used in both the `Util\Common::isPharFile()` method, as well as in the follow-on condition, only accepts a `string` as `$haystack`.
As of PHP 8.1, this will generate a deprecation notice `strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated`.
Discovered while testing an external standard against PHPCS `master` on PHP 8.1.
Fixed now.
> PHP 8.1: fix deprecation notice

- .github/workflows/phpstan.yml
- .github/workflows/test.yml
- .github/workflows/validate.yml
No need to install via Composer, the `setup-php` action can make PHPStan globally available.
There is no need to remove the config file and have all settings on the command-line as PHPUnit offers a `--no-configuration` option to ignore the config file.
Enabling that simplifies the action steps a little and isolates the customization for PHP 8.1 to PHP 8.1.
The cs2pr tool will allow to display the results from an action run in checkstyle format in-line in the PR code view, which should improve usability of the workflow results.
As the CS run is run in every test run in the matrix, passing the results on to CS2PR would result in violations being displayed multiple times, so using conditions to only pass the CS violations on to the PR for one of the runs.
Ref: …
> GH Actions: various tweaks to the scripts

- src/Standards/PEAR/Sniffs/Functions/FunctionCallSignatureSniff.php
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.inc
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.php
- src/Standards/PSR2/Sniffs/Methods/FunctionCallSignatureSniff.php
- src/Standards/PSR2/Tests/Methods/FunctionCallSignatureUnitTest.inc
- src/Standards/PSR2/Tests/Methods/FunctionCallSignatureUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Methods/FunctionCallSignatureUnitTest.php
The `File::findEndOfStatement()` method regards a `T_COLON` as the end of a statement, while for function call arguments using named parameters, the colon is part of the parameter name declaration and should be disregarded when determining the end of the statement.
Fixed now.
Includes unit tests for both affected sniffs.
>  PHP 8.0 | Pear+PSR2/FunctionCallSignature: support named parameters

- src/Fixer.php
The `Fixer::generateDiff()` method calls the `shell_exec()` method to retrieve the `diff` between two files.
In the unit tests, this is used to compare the expected content in a `.fixed` file with the generate fixed file contents.
If the expected content matches the generated content, the diff command will produce no output and `shell_exec()` will return `null`.
Ref: https://www.php.net/manual/en/function.shell-exec.php
This result is subsequently passed to `explode()` as the second parameter, but `explode()` only excepts strings as the second parameter.
Ref: https://www.php.net/manual/en/function.explode
As of PHP 8.1, this will generate a deprecation notice `explode(): Passing null to parameter #2 ($string) of type string is deprecated`.
Discovered while testing an external standard …
> PHP 8.1: fix deprecation notice [2]

- .github/workflows/test.yml
Not all PHPUnit dependencies allow for PHP 8.1/nightly yet, so run `composer install` with the `--ignore-platform-reqs` options to allow to run the tests anyway.
> PHPCS 4.x | GH Actions: fix test workflow for PHP nightly

- src/Standards/Generic/Sniffs/PHP/NoSilencedErrorsSniff.php
- src/Standards/Generic/Tests/PHP/NoSilencedErrorsUnitTest.inc
- src/Standards/Generic/Tests/PHP/NoSilencedErrorsUnitTest.php
... to confirm that the code snippet in the error message will be correct (set the `$contextLength` to a higher value to confirm).
> PHP 8.0 | Generic/NoSilencedErrors: add tests with named function call parameters

- src/Standards/PEAR/Tests/WhiteSpace/ObjectOperatorIndentUnitTest.inc
- src/Standards/PEAR/Tests/WhiteSpace/ObjectOperatorIndentUnitTest.inc.fixed
- src/Standards/PEAR/Tests/WhiteSpace/ObjectOperatorIndentUnitTest.php
... to confirm that the sniff does not break on these.
> PHP 8.0 | PEAR/ObjectOperatorIndent: add tests with named function call parameters

- src/Standards/Squiz/Sniffs/Formatting/OperatorBracketSniff.php
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.inc
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.php
... to confirm that the sniff does not break on these.
The new test was giving _three_ instead of _two_ errors on line 194 for this snippet `$padding * -1 + 3`, with the errors being thrown on the `*`, `-` and the `+` operators.
The `-` operator, however, is a unary operator and should not trigger this error.
Fixed now.
> Squiz.Formatting.OperatorBracket duplicate error messages for unary minus

- src/Standards/Squiz/Sniffs/WhiteSpace/ScopeKeywordSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ScopeKeywordSpacingUnitTest.php
Prevent the sniff from ignoring the spacing after the scope keyword in case of PHP 8.0 constructor property promotion.
As it was, the sniff would presume "normal" property syntax, which meant that in the case of constructor property promotion in a multi-line constructor declaration, the sniff would look for a semicolon to end the statement and bow out when the semicolon wasn't found.
By explicitly checking for constructor property promotion and skipping the above mentioned check in that case, we ensure that scope keywords in constructors are still handled correctly.
Includes tests.
> PHP 8.0 | Squiz/ScopeKeywordSpacing: add support for constructor property promotion

- src/Standards/PSR12/Sniffs/ControlStructures/ControlStructureSpacingSniff.php
- src/Standards/PSR12/Tests/ControlStructures/ControlStructureSpacingUnitTest.inc
- src/Standards/PSR12/Tests/ControlStructures/ControlStructureSpacingUnitTest.inc.fixed
- src/Standards/PSR12/Tests/ControlStructures/ControlStructureSpacingUnitTest.php
- src/Standards/PSR2/Sniffs/ControlStructures/ControlStructureSpacingSniff.php
- src/Standards/PSR2/Tests/ControlStructures/ControlStructureSpacingUnitTest.inc
- src/Standards/PSR2/Tests/ControlStructures/ControlStructureSpacingUnitTest.inc.fixed
- src/Standards/PSR2/Tests/ControlStructures/ControlStructureSpacingUnitTest.php
This adds support for checking the spacing inside single line conditions for `match` expressions to the PSR2 sniff and by extension to the PSR12 sniff, as well as explicitly for multiline conditions to the PSR12 sniff.
> PHP 8.0 | PSR2/PSR12/ControlStructureSpacing: check match expressions

- src/Standards/PSR12/Tests/Operators/OperatorSpacingUnitTest.inc
- src/Standards/PSR12/Tests/Operators/OperatorSpacingUnitTest.inc.fixed
- src/Tokenizers/PHP.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/Tokenizer/BitwiseOrTest.inc
- tests/Core/Tokenizer/BitwiseOrTest.php
In `PHP::processAdditional()`, in the part which retokenizes `T_BITWISE_OR` tokens to `T_TYPE_UNION`, the code already took reference operators and spread operators between the type declaration and the variable into account, but would also increment the current position in the loop, while this is already done in the `for()`. My bad.
Fixed now.
Includes additional unit tests for all relevant functions within the chain, as well as for the sniff for which the issue was reported.
Fixes #3267
> PHP 8.0 | Tokenizer/PHP: bugfix for union type operator tokenization

- src/Standards/Generic/Sniffs/CodeAnalysis/UnusedFunctionParameterSniff.php
- src/Standards/Generic/Tests/CodeAnalysis/UnusedFunctionParameterUnitTest.inc
When constructor property promotion is used, the properties declared in the class constructor should never be marked as unused by this sniff.
Includes tests.
Fixes #3269
> PHP 8.0 | Generic/UnusedFunctionParameter: add support for constructor property promotion

- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.php
The sniff already handles this correctly. This just adds some tests to confirm it and safeguard it for the future.
> PHP 8.0 | Generic/LowerCaseType: add tests with Constructor Property Promotion

- src/Standards/PEAR/Tests/Functions/ValidDefaultValueUnitTest.inc
- src/Standards/PEAR/Tests/Functions/ValidDefaultValueUnitTest.php
~~Properties declared using constructor property promotion, should be ignored for the purpose of determining whether an optional parameter is declared before a required one.~~
~~Includes tests.~~
The sniff already handles this correctly. This just adds some tests to confirm it and safeguard it for the future.
> PHP 8.0 | PEAR/ValidDefaultValue: add tests with constructor property promotion

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillMatchTokenTest.inc
- tests/Core/Tokenizer/BackfillMatchTokenTest.php
This PR contains two separate, small efficiency tweaks for the `match` expression retokenization.
1. The tokenizer was walking backwards in the `match` backfill, while it could have just used `$finalTokens[$lastNotEmptyToken]` to get the last non-empty token.
2. There was some redundancy in the tokens which were being checked for the token "before".
For tokens like, `T_CLASS` and `T_CONST`, the next token after the `match` keyword could never be an open parenthesis, so they would already be marked as "not match".
Includes additional tests.
Additionally, when I initially started the work on backfilling `match` expressions, the nullsafe object operator had not yet been backfilled, so there was not test covering that case. Added now just to be on the safe side.
Note: all extra tests would …
> PHP 8.0 | Tokenizer/PHP: efficiency tweaks

- package.xml
- src/Files/File.php
- src/Tokenizers/PHP.php
- src/Tokenizers/Tokenizer.php
- src/Util/Tokens.php
- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
- tests/Core/Tokenizer/AttributesTest.inc
- tests/Core/Tokenizer/AttributesTest.php
I tried to add PHP8 attributes parsing functionalities in PHP tokenizer.
Hope this could help completing PHP8 support on this great project.
PS: Since its my first PR here, please indicate me if there's something wrong with it. Thanks
> Tokenizer: add support for PHP8 attributes

- tests/Core/File/FindEndOfStatementTest.php
- tests/Core/File/FindStartOfStatementTest.php
- tests/Core/Tokenizer/BackfillNumericSeparatorTest.php
Just fixes some spelling in some comments. Nothing to test so no tests added.
> Spelling - seperator should be separator

- src/Standards/PEAR/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.php
- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.php
This would close https://github.com/squizlabs/PHP_CodeSniffer/issues/2924
Report 
```
class Bar {
/**
* The PHP5 constructor
*
* @return
*/
public function __construct() {
}
}
```
as an error.
And allow to override the list of specialMethod, in order to add others or to disallow this special behaviour by passing an empty array.
> [PEAR\Commenting\FunctionComment] Improve check for special method and add an option

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/AttributesTest.inc
- tests/Core/Tokenizer/AttributesTest.php
As per title, this fixes the bug described in #3294.
Only if the PHP version is less than 8.0 AND the attribute closer token is not found (not being on the same line or placed after a "?>" token which is interpreted as a php close tag for example), the remainder of the file will be re-tokenized and the attribute closed is searched in the new token stream.
If found the new token stream is injected into the token array and parsing continues, otherwise the re-tokenized stream will be ignored.
> Fix bug in attributes tokenization on PHP < 8.0 (#3294)

- src/Runner.php
> Continue to the next file when an ignored file is found when running checks in parallel.

- src/Files/File.php
- src/Tokenizers/Tokenizer.php
- tests/Core/ErrorSuppressionTest.php
Tokenizer: support hash comment for ignore annotations
Until now, for the PHPCS native ignore annotations, only `//` slash or `/* */` star-style comments were supported.
This adds support for PHPCS native ignore annotations using `#` hash-style comments.
Includes unit tests and syncing of the `ltrim()` used in `File::process()` with the `ltrim()` used in `Tokenizer::createPositionMap()`.
> Tokenizer: support hash comment for ignore annotations

- src/Reports/Code.php
- src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php
- src/Tokenizers/Tokenizer.php
Commit d4f33dbf45aa5bb78e077b0e73306746c8bd98cf changed the output from STDOUT to STDERR using `Common::printStatusMessage()` instead of plain `echo`'s.
In the mean time, some new `echo`'s have slipped in. This fixes those up.
> PHPCS 4.x | Fix inconsistent output

- src/Tokenizers/Tokenizer.php
- tests/Core/Tokenizer/UseParenthesisOwnerTest.inc
- tests/Core/Tokenizer/UseParenthesisOwnerTest.php
Commit 08824f327ce5e20d7528c5e838dd7fade3dcd11c (issue #2593) added support for `T_USE` tokens for closures being parentheses owners.
However, the net effect was that *every* `T_USE` token - including import/trait use statement `T_USE` tokens, would have the `parenthesis_owner`, `parenthesis_opener` and `parenthesis_closer` indexes set.
For closure `use` statements, those were set correctly.
However, for import/trait `use` statements, the `parenthesis_owner` would point to the `T_USE` keyword which doesn't have parentheses and the `parenthesis_opener` and `parenthesis_closer`  indexes would be `null` in most cases, but they would still be set.
Also, in some cases, the `parenthesis_opener` and `parenthesis_closer`  indexes for import/trait `use` statements would incorrectly be set if to …
> PHPCS 4.x | Tokenizer: fix stray "parenthesis_..." indexes being set for non-closure use

- package.xml
- src/Standards/Generic/Sniffs/VersionControl/GitMergeConflictSniff.php
- src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.7.inc
- src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.php
- src/Standards/Squiz/Sniffs/WhiteSpace/SuperfluousWhitespaceSniff.php
I can't think of any good reason why "template files", which typically use the short open echo tag, should be excluded from the check done by this sniff.
> Generic/GitMergeConflict: check files using only short open echo tag

- package.xml
- src/Standards/Generic/Sniffs/WhiteSpace/DisallowSpaceIndentSniff.php
- src/Standards/Generic/Tests/WhiteSpace/DisallowSpaceIndentUnitTest.3.inc
- src/Standards/Generic/Tests/WhiteSpace/DisallowSpaceIndentUnitTest.3.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/DisallowSpaceIndentUnitTest.php
I can't think of any good reason why "template files", which typically use the short open echo tag, should be excluded from the check done by this sniff. Currently spacing rules are basically applied inconsistently, based on what PHP tag is used.
> Generic/DisallowSpaceIndent: check files using only short open echo tag

- src/Standards/Squiz/Sniffs/Commenting/BlockCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.php
The sniff has different behaviour when there is a PHP open tag before the block comment, however, this behaviour was not applied when the PHP short open echo tag was encountered.
> Squiz/BlockComment: also check for short open echo tag

- tests/Core/ErrorSuppressionTest.php
Follow up to https://github.com/squizlabs/PHP_CodeSniffer/pull/3071#issuecomment-828109667
This refactors all test methods in the `ErrorSuppresionTest` class to use data providers.
For each of these refactors, the following comment applies:
* Maintains the exact same existing tests, now using a data provider.
The data provider uses keys which allows for much more descriptive output when using the PHPUnit `--testdox` option, as well as for easier debugging if/when a test would fail.
* Orders the tests in logical groups in the data provider.
* Switches out `assertEquals()` (loose type comparison) for `assertSame()` (strict type comparison).
* Caches the `$config` and `$ruleset` for the test via static local variables to prevent the test run from becoming slower due to the change to the data …
> ErrorSuppressionTest: refactor to use data providers + bug fixes for the tests

- tests/Core/Tokenizer/NamedFunctionCallArgumentsTest.php
The error message would display the token code, which is not helfpul for a human, so changing it to the token `type`.
> NamedFunctionCallArgumentsTest: minor fixes

- src/Tokenizers/PHP.php
Interface and trait names should always be `T_STRING`.
> Ensure interface and trait names are always tokenized as T_STRING

- package.xml
- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/FinallyTest.inc
- tests/Core/Tokenizer/FinallyTest.php
Make the backfill for T_FINALLY a little more stable by preventing re-tokenizing non-keyword `finally` strings to `T_FINALLY`.
> Tokenizer/PHP: stabilize T_FINALLY backfill

- src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.php
As reported in #3352, the `PSR2.ControlStructures.SwitchDeclaration.BodyOnNextLineCASE` fixer could inadvertently remove trailing comments.
This commit improves on the fix which was put in place in response to #683, by making the detection of what should be considered the start of the body more precise:
* Any amount of trailing comments on the same line as the `case` will be ignored.
* Any type of comment will be taken into consideration, not just PHPCS annotations and `T_COMMENT` tokens.
* Comments _not_ on the same line as the `case` and non-empty tokens on the same line as the `case` will both be considered as the "start of the body".
As for the fixer. The "body starts on same line" fixer was already okay. The "empty lines between case and body" fixer, however, will now ignore anything …
> PSR2/SwitchDeclaration: various bug fixes

- src/Standards/Generic/Sniffs/Functions/OpeningFunctionBraceBsdAllmanSniff.php
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceBsdAllmanUnitTest.inc
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceBsdAllmanUnitTest.inc.fixed
- src/Standards/Generic/Tests/Functions/OpeningFunctionBraceBsdAllmanUnitTest.php
As reported in #3357, the `Generic.Functions.OpeningFunctionBraceBsdAllman` sniff would remove return types (and comments) when fixing code where blank lines existed between the end of the function declaration and the open brace.
This commit fixes that bug.
In the case of comments, the `BraceSpacing` error will no longer auto-fix as a dev should decide where the comment should go and/or whether it should be removed.
Fixes #3357
Previously #1931, #1938
> Generic/OpeningFunctionBraceBsdAllman: bug fix - prevent removing return types

- src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.1.inc
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.1.inc.fixed
- src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.php
Multi-catch and `finally` statements were not taken into account when determining the end of the statement within an inline control structure.
Fixed now.
Fixes #3345
> Generic/InlineControlStructure: bug fix for try/catch/finally

- licence.txt
As the BSD-3 licence has been adjusted github doesn't notice this is the BSD-3 licence, after these changes github will pick up the correct licence
> Normalise License file

- src/Standards/Generic/Sniffs/NamingConventions/ConstructorNameSniff.php
On PHP 8.1, passing `null` to `strtolower()` generates a `strtolower(): Passing null to parameter #1 ($string) of type string is deprecated` notice.
The `File::getDeclarationName()` will return `null` for anonymous classes, so we need an extra safeguard here.
This fix is covered by the existing unit tests and was exposed when running the tests on PHP 8.1 with `error_reporting` set to `E_ALL`. (see the GH actions script output for #3380)
> PHP 8.1: Generic/ConstructorName: fix deprecation notices

- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc.fixed
- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/DefaultKeywordTest.inc
- tests/Core/Tokenizer/DefaultKeywordTest.php
.. safeguarding the tokenizer fix which should prevent the issue as reported in #3326.
As per: #3326 (comment)
> After `PHP::tokenize()`, the `DEFAULT` is still tokenized as `T_DEFAULT`. This causes the `Tokenizer::recurseScopeMap()` to assign it as the `scope_opener` to the `;` semi-colon at the end of the constant declaration, with the class close curly brace being set as the `scope_closer`.
> In the `PHP::processAdditional()` method, the `DEFAULT` is subsequently retokenized to `T_STRING` as it is preceded by a `const` keyword, but that is too late.
>
> The `scope_opener` being set on the semi-colon is what is causing the errors to be displayed for the above code sample.
The commit fixes this by:
1. Abstracting the list of `T_STRING` contexts out to a class property.
2. Using the list …
> Tokenizer/PHP: fix tokenization of the default keyword

- src/Fixer.php
- src/Reports/Cbf.php
... to make the output slightly more readable.
> Fixer/Cbf: add missing new line in level >=2 debug output

- src/Files/File.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
This test demonstrates and documents the existing behaviour of the method when comments are encountered within a parameter declaration.
This commit adds handling of parameter attributes to the `File::getMethodParameters()` method as per option [2] discussed in issue #3298.
In practice this means that:
* [New] A new `attributes` index is introduced into the returned array which will hold a boolean value indicating whether attributes are attached to the parameter.
* [Unchanged] The `content` index in the returned array includes the textual representation of any attributes attached to a parameter.
* [Fixed] The `type_hint` and `type_hint_token` indexes will no longer be polluted (set incorrectly) with information belonging to the attribute(s) instead of to the type declaration.
Includes …
> PHP 8.0 | File::getMethodParameters(): bug fix for attributes leaking into typehint

- src/Standards/Generic/Tests/NamingConventions/InterfaceNameSuffixUnitTest.php
WIthout this fix, composer warning is appears...
```bash
Generating optimized autoload files
Class PHP_CodeSniffer\Standards\Generic\Tests\NamingConventions\InterfaceSuffixNameUnitTest located in ./vendor/squizlabs/php_codesniffer/src/Standards/Generic/Tests/NamingConventions/InterfaceNameSuffixUnitTest.php does not comply with psr-4 autoloading standard. Skipping.
```
```bash
[root@b1d0aac4f4d2 /var/www]$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key …
```
> Fix autoload issue

- src/Standards/PEAR/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.php
PHP 8.0+ attributes can be placed between a docblock and the function declaration it applies to.
The `PEAR.Commenting.FunctionComment` sniff - and by extension the `Squiz.Commenting.FunctionComment` sniff - did not yet take this into account.
This would result in a false positive `Missing doc comment for function ... ` error.
Resolving that error though, would result in a new `There must be no blank lines after the function comment` error, so the blank line check also needed to be fixed.
With the current fix, blank lines between the docblock and the function declaration are still not allowed, but non-blank lines between the two (i.e. lines containing attributes) will be ignored.
Only one "no blank lines between" error will be thrown per function declaration.
> PHP 8.0 | PEAR/FunctionComment: prevent false positives with attributes

- src/Standards/Squiz/Sniffs/Commenting/InlineCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/InlineCommentUnitTest.inc.fixed
PHP 8.0+ attributes can be placed between a docblock and the function/class declaration it applies to.
The `Squiz.Commenting.InlineComment` sniff did not yet take this into account when determining whether a comment was a docblock or an single line comment incorrectly using the docblock syntax.
This would result in false positive `Inline doc block comments are not allowed; use "/* Comment */" or "// Comment" instead` errors.
Fixed now.
> PHP 8.0 | Squiz/InlineComment: prevent false positives with attributes

- src/Standards/Squiz/Sniffs/Commenting/BlockCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc.fixed
PHP 8.0+ attributes can be placed between a docblock and the function/class declaration it applies to.
The `Squiz.Commenting.BlockComment` sniff did not yet take this into account when determining whether a comment was a docblock or an block comment incorrectly using the docblock syntax.
This would result in false positive `Block comments must be started with /*` errors.
Fixed now.
> PHP 8.0 | Squiz/BlockComment: prevent false positives with attributes

- src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc.fixed
PHP 8.0+ attributes can be placed between a docblock and the property declaration it applies to.
The `Squiz.Commenting.VariableComment` sniff did not yet take this into account.
This would result in a false positive `Missing member variable doc comment` error.
Fixed now.
> PHP 8.0 | PEAR/VariableComment: prevent false positives with attributes

- src/Standards/Squiz/Sniffs/Objects/ObjectInstantiationSniff.php
- src/Standards/Squiz/Tests/Objects/ObjectInstantiationUnitTest.inc
- src/Standards/Squiz/Tests/Objects/ObjectInstantiationUnitTest.php
The `Squiz.Objects.ObjectInstantiation` did not take null coalesce into account.
It also was potentially a little too lenient for ternaries as an inline then or inline else token before the `new` keyword would be considered an assignment, while it was never checked that the result of the ternary was actually assigned to something.
While still not 100%, this commit improves the sniffs to:
1. Allow for null coalesce assignments `??=`.
2. For ternary tokens + null coalesce `??`: verify if the result of either of these is actually "assigned" to something (or preceded by one of the other "allowed" tokens).
This should reduce the number of both false positives as well as false negatives, though there is still the potential for some false negatives - see the test on line 32 of the test case …
> Squiz/ObjectInstantiation: bug fix - account for null coalesce

- package.xml
- src/Standards/Generic/Tests/Arrays/DisallowLongArraySyntaxUnitTest.php
- src/Standards/Squiz/Tests/PHP/CommentedOutCodeUnitTest.php
- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/ArrayKeywordTest.inc
- tests/Core/Tokenizer/ArrayKeywordTest.php
Happened to come across this while investigating something else.
As it was, as long as no open parenthesis or variable was encountered, this snippet would loop to the end of the file for each `T_ARRAY` token encountered as it would only `break` in the `if/elseif` and there was no `else` clause.
Basically, we only want the `array` keyword to be tokenized as `T_ARRAY` if it is an actual array declaration. In all other cases, it should be tokenized as `T_STRING`.
This fixes the performance leak by only looping to the first non-empty token after the keyword, checking if it's an open parenthesis and retokenizing the `T_ARRAY` to `T_STRING` in all other cases.
It also removes the need for the separate _return type_ retokenization of the array keyword.
Includes adding unit tests specifically for …
>  Tokenizer/PHP: bug fix - fix performance issue

- src/Files/DummyFile.php
- src/Runner.php
The `DummyFile::__construct()` method expects a `string` as the first parameter, subsequently passes it to the `File::setContent()` method, which also expects a `string`, which then passes it to the `Common::detectLineEndings()` method, which again expects a `string`.
Within the `Common::detectLineEndings()` method, the string is then passed to the PHP native `preg_match()` function, which (again) expects as `string` for the `$subject` parameter.
When using PHPCS with parallel processing turned on, on a system which allows for parallel processing, the `DummyFile` class was, however, being instantiated in the `Runner::processChildProcs()` method with `null` as the content of the first parameter, which on PHP 8.1 leads to `preg_match(): Passing null to parameter #2 ($subject) of type string …
> PHP 8.1 | Runner::processChildProcs(): fix passing null to non-nullable bug

- .github/workflows/test.yml
We can remove the `experimental` key in favour of checking against the PHP version in `continue-on-error`.
What is included in `E_ALL` can vary across PHP versions. Setting `error_reporting` to `-1` will ensure ALL errors are always shown, no matter what.
The `matrix.php` setting is a text string, so let's compare against it as a text string.
> GH Actions: various tweaks

- src/Util/Timing.php
Closes #3448
With this fix I got clean reports
Steps https://3v4l.org/flZrS
> Fix deprecation for PHP 8.1

- src/Standards/Squiz/Sniffs/WhiteSpace/ScopeClosingBraceSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/ScopeClosingBraceUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeClosingBraceUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ScopeClosingBraceUnitTest.php
When non-empty inline HTML is on the same line, before the scope closing, the sniff would incorrectly throw the `Closing brace indented incorrectly; expected %s spaces, found %s` error, instead of the `Closing brace must be on a line by itself` error.
This would ultimately lead to the fixer removing the non-empty inline HTML, potentially breaking HTML display/structure.
Fixed now. Includes unit test.
Fixes #3422
> Squiz/ScopeClosingBrace: bug fix - prevent removing inline HTML when fixing

- src/Config.php
- src/Util/Common.php
... with calls to `Common::isReadable()` as introduced in d56e167a5dea3550996f197b5d92b1418b1e3fab .
Includes adding additional error silencing to the `Common::isReadable()` function as each of these PHP native functions will throw a warning upon failure.
Fixes #3388
> WSL support: replace remaining calls to `is_readable()`

- src/Tokenizers/Tokenizer.php
This piece of code is very hot, executed thousands, possibly millions of times.
I found this when I benchmarked our custom sniffs. The replaceTabsInToken() method is consistently reported as one of the absolute hottest ones. I looked at the method and was wondering why this particular piece is a loop when it can be a mathematical expression. According to my micro-benchmark (only measuring the changed piece) it's about twice as fast now. This will probably not have much of an effect in a real-world scenario. Still I find it worth it.
> Replace hot Tokenizer loop with a mathematical expression

- src/Standards/Squiz/Sniffs/WhiteSpace/MemberVarSpacingSniff.php
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.php
Fixes false positives when class properties are declared with attributes and without DocComment.
Without this fix it's impossible to use only attributes for properties without DocComments, because this sniff forces you to insert blank line between the property and the attribute:
```
Expected 1 blank line(s) before member var; 0 found (Squiz.WhiteSpace.MemberVarSpacing.Incorrect)
```
Actual result:
```diff
--- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc.fixed
+++ PHP_CodeSniffer
@@ -363,12 +363,14 @@
{
protected $propertyDouble;
#[ThirdAttribute]
+
protected $propertyWithoutSpacing;
}
```
Expected result:
```diff
--- src/Standards/Squiz/Tests/WhiteSpace/MemberVarSpacingUnitTest.inc.fixed
+++ PHP_CodeSniffer
@@ -363,12 +363,14 @@
{
protected $propertyDouble;
+ …
```
> Squiz.WhiteSpace.MemberVarSpacing false positives when attributes used without docblock

- src/Standards/Generic/Sniffs/Metrics/CyclomaticComplexitySniff.php
- src/Standards/Generic/Tests/Metrics/CyclomaticComplexityUnitTest.inc
- src/Standards/Generic/Tests/Metrics/CyclomaticComplexityUnitTest.php
Resolve 3 issues with the Cyclometric Complexity sniff
- Fix for Issue [#3468](https://github.com/squizlabs/PHP_CodeSniffer/issues/3468)
do/while loops are double-counted in the Generic.Metrics.CyclomaticComplexity sniff
- Fix for Issue [#3469](https://github.com/squizlabs/PHP_CodeSniffer/issues/3469)
Ternary Operator and Null Coalescing Operator are not counted in the Generic.Metrics.CyclomaticComplexity sniff
- Issue [#3472](https://github.com/squizlabs/PHP_CodeSniffer/issues/3472)
PHP 8 match() expression is not counted in the Generic.Metrics.CyclomaticComplexity sniff
This PR replaces [PR #3470](https://github.com/squizlabs/PHP_CodeSniffer/pull/3470), [PR #3471](https://github.com/squizlabs/PHP_CodeSniffer/pull/3471) and [PR #3473 …
> Cyclomatic complexity updates and fixes

- src/Standards/Generic/Sniffs/Formatting/MultipleStatementAlignmentSniff.php
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.inc.fixed
- src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.php
For use within the loop in the `checkAlignment()` method, closures are explicitly removed for the `$scopeOpeners` array as they can be (and often are) assigned to a variable.
However, a closure which contained a parameter with a default value would take the equal sign for the default value as the start of a new block.
The `process()` method already contained a safeguard against this, but it's the `checkAlignment()` method which is being called recursively, so this check was not executed for those recursive calls.
Calling the `process()` method recursively would be troublesome as the returned stackPtr is incremented by one in the `process()` method, so moving the initial check from the `process()` method to the `checkAlignment()` method seemed a reasonable solution.
There will probably be …
> Generic/MultipleStatementAlignment: bug fix for closure params with defaults

- .github/workflows/test.yml
PHP 8.1 has been released, so builds against it should no longer be allowed to fail.
Also adding PHP 8.2 as the new "nightly" build (which is allowed to fail).
> GH Actions: PHP 8.1 has been released

- src/Standards/PSR12/Sniffs/Classes/ClassInstantiationSniff.php
- src/Standards/PSR12/Tests/Classes/ClassInstantiationUnitTest.inc
- src/Standards/PSR12/Tests/Classes/ClassInstantiationUnitTest.inc.fixed
The `class` keyword was correctly tokenized as `T_ANON_CLASS`, even when there is an attribute between the `new` and the `class` keyword, however, the `PSR12.Classes.ClassInstantiation` sniff did not take that possibility into account, leading to false positives.
This commit:
* Adds code to skip over attributes.
Note: I've elected to skip over attributes, but as these attributes AFAICS can only be added in combination with an anonymous class and anonymous classes are ignored by this sniff, it would also be a valid option to bow out of the sniff when an attribute is encountered. As this would be inconsistent with how the `T_ANON_CLASS` token was handled so far, I've not gone with that option.
* Adds some additional extra guard code to prevent future false positives for when the class name …
> PSR12/ClassInstantiation: bug fix for attributes with anonymous classes

- phpunit.xml.dist
**Note:** This PR is only pulled to the PHPCS 4.x branch as PHPCS 4.x uses PHPUnit 8 and 9, while PHPCS 3.x is still limited to PHPUnit < 8.
PHPUnit just released version 9.5.10 and 8.5.21.
This contains a particular (IMO breaking) change:
> * PHPUnit no longer converts PHP deprecations to exceptions by default (configure `convertDeprecationsToExceptions="true"` to enable this)
Let's unpack this:
Previously (PHPUnit < 9.5.10/8.5.21), if PHPUnit would encounter a PHP native deprecation notice, it would:
1. Show a test which causes a deprecation notice to be thrown as **"errored"**,
2. Show the **first** deprecation notice it encountered and
3. PHPUnit would exit with a **non-0 exit code** (2), which will fail a CI build.
As of PHPUnit 9.5.10/8.5.21, if PHPUnit encounters a PHP native …
> PHPCS 4.x | PHPUnit: update configuration

- .github/workflows/test.yml
- scripts/build-phar.php
As things were in the CI script, the `phpcs` and `phpcbf` Phars would be build against each supported PHP version and the tests run with the `phpcs` Phar would use the Phar as build on the same PHP version as the test was being run on.
This test was not representative of the reality as with each release, only one `phpcs` and one `phpcbf` phar is released.
The changes in this commit:
* Split the building of the Phar off from the main test script.
* This new `build` job:
- Tests building the Phar against all supported PHP versions as an early detection system for problems in the Phar extension/Phar building script.
- Uploads both phars as build against PHP 7.4.
The uploaded Phars match the Phars as would be included on a release as they are build against the same PHP version as used for …
> GH Actions: split PHAR build test from other tests

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillReadonlyTest.inc
- tests/Core/Tokenizer/BackfillReadonlyTest.php
Follow up on #3480
While going through some sniffs to add support, I realized that parameters with a reference were not accounted for correctly. Didn't think of this before either.
Fixed now, including test.
/cc @kukulich
> PHP 8.1 | Tokenizer/PHP: readonly bug fix

- src/Standards/Generic/Sniffs/PHP/LowerCaseKeywordSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.php
> PHP 8.1 | Generic/LowerCaseKeyword: allow for readonly keyword

- src/Standards/Squiz/Sniffs/Commenting/BlockCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/BlockCommentUnitTest.inc.fixed
> PHP 8.1 | Squiz/BlockComment: prevent false positives for readonly keyword

- src/Standards/Squiz/Sniffs/Commenting/DocCommentAlignmentSniff.php
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.php
> PHP 8.1 | Squiz/DocCommentAlignment: allow for readonly keyword

- src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.php
> PHP 8.1 | Squiz/VariableComment: allow for readonly keyword

- src/Standards/PSR2/Sniffs/Classes/PropertyDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.php
> PHP 8.1 | PSR2/PropertyDeclaration: allow for readonly keyword

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BitwiseOrTest.inc
- tests/Core/Tokenizer/BitwiseOrTest.php
More follow up on #3480.
Done some more stress testing and found that the retokenization of `|` to `T_TYPE_UNION` was broken when combined with the `readonly` keyword.
Fixed now, includes test.
/cc @kukulich
> PHP 8.1 | Tokenizer/PHP: readonly vs union types bug fix

- src/Tokenizers/PHP.php
Follow up on #3350
As things were, `$tokens[i]` may not exist and the current condition order would lead to a `PHP Warning:  Undefined array key 517 in php_codesniffer/src/Tokenizers/PHP.php on line 2101` notice if the end of the file was reached.
Fixed now.
> Tokenizer/PHP: fix incorrect condition order

- src/Standards/PSR12/Sniffs/Properties/ConstantVisibilitySniff.php
- src/Standards/PSR12/Tests/Properties/ConstantVisibilityUnitTest.inc
- src/Standards/PSR12/Tests/Properties/ConstantVisibilityUnitTest.php
PHP 8.1 introduces the ability to declare class constants as `final`.
The tokenization of the `final` keyword in this context appears to be consistent PHPCS cross-version, so AFAICS no changes are needed to the PHP tokenizer.
However, the `PSR12.Properties.ConstantVisibility` sniff does need to allow for them.
Ref: https://wiki.php.net/rfc/final_class_const
Fixes #3526
Related to #3479
---
Notes:
* The test failures are unrelated to this PR and PR #3525 is already open to fix those.
* I've done a cursory scan of all sniffs referring to the `T_CONST` token and could not find any other sniffs which would need adjusting for this PHP change.
> PHP 8.1 | PSR12/ConstantVisibility: allow for class constants to be `final`

- package.xml
- src/Tokenizers/PHP.php
- src/Util/Tokens.php
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
Other tokens should be added after these PR are merged:
> Improved tokenizing of context sensitive keywords

- package.xml
- src/Tokenizers/PHP.php
- src/Util/Tokens.php
- tests/Core/Tokenizer/BackfillEnumTest.inc
- tests/Core/Tokenizer/BackfillEnumTest.php
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
Fixes https://github.com/squizlabs/PHP_CodeSniffer/issues/3474
> PHP 8.1: Added support for `enum` keyword

- src/Standards/Generic/Sniffs/Metrics/CyclomaticComplexitySniff.php
- src/Standards/Generic/Tests/Metrics/CyclomaticComplexityUnitTest.inc
- src/Standards/Generic/Tests/Metrics/CyclomaticComplexityUnitTest.php
Issue [#3505](https://github.com/squizlabs/PHP_CodeSniffer/issues/3505)
Add nullsafe object operator to tokens that trigger an increase in cyclomatic complexity
> Include NullSafe operator in calculation for Cyclomatic Complexity Sniff

- CodeSniffer.conf.dist
- src/Config.php
While not problematic, it just feels very untidy for the `CodeSniffer.conf` file not to end the code block with a semicolon.
> CodeSniffer.conf: end code with semicolon

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillEnumTest.inc
- tests/Core/Tokenizer/BackfillEnumTest.php
- tests/Core/Tokenizer/GotoLabelTest.inc
- tests/Core/Tokenizer/GotoLabelTest.php
Follow up on #3478.
When an `enum` would be backed by a type and the colon would directly follow the name of the `enum`, the name would be incorrectly tokenized (including the colon) as `T_GOTO_LABEL`.
Discovered while reviewing #3482
Also related to #3161
/cc @kukulich 
---
... after the bugfix for `T_GOTO_LABEL`.
Also added a minor tweak to one test case to make sure that spacing around the type colon is handled correctly.
> Name of typed enum tokenized as T_GOTO_LABEL

- src/Runner.php
This patch simplifies the logic of waiting for child processes during parallel processing and may address #3144.
Change summary:
1. Instead of busy-waiting using `pcntl_waitpid(WNOHANG)` in a loop, let `pcntl_waitpid()` block until a child exits. This should address the following symptom:
> Some processes seem to do nothing `0 wait4(18694, 0x7ffe6ddd6cbc, WNOHANG, NULL) = 0` (strace) but still need max CPU power (top).
2. Index child processes by PID to simplify the logic of unsetting exited children.
3. Do not use `$pid` as the exit code. This is unnecessary and violates the [API](https://www.php.net/manual/en/function.exit.php),
> Exit statuses should be in the range 0 to 254, the exit status 255 is reserved by PHP and shall not be used.
> Get rid of busy-waiting in the parent process

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
Follow up on #3484 /cc @kukulich 
Just like `new class`, `new parent`, `new self` and `new static` should also be preserved and with the `parent`, `self` and `static` keywords remaining as their dedicated token.
* For `new static`, the tokenization changed due to the context sensitive keywords change. This has now been fixed.
* `new self` was fine before and is still fine.
* `new parent` apparently wasn't handled correctly, even before the change. The condition which was in place for handling the same situation for `self` has now been updated to also handle `parent`.
> Tokenizer/PHP: bug fix - parent/static keywords in class instantiations

- package.xml
- src/Tokenizers/PHP.php
- src/Util/Tokens.php
- tests/Core/Tokenizer/EnumCaseTest.inc
- tests/Core/Tokenizer/EnumCaseTest.php
Based on https://github.com/squizlabs/PHP_CodeSniffer/pull/3478
> PHP 8.1: Added `T_ENUM_CASE`

- src/Standards/PSR2/Sniffs/ControlStructures/SwitchDeclarationSniff.php
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/ControlStructures/SwitchDeclarationUnitTest.inc.fixed
Trailing comments within control structures nested within a switch case would break the determination of whether or not there is a terminating statement within the nested control structure.
Making the `findNestedTerminator()` method look for non-empty instead of non-whitespace tokens fixes that and shouldn't break the `TerminatingComment` check as that has it's own check whether the last token in the case statement is a comment.
Fixes #3550
> PSR2/SwitchDeclaration: bug fix when determining terminating statement

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.inc
- tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.php
- tests/Core/Tokenizer/BackfillNumericSeparatorTest.inc
- tests/Core/Tokenizer/BackfillNumericSeparatorTest.php
Follow up on #3481. /cc @MarkBaker 
Just like for all other type of integer notations, if a numeric literal separator is used, it is not allowed between the prefix and the actual number.
```php
// This is fine.
$b = 0b1_0;
$o = 0o6_3;
// This is an invalid use of the numeric literal separator.
$b = 0b_10;
$o = 0o_63;
```
This PR fixes the backfill for explicit octal notation to NOT backfill these type of invalid sequences as the inconsistent tokenization across PHP versions which that causes, can create havoc in sniffs.
Includes adding additional unit tests.
@gsherwood Greg - can this PR please be earmarked for PHPCS 3.7.0 to prevent the incorrect tokenization getting into a released version ?
> PHP 8.1 | Tokenizer/PHP: bug fix for overeager explicit octal notation backfill

- src/Util/Standards.php
I noticed this while debugging something completely different: the display order of the registered standards can vary wildly between different computers/OSes.
For example, on Windows, they always seem to be ordered alphabetically:
> The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz and Zend
And in case there are external standards registered, they are sorted alphabetically per "set of standards", i.e. per registered "installed path":
> The installed coding standards are MySource, PEAR, PSR1, PSR12, PSR2, Squiz, Zend, WordPress, WordPress-Core, WordPress-Docs, WordPress-Extra and PHPCompatibility
However, on Linux, I was seeing a completely different (more random) order, like for example:
> The installed coding standards are PEAR, PSR2, PSR1, Squiz, PSR12, …
> PHPCS -i: display standards in same order cross-platform

- src/Standards/PEAR/Tests/WhiteSpace/ScopeClosingBraceUnitTest.inc
- src/Standards/PEAR/Tests/WhiteSpace/ScopeClosingBraceUnitTest.inc.fixed
- src/Standards/PEAR/Tests/WhiteSpace/ScopeClosingBraceUnitTest.php
- src/Standards/PSR12/Tests/Classes/OpeningBraceSpaceUnitTest.inc
- src/Standards/PSR12/Tests/Classes/OpeningBraceSpaceUnitTest.inc.fixed
- src/Standards/PSR12/Tests/Classes/OpeningBraceSpaceUnitTest.php
- src/Standards/Squiz/Sniffs/Commenting/ClosingDeclarationCommentSniff.php
- src/Standards/Squiz/Sniffs/Commenting/DocCommentAlignmentSniff.php
- src/Standards/Squiz/Tests/Commenting/ClosingDeclarationCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/ClosingDeclarationCommentUnitTest.php
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/DocCommentAlignmentUnitTest.php
- src/Standards/Squiz/Tests/WhiteSpace/ScopeClosingBraceUnitTest.inc
- src/Standards/Squiz/Tests/WhiteSpace/ScopeClosingBraceUnitTest.inc.fixed
- src/Standards/Squiz/Tests/WhiteSpace/ScopeClosingBraceUnitTest.php
Follow up on #3482 as per https://github.com/squizlabs/PHP_CodeSniffer/pull/3482#issuecomment-1016007608
> PHP 8.1 | Add `enum` support to various additional sniffs

- src/Standards/Generic/Sniffs/PHP/LowerCaseKeywordSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.php
This is a PR to simplify maintenance of this sniff.
Since PR #3484, the `Tokens` class contains a `$contextSensitiveKeywords` property which largely overlaps with the list of tokens registered for this sniff.
All tokens in that list should always be included in the targets for this sniff anyway, so we may as well leverage the new token array.
Includes adding the new custom `T_ENUM_CASE` token to the list of additional tokens to take into account.
> PHP 8.1 | Generic/LowerCaseKeyword: simplify registered tokens + add `enum` support

- src/Files/File.php
- tests/Core/File/GetMemberPropertiesTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
Neither enums nor interfaces support properties being declared on them.
This adjusts the `File::getMemberProperties()` method to handle properties declared on an `enum` in the same way as properties declared on an `interface` were already being handled.
> PHP 8.1 | File::getMemberProperties(): handle `enum` properties same as interface properties

- src/Files/File.php
- tests/Core/File/FindImplementedInterfaceNamesTest.inc
- tests/Core/File/FindImplementedInterfaceNamesTest.php
An `enum` declaration can implement one or more interfaces.
This commit updates the `File::findImplementedInterfaceNames()` method to allow it to find the interfaces implemented by an `enum` as well.
> PHP 8.1 | File::findImplementedInterfaceNames(): add support for enums implementing interfaces

- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc.fixed
Removed during rebase by mistake...
> PHP 8.1: Added missing tests of intersection types for `LowerCaseTypeSniff`

- .github/workflows/phpstan.yml
- .github/workflows/test.yml
The action used to install Composer packages and handle the caching has released a new major (and some follow-up patch releases), which means, the action reference needs to be updated to benefit from it.
Refs:
* https://github.com/ramsey/composer-install/releases/tag/2.0.0
* https://github.com/ramsey/composer-install/releases/tag/2.0.1
* https://github.com/ramsey/composer-install/releases/tag/2.0.2
> GH Actions: version update for `ramsey/composer-install`

- src/Standards/Generic/Sniffs/Files/OneClassPerFileSniff.php
- src/Standards/Generic/Sniffs/Files/OneInterfacePerFileSniff.php
- src/Standards/Generic/Sniffs/Files/OneObjectStructurePerFileSniff.php
- src/Standards/Generic/Sniffs/Files/OneTraitPerFileSniff.php
Each of these sniffs would start walking the rest of the file from the token next to the OO keyword to the end of the file in search of the next (class/interface/trait) keyword.
As nested OO structure declarations (with the exception of anonymous classes, but those are outside the realm of these sniffs) are not supported in PHP, we can make these sniffs a lot faster by starting the search _after_ the scope closer for the current OO structure.
> Generic/One*PerFile sniffs: efficiency tweak

- src/Tokenizers/PHP.php
- src/Util/Tokens.php
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
As reported in #3607, the `eval` keyword was not included in the list of context sensitive keyword. This is a regression compared to PHPCS 3.6.2.
Fixed now, including unit tests.
Fixes #3607
While investigating #3607, I figured adding a test with a function declared to return by reference would also not be amiss and found that that situation was not accounted for.
This commit fixes that.
> [Hot fix] Tokenizer/PHP: 2 bug fixes for improved context sensitive keyword support

- src/Standards/Squiz/Sniffs/Scope/MethodScopeSniff.php
- src/Standards/Squiz/Tests/Scope/MethodScopeUnitTest.inc
The `Squiz.Scope.MethodScope` sniff is intended to check whether each method has visibility declared, but would in actual fact also enforce that the visibility should be on the same line as the `function` keyword as it stopped searching for the visibility keyword once it reached the start of the line.
Fixed now by using the `File::getMethodProperties()` method for determining visibility instead of searching with sniff specific logic.
> Squiz.Scope.MethodScope misses visibility keyword on previous line

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.inc
- tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.php
Follow up on #3481 and #3552. /cc @MarkBaker 
While working on PHPCompatibility/PHPCSUtils, I found another instance where the explicit octal notation backfill is overeager.
PHP natively will tokenize invalid octals, like `0o91` as `T_LNUMBER` + `T_STRING` in all PHP versions, but with the backfill in place, this would no longer be the case and on PHP < 8.1, this would now be tokenized as `T_LNUMBER`, making tokenization across PHP versions unpredictable and inconsistent.
Fixed now. Including tests.
@gsherwood Similar to the previous fix, could this fix _please_ still be merged into `3.7.0` to prevent this incorrect tokenization ending up in a released version ?
> PHP 8.1 | Tokenizer/PHP: hotfix for overeager explicit octal notation backfill

- package.xml
- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/DoubleQuotedStringTest.inc
- tests/Core/Tokenizer/DoubleQuotedStringTest.php
While creating a sniff for PHPCompatibility to detect the PHP 8.2 deprecation of two of the four syntaxes to embed variables/expressions within text strings, I realized that for select examples of the "type 4" syntax - "Variable variables (`“${expr}”`, equivalent to (string) `${expr})`" -, PHPCS did not, and probably never did, tokenize those correctly.
Double quoted strings in PHPCS are normally tokenized as one token (per line), including any and all embedded variables and expressions to prevent problems in the scope map caused by braces within the string/expression.
However, for some double quoted strings using `${` syntax, this was not the case and these were tokenized as outlined below, which would still lead to the problems in the scope map.
Luckily, these syntax variants aren't …
> Tokenizer/PHP: bug fix for double quoted strings using `${`

- src/Standards/Squiz/Sniffs/PHP/DisallowComparisonAssignmentSniff.php
- src/Standards/Squiz/Tests/PHP/DisallowComparisonAssignmentUnitTest.inc
Fixes #3616
Note: I've changed the `findNext()` call from an exhaustive call to the end of the statement to a faster check for the first non-empty token, which I believe was the actual _intention_ of the function call.
As no tests are failing, I'm fairly certain my suspicion is correct ;-)
> Squiz/DisallowComparisonAssignment: bug fix - ignore match structures

- src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.inc
- src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.inc.fixed
- src/Util/Tokens.php
Follow up to PR #3546, which changed how the `parent` keyword in a `new parent` snippet was tokenized from `T_STRING` to `T_PARENT`.
The `T_PARENT` keyword token, however, was not included in the `Tokens::$functionNameTokens` array, which was the underlying cause for the bug reported in #3618.
Fixed now.
Tested by adding additional tests to the `Generic.WhiteSpace.ArbitraryParenthesesSpacing` sniff. These tests passed in PHPCS 3.6.2 and started failing in PHPCS 3.7.0. Once this fix has been merged, the tests will pass again.
Fixes #3618
> Tokens::$functionNameTokens: include the `parent` keyword

- src/Runner.php
When a child process fails, e.g. with a FatalError, it might still return empty list of errors. Although, child process failure is definitely not a thing we want to ignore.
Therefore, we check exit status of each child process and make sure parent process fails (and returns non-zero status code) as well.
> PHPCS can show 0 exit code when running in parallel even if child process has fatal error

- src/Standards/Generic/Sniffs/PHP/LowerCaseTypeSniff.php
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.inc.fixed
- src/Standards/Generic/Tests/PHP/LowerCaseTypeUnitTest.php
PHP 7.4 arrow functions were not yet being taken into account for this sniff.
Fixed now.
> Generic/LowerCaseType: examine types in arrow function declarations

- src/Runner.php
As discussed in #3621, this PR adds a new function to show a "friendly" error message if/when PHPCS runs out of memory.
This functionality can't be tested via the unit/integration test suite as the PHP shutdown can't be mocked.
To test the functionality, I used a test run of PHPCS over its own code base with the following command:
```bash
phpcs -d memory_limit 32M
```
This should yield something along the lines of the below screenshot:
Fixes #3621
> Runner: show actionable information when PHPCS runs out of memory

- src/Standards/PSR12/Sniffs/Classes/ClassInstantiationSniff.php
- src/Standards/PSR12/Tests/Classes/ClassInstantiationUnitTest.inc
- src/Standards/PSR12/Tests/Classes/ClassInstantiationUnitTest.inc.fixed
- src/Standards/PSR12/Tests/Classes/ClassInstantiationUnitTest.php
Related to #3546 which fixed an inconsistency after #3484.
The change of the tokenization from `T_STRING` to `T_PARENT` for the `parent` keyword in `new parent` caused a regression in the `PSR12.Classes.ClassInstantiation` sniff.
Fixed now.
Fixes #3668
> PSR12/ClassInstantiation: fix regression for `new parent`

- src/Standards/Generic/Sniffs/Functions/FunctionCallArgumentSpacingSniff.php
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.inc.fixed
- src/Standards/Generic/Tests/Functions/FunctionCallArgumentSpacingUnitTest.php
Related to #3546 which fixed an inconsistency after #3484.
The change of the tokenization from `T_STRING` to `T_PARENT` for the `parent` keyword in `new parent` caused a regression in the `Generic.Functions.FunctionCallArgumentSpacing` sniff.
Fixed now.
> Generic/FunctionCallArgumentSpacing: fix regression for `new parent`

- src/Standards/Squiz/Sniffs/Formatting/OperatorBracketSniff.php
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.inc
- src/Standards/Squiz/Tests/Formatting/OperatorBracketUnitTest.inc.fixed
Related to #3546 which fixed an inconsistency after #3484.
The change of the tokenization from `T_STRING` to `T_PARENT` for the `parent` keyword caused a regression in the `Squiz.Formatting.OperatorBracket` sniff.
Fixed now.
> Squiz/OperatorBracket: fix regression for `new parent`

- tests/Core/File/FindEndOfStatementTest.inc
- tests/Core/File/GetMemberPropertiesTest.php
- tests/Core/File/GetMethodParametersTest.php
- tests/Core/File/GetMethodPropertiesTest.php
- tests/Core/File/IsReferenceTest.inc
- tests/Core/Tokenizer/ScopeSettingWithNamespaceOperatorTest.inc
... picked up along the way.
The `return 0;` statement belongs with the `testStaticArrowFunction` test and was introduced to test a specific bug in #2749.
This brings the test back to its correct state.
(while the diff may look weird, in reality, it just moves three tests up)
> Tests: various small improvements

- src/Standards/Generic/Sniffs/PHP/UpperCaseConstantSniff.php
- src/Standards/Squiz/Sniffs/ControlStructures/ForLoopDeclarationSniff.php
- tests/Core/Autoloader/DetermineLoadedClassTest.php
- tests/Core/Tokenizer/AttributesTest.php
.. picked up along the way.
* Remove unused `use` statements.
* Use `use` statements.
* No need for a combined assignment operator.
> Various minor code tweaks

- .github/workflows/test.yml
GitHub has deprecated the use of `set-output` (and `set-state`) in favour of new environment files.
This commit updates workflows to use the new methodology.
Refs:
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
* https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files
👉🏻 Note: this won't get rid of all warning yet as a lot of predefined action runners also use `set-output`, but most of those are in the process of updating and/or have released a new version already, so the other warnings should automatically disappear over the next few weeks.
> GH Actions: fix use of deprecated `set-output`

- tests/Core/Tokenizer/NamedFunctionCallArgumentsTest.inc
- tests/Core/Tokenizer/NamedFunctionCallArgumentsTest.php
(this is to safeguard that the `enum` retokenization doesn't interfere with the parameter label retokenization)
> NamedFunctionCallArgumentsTest: add test with PHP 8.1 enum keyword

- package.xml
- src/Standards/Generic/Sniffs/WhiteSpace/DisallowTabIndentSniff.php
- src/Standards/Generic/Tests/WhiteSpace/DisallowTabIndentUnitTest.3.inc
- src/Standards/Generic/Tests/WhiteSpace/DisallowTabIndentUnitTest.3.inc.fixed
- src/Standards/Generic/Tests/WhiteSpace/DisallowTabIndentUnitTest.php
Since PHP 7.3, heredoc/nowdoc closers may be indented.
This indent can use either tabs or spaces and the indent is included in the `T_END_HEREDOC`/`T_END_NOWDOC` token contents as received from the PHP native tokenizer.
However, these tokens where not included in the tokens to look at for the `Generic.WhiteSpace.DisallowTabIndent` sniff, which could lead to false negatives.
Fixed now, includes tests.
> Generic.WhiteSpace.DisallowTabIndent not reporting errors for PHP 7.3 flexible heredoc/nowdoc syntax

- src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php
While looking at issue #3362 in an attempt to debug it, @BinaryKitten and me came across a `An error occurred during processing; checking has been aborted. The error message was: Undefined array key "" in /src/Standards/Generic/Sniffs/WhiteSpace/ScopeIndentSniff.php on line 646 (Internal.Exception)` error notice.
While this will probably only occur in exceptional circumstances, it was caused by an operator precedence issue in the scope closer check condition.
Adding the extra parentheses fixes the operator precedence snafu and prevents the above error notice.
Note: this does not fix #3362, but still, is one less bug to worry about ;-)
> Generic/ScopeIndent: minor bug fix (undefined array index)

- src/Standards/Generic/Docs/Classes/OpeningBraceSameLineStandard.xml
- src/Standards/Generic/Docs/Formatting/SpaceAfterNotStandard.xml
- src/Standards/Generic/Docs/WhiteSpace/ArbitraryParenthesesSpacingStandard.xml
Each of these three sniffs had a `<code_comparison>` block containing _three_ `<code>` elements instead of two.
Discovered by validating the docs against the XSD schema created by the amazing @dingo-d. The XSD schema is now available in [PHPCSDevTools](https://github.com/PHPCSStandards/PHPCSDevTools) 1.2.0 as discussed in #3585.
If you're interested, I could refresh (a variation of) PR #2872 to add XML doc validation against the schema to the GH Actions checks.
> Docs: fix invalid XML docs for three sniffs

- src/Standards/Generic/Sniffs/WhiteSpace/SpreadOperatorSpacingAfterSniff.php
- src/Standards/Generic/Tests/WhiteSpace/SpreadOperatorSpacingAfterUnitTest.inc
- src/Standards/Generic/Tests/WhiteSpace/SpreadOperatorSpacingAfterUnitTest.inc.fixed
... as in that case the spread operator does not apply to a variable/function call and the likelihood of the sniff conflicting with other sniffs which examine the spacing on the inside of parenthesis is high.
Ref:
* https://wiki.php.net/rfc/first_class_callable_syntax
* https://3v4l.org/YTTO1
> Generic.WhiteSpace.SpreadOperatorSpacingAfter does not ignore spread operator in PHP 8.1 first class callables

- package.xml
- tests/Core/Tokenizer/HeredocStringTest.inc
- tests/Core/Tokenizer/HeredocStringTest.php
Similar to previous PR #3604 which fixed the tokenization for complex double quoted strings with interpolated variables/expressions and added tests for it.
Context: I ran into a tokenizer issue with heredocs and interpolated variables elsewhere, so I wrote some tests for it. Turned out all was okay with the tokenizer, but the test elsewhere had a parse error in PHP < 7.3. Either way, I figured I may as well pull the tests to safeguard things stay okay ;-)
> Tokenizer/PHP: add tests for consistent tokenization heredocs with interpolated strings

- src/Ruleset.php
When running the `phpcs --standard=Name -e` command, the line at the top of the output would always presumes that a standard contains more than one sniff.
The sniff count for the standards within the standard - `StandardName (# sniff[s])` - already handled this correctly.
Fixed the top line now.
Output without this fix:
```
The DummySubDir standard contains 1 sniffs
DummySubDir (1 sniff)
----------------------
DummySubDir.Demo.Demo
```
Output with this fix:
```
The DummySubDir standard contains 1 sniff
DummySubDir (1 sniff)
----------------------
DummySubDir.Demo.Demo
```
> Ruleset::explain(): fix plural vs singular phrasing

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.inc
- tests/Core/Tokenizer/BackfillExplicitOctalNotationTest.php
... in the backfill for the PHP 8.1 explicit octal notation.
> Potential "Uninitialized string offset 1" in octal notation backfill

- .github/workflows/phpstan.yml
- .github/workflows/test.yml
Caches used in GH Actions do not get updated, they can only be replaced by a different cache with a different cache key.
Now the predefined Composer install action this repo is using already creates a pretty comprehensive cache key:
> `ramsey/composer-install` will auto-generate a cache key which is composed of
the following elements:
> * The OS image name, like `ubuntu-latest`.
> * The exact PHP version, like `8.1.11`.
> * The options passed via `composer-options`.
> * The dependency version setting as per `dependency-versions`.
> * The working directory as per `working-directory`.
> * A hash of the `composer.json` and/or `composer.lock` files.
This means that aside from other factors, the cache will always be busted when changes are made to the (committed) `composer.json` or the …
> GH Actions: bust the cache semi-regularly

- src/Standards/Squiz/Tests/Objects/ObjectInstantiationUnitTest.inc
- src/Tokenizers/PHP.php
This fixes the mis-identification of a `T_DEFAULT` token within a (not yet retokenized) `match` structure as a `switch` `default` token, which resulted in a `T_COLON` token incorrectly not being retokenized to `T_INLINE_ELSE`.
As a complete test file for ternary tokenization does not exist (yet), I've added a unit test to the `Squiz.Objects.ObjectInstantiation` sniff. The code in the test would cause a false positive for the `ObjectInstantiation` sniff without this fix.
Fixes #3789
> Tokenizer/PHP: bug fix for match within ternary

- src/Tokenizers/PHP.php
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.inc
- tests/Core/Tokenizer/ContextSensitiveKeywordsTest.php
PHPCS re-tokenizes the `self`, `parent`, `true`, `false` and `null` keywords to a PHPCS native token.
This re-tokenization did not take the following situations into account:
* Those keywords being used as function names when the function is declared to return by reference.
* Those keywords being used as a function call.
Additionally, the PHP native `T_STATIC` token would not be (re-)tokenized to `T_STRING` when used as a function call, though it was tokenized correctly when used as a method call. While using the `static` keyword for a global function declaration is illegal in PHP, the tokenization in PHPCS should still be consistent.
This commit fixes those issues.
These issues were discovered while investigating issue …
> Tokenizer/PHP: more context sensitive keyword fixes

- src/Runner.php
When sniffs use traits/utility classes/helper functions, the message for the `Internal.Exception` can be unclear as it may point to the trait/utility classes/helper function as the culprit without any indication of which sniff caused the error.
This can cause bugs in sniffs to be reported by end-users in the wrong repository, but even when reported in the right repository, it makes the report unclear and means the maintainer will need to do more work to try and reproduce the issue.
This PR attempts to make the `Internal.Exception` error message more informative by pinpointing the sniff which caused the issue to occur. While this _may_ result in duplicate information when no traits/utility classes/helper functions are involved, for those cases when those are involved, I believe this will …
> Runner::processFile(): make internal error more informative

- src/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php
- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.1.inc
- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.php
`$prev` is already defined in exactly the same way on line 66. No need to re-define it.
Aside from `T_EXIT`, PHP (prior to PHP 8.0) does not allow for the inline use of the other tokens this sniff registers.
While using those tokens inline would result in a parse error, that is not the concern of this sniff.
By ignoring these, the sniff causes false negatives.
This commit makes the sniff more selective and only ignores inline statements for tokens which are allowed in inline statements.
The sniff, as it was, only allowed for `or` and `||` logical operators before a termination expression, not for `and`, `&&` or `xor`, while PHP allows these too.
See: https://3v4l.org/OWS4n#veol
Fixed now.
The `T_EXIT` token can be used in ternaries without …
> Squiz/NonExecutableCode: slew of bug fixes, mostly related to modern PHP

- src/Standards/Generic/Sniffs/PHP/ForbiddenFunctionsSniff.php
- src/Standards/Generic/Tests/PHP/ForbiddenFunctionsUnitTest.inc
- src/Standards/Squiz/Sniffs/PHP/LowercasePHPFunctionsSniff.php
- src/Standards/Squiz/Tests/PHP/DiscouragedFunctionsUnitTest.inc
- src/Standards/Squiz/Tests/PHP/LowercasePHPFunctionsUnitTest.inc
- src/Standards/Squiz/Tests/PHP/LowercasePHPFunctionsUnitTest.inc.fixed
Attributes cannot contain function calls and in most cases, `T_STRING`s in an attribute will be a class name, not a function name.
As things were, `T_STRING`'s in attributes which _looked_ like function calls (but in actual fact are class instantiations) would lead to false positives.
Fixed now by ignoring all code within attributes.
Fixes #3778
Attributes cannot contain function calls and in most cases, `T_STRING`s in an attribute will be a class name, not a function name.
As things were, `T_STRING`'s in attributes which _looked_ like function calls (but in actual fact are class instantiations) would lead to false positives.
Fixed now by ignoring all code within attributes.
> Squiz/LowercasePHPFunctions + Generic/ForbiddenFunctions: bug fix for class names in attributes

- src/Standards/PEAR/Sniffs/Functions/FunctionDeclarationSniff.php
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.inc
- src/Standards/PEAR/Tests/Functions/FunctionDeclarationUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.inc
- src/Standards/Squiz/Tests/Functions/MultiLineFunctionDeclarationUnitTest.inc.fixed
Since PHP 8.1, `new ClassName()` expressions can be used as the default value of a parameter in a function declaration.
`new ClassName()` expressions should be treated as function _calls_, which have their own indentation rules, so the `PEAR.Functions.FunctionDeclaration` and the `Squiz.Functions.MultiLineFunctionDeclaration` sniffs should skip over these and not attempt to change the indentation of parameters in those function calls.
This commit implements this change.
Refs:
* https://wiki.php.net/rfc/new_in_initializers
* https://www.php.net/manual/en/migration81.new-features.php#migration81.new-features.core.new-in-initializer
* https://www.php.net/manual/en/language.oop5.decon.php#language.oop5.decon.constructor.new
Fixes #3786
---
**Note**:
* I have also verified …
> PEAR/Squiz/[MultiLine]FunctionDeclaration: allow for PHP 8.1 new in initializers

- src/Standards/PSR2/Sniffs/Classes/PropertyDeclarationSniff.php
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.inc.fixed
- src/Standards/PSR2/Tests/Classes/PropertyDeclarationUnitTest.php
The `PSR2.Classes.PropertyDeclaration` sniff includes a check to verify that the `static` keyword is _after_ the visibility in a property declaration.
PHP 8.1 introduced the `readonly` keyword for properties, ~~but as PSR2/PSR12 were both released before PHP 8.1, no PSR rules have (yet) been defined for the modifier keyword order for `readonly` properties.~~
++[PSR PER 2.0.0](https://www.php-fig.org/per/coding-style/#46-modifier-keywords) dictates that visibility is declared before the `readonly` keyword.++
~~Having said that,~~ all code samples in both the RFC as well as the PHP manual use the `visibility - readonly` modifier keyword order, so it is likely that this will become the standard modifier keyword order.
A search for PHP projects which have started to use the `readonly` …
> PHP 8.1 | PSR2/PropertyDeclaration: add check for visibility before readonly keyword

- src/Config.php
As per issue #3760, if the `stty size` command errors out, `shell_exec()` will return `null`. Per the [documentation](https://www.php.net/manual/en/function.shell-exec.php#refsect1-function.shell-exec-returnvalues), the `shell_exec()` command can also return `false`, which would also be an unusable value (`preg_match()` will not match, so `'auto'` would be cast to int, resulting in `0` being set as the value).
If the output of `shell_exec()` would be `null`, PHP as of PHP 8.1 will throw a "passing null to non-nullable" notice.
Additionally, if the output from `shell_exec()` would be `false`, the original input would be an invalid non-numeric value or the original input would be `auto`, but the `shell_exec()` command is disabled, the code as-it-was, would set the `reportWidth` to `0`, …
> PHP 8.1 | Config: fix passing null to non-nullable notice

- .github/ISSUE_TEMPLATE/bug_report.md
... in hopes of reducing the number of issues which are incorrectly reported to this repo.
Includes automating the assignment of initial issue labels.
> Bug report template: add notice about external standards

- package.xml
- phpcs.xml.dist
- scripts/ValidatePEAR/ValidatePEARPackageXML.php
- src/Files/File.php
- src/Ruleset.php
- tests/Core/Ruleset/Fixtures/Sniffs/Category/SetPropertyAllowedAsDeclaredSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/Category/SetPropertyAllowedViaMagicMethodSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/Category/SetPropertyAllowedViaStdClassSniff.php
- tests/Core/Ruleset/Fixtures/Sniffs/Category/SetPropertyNotAllowedViaAttributeSniff.php
- tests/Core/Ruleset/RuleInclusionTest.php
- tests/Core/Ruleset/RuleInclusionTest.xml
- tests/Core/Ruleset/SetPropertyAllowedAsDeclaredTest.xml
- tests/Core/Ruleset/SetPropertyAllowedViaMagicMethodTest.xml
- tests/Core/Ruleset/SetPropertyAllowedViaStdClassTest.xml
- tests/Core/Ruleset/SetPropertyAppliesPropertyToMultipleSniffsInCategoryTest.xml
- tests/Core/Ruleset/SetPropertyDoesNotThrowErrorOnInvalidPropertyWhenSetForCategoryTest.xml
- tests/Core/Ruleset/SetPropertyDoesNotThrowErrorOnInvalidPropertyWhenSetForStandardTest.xml
- tests/Core/Ruleset/SetPropertyNotAllowedViaAttributeTest.xml
- tests/Core/Ruleset/SetPropertyThrowsErrorOnInvalidPropertyTest.xml
- tests/Core/Ruleset/SetSniffPropertyTest.php
The BC-breaks can be broken down as follows:
If a property is set via a ruleset for an **_individual_** sniff and that sniff does not have the property explicitly declared, nor does the sniff declare the PHP magic `__set()` method or `extend stdClass`, the ruleset will now be regarded as invalid.
In practice, this means the PHPCS run will halt and will show an informative notice to the end-user about the invalid property setting and the PHPCS run will exit with exit code `3`.
For properties being set for a complete category of sniffs or a complete standard, the PHPCS run will not halt, nor show an error when the property isn't supported for all sniffs in the category/standard.
In that case, the property will only be set on those sniffs which support it (i.e. either have the property …
> PHP 8.2 | Ruleset: prevent notices about dynamic properties being set

- package.xml
- tests/Core/Config/ReportWidthTest.php
Follow up on merged PR #3761
While definitively not a comprehensive set of tests for the `Config` class, this commit adds an initial set of tests for the `Config` class verifying that the `reportWidth` property is handled correctly.
Note: these tests have been set up to already be compatible with PR #3803, which widens the supported PHPUnit version.
:point_right: I have a separate commit ready for these tests for PHPCS 4.x as some changes are needed for PHPCS 4.x.
> Config: add tests for the `reportWidth` setting

- .github/workflows/manage-labels.yml
This is a quite straight-forward workflow to just remove some labels which should only be on open issues/open PRs and which should be removed once an issue or PR has been closed/merged.
Just attempting to reduce yet some more manual labour.
_N/A_
_N/A_
> GH Actions: automate some label management

- src/Files/File.php
- tests/Core/File/GetMethodParametersTest.inc
- tests/Core/File/GetMethodParametersTest.php
Follow up on PR #3516 which was included in PHPCS 3.7.0.
Turns out that constructor property promotion also allows for declaring properties with the `readonly` keyword, but without explicit visibility set. See: https://3v4l.org/nli62
Readonly properties without explicit visibility are already handled correctly in the `File::getMemberProperties()` method, but were not handled correctly in the `File::getMethodParameters()` method.
Fixed now.
Includes updated documentation and a unit test.
> File::getMethodParameters(): allow for readonly promoted properties without visibility

- package.xml
- src/Files/File.php
- tests/Core/File/GetClassPropertiesTest.inc
- tests/Core/File/GetClassPropertiesTest.php
PHP 8.2 introduces `readonly` classes. The `readonly` keyword can be combined with the `abstract` or `final` keyword. See: https://3v4l.org/VIXgD
Includes adding a full set of tests for the `File::getClassProperties()` method, which was so far untested.
Ref:
* https://wiki.php.net/rfc/readonly_classes
> PHP 8.2 | File::getClassProperties(): add support for readonly classes

- src/Standards/PSR1/Sniffs/Files/SideEffectsSniff.php
- src/Standards/PSR1/Tests/Files/SideEffectsUnitTest.1.inc
Ref:
* https://wiki.php.net/rfc/readonly_classes
Fixes #3727
> PHP 8.2 | PSR1/SideEffects: allow for readonly classes

- package.xml
- src/Standards/PSR12/Sniffs/Files/FileHeaderSniff.php
- src/Standards/PSR12/Tests/Files/FileHeaderUnitTest.18.inc
As reported in https://github.com/squizlabs/PHP_CodeSniffer/issues/3799#issuecomment-1532870980, the `FileHeader` sniff did not take the new PHP 8.2+ `readonly` OO modifier keyword into account.
Fixed now.
Includes test.
> PSR12/FileHeader: bug fix - false positives on PHP 8.2+ readonly classes

- .github/ISSUE_TEMPLATE/bug_report.md
This is a follow-up to https://github.com/squizlabs/PHP_CodeSniffer/pull/3829 based on the conversation therein following that being merged.
While the table looks good in a mono-spaced font, the input field on the new issue form in GitHub uses a variable width font, so the table doesn't line up nicely there. Having less white-space (and the lack of trailing pipe) should mean the information is easier to supply, and still displays nicely when rendered as Markdown.
_None required_
> Reduce width of table in issue template

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.php
Today I have seen an invalid `@param` tag in a docblock, and `Squiz.Commenting.FunctionComment` returned a PHP Fatal error while parsing the file. The error was:
```
There was 1 error:
1) PHP_CodeSniffer\Standards\Squiz\Tests\Commenting\FunctionCommentUnitTest::testSniff
Uninitialized string offset 0
/path/to/squizlabs-php-codesniffer/src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php:413
/path/to/squizlabs-php-codesniffer/src/Standards/PEAR/Sniffs/Commenting/FunctionCommentSniff.php:152
/path/to/squizlabs-php-codesniffer/src/Files/File.php:498
/path/to/squizlabs-php-codesniffer/src/Files/LocalFile.php:92
/path/to/squizlabs-php-codesniffer/tests/Standards/AbstractSniffUnitTest.php:173
/path/to/squizlabs-php-codesniffer/tests/TestSuite7.php:28
```
I have tracked this down, …
> Fix PHP Fatal error in `Squiz.Commenting.FunctionComment`

- package.xml
- src/Standards/PSR2/Docs/Files/ClosingTagStandard.xml
- src/Standards/PSR2/Docs/Methods/FunctionCallSignatureStandard.xml
- src/Standards/PSR2/Docs/Methods/FunctionClosingBraceStandard.xml
Thank you for providing a great tool.
I was looking into sniffs to create a coding standard for my project and it took me a long time to get to the `generator`.
I found some missing in the documentation and am submitting this PR.
Hope that helps.
- Added missing `PSR-2` documentation XML files.
> Added PSR-2 documentation XML files

- src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.1.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.1.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.2.inc.fixed
- src/Standards/Squiz/Tests/Arrays/ArrayDeclarationUnitTest.php
See #3557
`Squiz.Arrays.ArrayDeclaration.NoKeySpecified` doesn't accept the following snippet:
```php
$x = [
'foo' => 'bar',
...$baz,
];
```
It triggers an error as phpcs doesn't detect that the second entry is array unpacking.
```
Key specified for array entry; first entry has no key (Squiz.Arrays.ArrayDeclaration.KeySpecified)
``` 
The following (single line) array validates:
```php
$x = ['foo' => 'bar',  ...$baz];
```
`Squiz.Arrays.ArrayDeclaration.KeySpecified`: Allow array unpacking (`...$array`) in multi-line key-value array definitions.
Fixes #3557
- I did not. I'd be happy to, if you give me a pointer on how I can do this without breaking earlier PHP versions, given it's new syntax.
The one test failure for PHP 8.2 seems unrelated as it was already present in …
> Allow array unpacking in ArrayDeclaration multiline Sniff

- src/Standards/Squiz/Sniffs/PHP/InnerFunctionsSniff.php
- src/Standards/Squiz/Tests/PHP/InnerFunctionsUnitTest.inc
- src/Standards/Squiz/Tests/PHP/InnerFunctionsUnitTest.php
> Make InnerFunctionsSniff detect functions inside closures

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.php
This started as an auto-fix to remove ampersands from `@param` tags in docblocks within `Squiz.Commenting.FunctionComment`. This has evolved into "handle `@param` tags for variables passed by reference." We are also increasing test coverage of related-but-not-changed behaviour.
> Handle `@param` in docblock for variables passed by reference

- src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
The `Squiz.Commenting.FunctionComment.InvalidNoReturn` causes false positives when it encounters the `never` return type.
Tested this locally with:
```xml
<rule ref="Squiz.Commenting.FunctionComment.InvalidNoReturn"/>
```
```php
/**
* @return never
*/
private function foo()
{
throw new \RuntimeException('This method never returns');
}
```
> Fix `Squiz.Commenting.FunctionComment.InvalidNoReturn` false positive when return type is `never`

- src/Config.php
It fixes documentation of the command-line interface for the `filter` command.
`Change documentation of filter command to match internally used PascalCase`
Fixes #3877
> fix(docs): change filter arguments to match PascalCase

- src/Reports/Cbf.php
- src/Reports/Checkstyle.php
- src/Reports/Code.php
- src/Reports/Csv.php
- src/Reports/Diff.php
- src/Reports/Emacs.php
- src/Reports/Full.php
- src/Reports/Info.php
- src/Reports/Json.php
- src/Reports/Junit.php
- src/Reports/Notifysend.php
- src/Reports/Report.php
- src/Reports/Source.php
- src/Reports/Summary.php
- src/Reports/VersionControl.php
- src/Reports/Xml.php
The invalid phpdoc namespace fixed.
Fixes #
> Fix invalid namespace in phpdoc (\PHP_CodeSniffer\Files\File)

- package.xml
- src/Standards/Squiz/Sniffs/PHP/NonExecutableCodeSniff.php
- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.2.inc
- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.3.inc
- src/Standards/Squiz/Tests/PHP/NonExecutableCodeUnitTest.php
The following code snippet is currently flagging as `Squiz.PHP.NonExecutableCode.Unreachable`, but probably shouldn't.
```php
<?php if (true): ?>
<?php foreach ([] as $item): ?>
<?php continue; ?>
<?php endforeach; ?>
<?php endif; ?>
```
This pull request adds a check to avoid this snippet from being flagged as problematic.
> Squiz/NonExecutableCode: fix false positives when code goes in and out of PHP/HTML

- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.1.css
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.1.css.fixed
- src/Standards/Squiz/Tests/WhiteSpace/SuperfluousWhitespaceUnitTest.php
- src/Tokenizers/CSS.php
Yes, I know that the non-PHP tokenizers are going away in version 4.0. Meanwhile, the 3.x release line has a bug which can be fixed.
While working with `phpcbf`, I noticed that some LESS files (which are [parsed as CSS due to the specific ruleset being used](https://github.com/magento/magento-coding-standard/blob/v32/Magento2/ruleset.xml#L6)) had unexpected content injected into them.
```css
/* file: test.less */
// /**
//  * this is a comment
//  * this is also a comment
//  */
```
(Note the extra trailing newline at the end of the file.)
`phpcs --basepath=. -s --standard=Squiz --sniffs=Squiz.WhiteSpace.SuperfluousWhitespace --extensions=less/CSS test.less`
```
FILE: test.less
------------------------------------------------------------------------------------------------------------- …
```
> Fix bug in CSS tokenizer

- src/Standards/PEAR/Sniffs/Commenting/FunctionCommentSniff.php
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.inc.fixed
- src/Standards/PEAR/Tests/Commenting/FunctionCommentUnitTest.php
I have witnessed some complaints coming from `Squiz.Commenting.FunctionComment.SpacingAfter` which look like they could be trivially auto-fixed. This pull request adds auto-fixing for this particular complaint. I intend to investigate feasibility of auto-fixing other cases in this sniff another time.
Allow auto-fixing `...FunctionComment.SpacingAfter`
- New feature _(non-breaking change which adds functionality)_
> Auto-fix PEAR.Commenting.FunctionComment.SpacingAfter
