squizlabs/PHP_CodeSniffer

.travis.yml
Set sudo: false. This allows Travis use their new and faster
container-based infrastructure.
=> [TASK] Configure Travis for faster builds

CodeSniffer/DocGenerators/Markdown.php
Introduce a generator which produces documentation in Markdown format.
=> [FEATURE] Add markdown generator

CodeSniffer.php
=> Check if Sniff is abstract before registering it

CodeSniffer/Standards/Squiz/Tests/CSS/ClassDefinitionClosingBraceSpaceUnitTest.css, CodeSniffer/Tokenizers/CSS.php
I have this 8000 lines generated CSS file and seems to send PHPCS into an endless loop. Not sure what is causing this, but here is a test case as a start. So this should send the Travis CI test into some kind of timeout.
=> Long CSS file performance issue because array_values() is very slow

CodeSniffer/Tokens.php
- see documentation at: http://php.net/declare
=> Add declare as a scope and parenthesis opener

CodeSniffer/File.php
Follow up to pull request #639
=> Suppress iconv_strlen error

CodeSniffer/File.php
Function description was mentioned as "Returns the position of the next token" for function findPrevious()
=> Update to comments for function findPrevious()

CodeSniffer/CLI.php
=> Add junit to list of valid report formats

CodeSniffer/CLI.php
Update return type to match the function defination.
=> Update CLI.php - Update return type to match the function defination.

CodeSniffer/File.php
=> Update File.php - possibly unused variables

CodeSniffer/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php, CodeSniffer/Standards/Squiz/Tests/Commenting/FunctionCommentUnitTest.inc
=> Makes "Squiz.Commenting.FunctionComment" sniff understand description in "@return" tag

src/Tokenizers/PHP.php
Correct token is `T_HASHBANG`.
=> Fix comment typo

CodeSniffer/Standards/Generic/Sniffs/Formatting/DisallowMultipleStatementsSniff.php, CodeSniffer/Standards/Generic/Tests/Formatting/DisallowMultipleStatementsUnitTest.inc
=> Fix DisallowMultipleStatements not working with <?=

CodeSniffer/Standards/Squiz/Sniffs/Operators/IncrementDecrementUsageSniff.php, CodeSniffer/Standards/Squiz/Tests/Operators/IncrementDecrementUsageUnitTest.inc
=> fix for issue 1181

scripts/phpcs-svn-pre-commit
Same way as scripts/phpcs and scripts/phpcbf do.
=> Svn-pre-commit hook: use env in shebang

CodeSniffer/File.php
Example:
```php
<?php
class MyClass
{
use MyTrait;
use AnotherTrait {
AnotherTrait::method as methodAlias;
}
}
```
Current tokens (wrong) - check tokens `8` and `14`:
```
Array
(
[0] => Array
(
[type] => T_OPEN_TAG
[code] => 379
[content] => <?php
[line] => 1
[column] => 1
[length] => 5
[level] => 0
[conditions] => Array
(
)
)
[1] => Array
(
[code] => 361
[type] => T_CLASS
[content] => class
[line] => 2
[column] => 1
[length] => 5
[scope_condition] => 1
[scope_opener] => 5
[scope_closer] => 33
[level] => 0
[conditions] => Array
(
)
)
[2] => Array
(
[code] => 382
[type] => T_WHITESPACE
[content] =>  
[line] => 2
[column] => 6
[length] => 1
[level] => 0
[conditions] => Array
(
)
)
[3] => Array
(
[content] => MyClass
[code] => 319
[type] => T_STRING
[line] => 2
[column] => 7
[length] => 7 …
```
=> A mix of USE statements with and without braces can cause the tokenizer to mismatch brace tokens

CodeSniffer/Standards/Generic/Sniffs/NamingConventions/CamelCapsFunctionNameSniff.php, CodeSniffer/Standards/Generic/Tests/NamingConventions/CamelCapsFunctionNameUnitTest.inc, CodeSniffer/Standards/Generic/Tests/NamingConventions/CamelCapsFunctionNameUnitTest.php, CodeSniffer/Standards/PEAR/Sniffs/NamingConventions/ValidFunctionNameSniff.php, CodeSniffer/Standards/PEAR/Tests/NamingConventions/ValidFunctionNameUnitTest.inc, CodeSniffer/Standards/PEAR/Tests/NamingConventions/ValidFunctionNameUnitTest.php
=> NamingConventions FunctionName sniffs: Add anonymous class support.

CodeSniffer/Standards/Generic/Sniffs/Metrics/NestingLevelSniff.php
=> NestingLevel: minor documentation fix.

CodeSniffer/Standards/PEAR/Sniffs/NamingConventions/ValidClassNameSniff.php, CodeSniffer/Standards/PEAR/Tests/NamingConventions/ValidClassNameUnitTest.inc, CodeSniffer/Standards/PEAR/Tests/NamingConventions/ValidClassNameUnitTest.php, CodeSniffer/Standards/Squiz/Sniffs/Classes/ValidClassNameSniff.php, CodeSniffer/Standards/Squiz/Tests/Classes/ValidClassNameUnitTest.inc, CodeSniffer/Standards/Squiz/Tests/Classes/ValidClassNameUnitTest.php
=> ValidClassName sniffs: Add trait support.

CodeSniffer/Standards/Squiz/Sniffs/WhiteSpace/ObjectOperatorSpacingSniff.php
The separate functions make life easier if you want to extend the class and do additional checks.
=> Refactor the spacing around the object operator into separate functions

CodeSniffer/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc, CodeSniffer/Standards/Squiz/Tests/ControlStructures/ControlSignatureUnitTest.inc.fixed
My code had this error, sorry for this. it also removes extra variable declaration.
=> fixes missing variable declaration in test coverage

CodeSniffer/Standards/Generic/Sniffs/Debug/ESLintSniff.php
=> Add ESLint sniff

src/Sniffs/AbstractVariableSniff.php, src/Standards/Zend/Sniffs/NamingConventions/ValidVariableNameSniff.php
Not much to see here... minor changes mainly CS.
=> Fix some CS and docblocks

src/Sniffs/AbstractScopeSniff.php, src/Sniffs/AbstractVariableSniff.php, src/Sniffs/Sniff.php, tests/AllTests.php, tests/Core/AllTests.php, tests/Core/File/FindExtendedClassNameTest.php, tests/Core/File/FindImplementedInterfaceNamesTest.php, tests/Core/File/GetMethodParametersTest.php, tests/Standards/AbstractSniffUnitTest.php, tests/Standards/AllSniffs.php, tests/TestSuite.php
=> Fix docblocks about old PHP_Codesniffer_File

src/Tokenizers/PHP.php
=> Added missing scope_* values with T_START_NOWDOC token

src/Standards/Generic/Sniffs/ControlStructures/InlineControlStructureSniff.php, src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.inc, src/Standards/Generic/Tests/ControlStructures/InlineControlStructureUnitTest.inc.fixed
=> Allow comments between body and condition in do while loops.

src/Standards/Generic/Sniffs/Files/OneObjectStructurePerFileSniff.php, src/Standards/Generic/Tests/Files/OneObjectStructurePerFileUnitTest.inc, src/Standards/Generic/Tests/Files/OneObjectStructurePerFileUnitTest.php
That sounded interesting and I thought that I could help here.
closes #1627
=> Added new sniff that checks about multiple Class/Interface/Trait on a file

src/Standards/Generic/Sniffs/PHP/LowerCaseKeywordSniff.php, src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc, src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.inc.fixed, src/Standards/Generic/Tests/PHP/LowerCaseKeywordUnitTest.php
- function (closure)
- parent
- self
- yield
- yield from
=> [3.0] Added missing lowercase keywords

src/Config.php
As per https://github.com/squizlabs/PHP_CodeSniffer/issues/1566#issuecomment-335034128
=> Config: give `phpcs.xml` priority over `.phpcs.xml.dist`

src/Standards/Generic/Docs/Arrays/DisallowLongArraySyntaxStandard.xml, src/Standards/Generic/Docs/Arrays/DisallowShortArraySyntaxStandard.xml
Hi,
Filling in some blanks on the documentation.
Let me know if you want me to change anything, I have some more to do, but wanted any feedback first.
Thx
=> Add generator docs for Generic.Arrays

CodeSniffer/Standards/Generic/Sniffs/CodeAnalysis/EmptyStatementSniff.php, CodeSniffer/Standards/Squiz/Sniffs/ControlStructures/ControlSignatureSniff.php, CodeSniffer/Standards/Squiz/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, CodeSniffer/Standards/Squiz/Tests/WhiteSpace/ControlStructureSpacingUnitTest.inc
This PR Backports the Fixed bug #1890 from eefb31c
=> Backport Fixed bug #1890 to 2.9.x

src/Generators/Generator.php, src/Reports/Diff.php, src/Sniffs/AbstractArraySniff.php, src/Sniffs/AbstractPatternSniff.php, src/Sniffs/AbstractVariableSniff.php, src/Standards/Generic/Sniffs/Arrays/ArrayIndentSniff.php, src/Standards/Generic/Sniffs/Formatting/SpaceAfterNotSniff.php, src/Standards/PEAR/Sniffs/Functions/ValidDefaultValueSniff.php, src/Standards/Squiz/Sniffs/Arrays/ArrayBracketSpacingSniff.php, src/Standards/Squiz/Sniffs/CSS/ClassDefinitionClosingBraceSpaceSniff.php, src/Util/Cache.php, src/Util/Common.php, tests/AllTests.php, tests/Standards/AllSniffs.php
Just cleanup some unused code - to keep my IDE quiet and happy :)
=> Remove unused use statements

src/Runner.php, src/Standards/Generic/Sniffs/PHP/DisallowAlternativePHPTagsSniff.php, src/Standards/Generic/Tests/Files/OneTraitPerFileUnitTest.php, src/Standards/Generic/Tests/PHP/DisallowShortOpenTagUnitTest.php, src/Standards/PSR1/Tests/Classes/ClassDeclarationUnitTest.php
=> Removed old PHP version checks

src/Standards/Squiz/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php, src/Standards/Squiz/Sniffs/WhiteSpace/FunctionClosingBraceSpaceSniff.php
=> Avoid calling File::hasCondition() twice

src/Files/LocalFile.php, src/Standards/PSR12/Sniffs/Operators/OperatorSpacingSniff.php, src/Standards/Squiz/Sniffs/Scope/MemberVarScopeSniff.php, src/Util/Cache.php
Together with PHPStorm and https://github.com/kalessil/phpinspectionsea, here are some improvements that we can make to PHP_CodeSniffer :smile:
=> Improvements

src/Standards/Squiz/Sniffs/Commenting/VariableCommentSniff.php, src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc, src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.inc.fixed, src/Standards/Squiz/Tests/Commenting/VariableCommentUnitTest.php
=> Fixes suggested variable type with single-line comment

package.xml, src/Standards/Generic/Sniffs/VersionControl/GitMergeConflictSniff.php, src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.1.css, src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.1.inc, src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.2.css, src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.2.inc, src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.3.inc, src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.4.inc, src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.5.inc, src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.6.inc, src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.js, src/Standards/Generic/Tests/VersionControl/GitMergeConflictUnitTest.php
New sniff to detect merge conflict artifacts left in files.
=> New Generic.VersionControl.GitMergeConflict sniff

phpcs.xsd, src/Ruleset.php
Implementation for #2153.
Since Ruleset is untested, I didn't add any tests (please advice if you need some), only tested this in our consuming packages.
=> Support property-level extending for array properties

src/Files/File.php, src/Sniffs/AbstractScopeSniff.php, src/Sniffs/AbstractVariableSniff.php, src/Standards/Generic/Tests/CodeAnalysis/AssignmentInConditionUnitTest.inc, src/Standards/Squiz/Sniffs/WhiteSpace/FunctionSpacingSniff.php, src/Tokenizers/PHP.php, src/Tokenizers/Tokenizer.php, src/Util/Tokens.php, tests/Core/File/FindEndOfStatementTest.php
=> Various documentation fixes

src/Standards/PSR2/ruleset.xml
Fix PSR2.Files.ClosingTag name reference.
=> PSR2 rulesets: improve inline documentation

package.xml
=> Correction to "extend" property name in release notes

package.xml
=> Typos in Release Notes of 3.4.0v

package.xml, src/Standards/Squiz/Sniffs/CSS/OpacitySniff.php, src/Standards/Squiz/Tests/CSS/OpacityUnitTest.css.fixed, src/Standards/Squiz/Tests/CSS/OpacityUnitTest.php
While I was at it, I've reviewed the sniff and applied any improvements I could think of:
* The sniff did not take comments or PHPCS annotations into account.
=> Squiz.CSS.Opacity: add fixed file and minor improvement

package.xml, src/Standards/Squiz/Sniffs/WhiteSpace/FunctionOpeningBraceSpaceSniff.php, src/Standards/Squiz/Tests/WhiteSpace/FunctionOpeningBraceSpaceUnitTest.inc.fixed, src/Standards/Squiz/Tests/WhiteSpace/FunctionOpeningBraceSpaceUnitTest.js.fixed, src/Standards/Squiz/Tests/WhiteSpace/FunctionOpeningBraceSpaceUnitTest.php
The sniff contains fixers, but didn't have `fixed` files.
While I was at it, I've done a cursory review of the sniff and have added some additional unit test files for situations, so far, untested.
Includes removing some redundant code from the unit test file.
=> Squiz/FunctionOpeningBraceSpace: add missing fixed files + some extra unit tests

src/Fixer.php, src/Runner.php, src/Sniffs/AbstractArraySniff.php, src/Standards/Generic/Sniffs/NamingConventions/UpperCaseConstantNameSniff.php, src/Standards/Generic/Tests/CodeAnalysis/ForLoopShouldBeWhileLoopUnitTest.inc, src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.inc, src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.inc.fixed, src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.js, src/Standards/Generic/Tests/Commenting/DocCommentUnitTest.js.fixed, src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.js, src/Standards/Generic/Tests/Formatting/MultipleStatementAlignmentUnitTest.js.fixed, src/Standards/Generic/Tests/Metrics/CyclomaticComplexityUnitTest.inc, src/Standards/MySource/Tests/Objects/CreateWidgetTypeCallbackUnitTest.js, src/Standards/PSR2/Sniffs/Methods/FunctionClosingBraceSniff.php, src/Standards/Squiz/Sniffs/Arrays/ArrayDeclarationSniff.php, src/Standards/Squiz/Sniffs/WhiteSpace/SuperfluousWhitespaceSniff.php, src/Standards/Squiz/Tests/ControlStructures/InlineIfDeclarationUnitTest.php, src/Standards/Zend/Sniffs/Debug/CodeAnalyzerSniff.php, src/Tokenizers/PHP.php, src/Tokenizers/Tokenizer.php, tests/Core/ErrorSuppressionTest.php, tests/Core/File/FindEndOfStatementTest.php, tests/Core/File/FindExtendedClassNameTest.php, tests/Core/File/FindImplementedInterfaceNamesTest.php, tests/Core/File/GetMemberPropertiesTest.php, tests/Core/File/IsReferenceTest.php
IMO these are not intentional typos for unit tests.
=> Various typos

scripts/ValidatePEAR/FileList.php, src/Runner.php, src/Sniffs/AbstractVariableSniff.php, src/Standards/Generic/Sniffs/Functions/FunctionCallArgumentSpacingSniff.php, src/Standards/Squiz/Sniffs/Commenting/FunctionCommentSniff.php, src/Standards/Squiz/Sniffs/Commenting/InlineCommentSniff.php, src/Standards/Squiz/Sniffs/WhiteSpace/SuperfluousWhitespaceSniff.php, src/Util/Common.php
=> Minor documentation fixes

package.xml, src/Standards/PSR1/Docs/Methods/CamelCapsMethodNameStandard.xml
Created PSR1.Methods.CamelCapsMethodName docs for completeness.
=> Added documentation to PSR1.Methods.CamelCapsMethodName sniff

package.xml, src/Standards/Generic/Docs/Files/OneObjectStructurePerFileStandard.xml, src/Standards/Generic/Docs/Files/OneTraitPerFileStandard.xml
Complete Generic Files documentation.
=> Added docs for OneObjectStructurePerFile and OneTraitPerFile sniffs

src/Standards/Squiz/Sniffs/Operators/IncrementDecrementUsageSniff.php
... rather than post in/decrement.
Fixes #2354
=> Squiz/IncrementDecrementUsage: suggest pre-in/decrement

src/Standards/PSR2/Sniffs/Classes/ClassDeclarationSniff.php
=> Allow trailing comma in multi line function calls

src/Standards/Generic/Sniffs/CodeAnalysis/EmptyPHPStatementSniff.php, src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.inc, src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.inc.fixed, src/Standards/Generic/Tests/CodeAnalysis/EmptyPHPStatementUnitTest.php
See https://github.com/squizlabs/PHP_CodeSniffer/issues/2493
=> Add more check for emptyPhpStatement

src/Standards/PSR12/Sniffs/Functions/ReturnTypeDeclarationSniff.php, src/Standards/PSR12/Tests/Functions/ReturnTypeDeclarationUnitTest.inc, src/Standards/PSR12/Tests/Functions/ReturnTypeDeclarationUnitTest.inc.fixed, src/Standards/PSR12/Tests/Functions/ReturnTypeDeclarationUnitTest.php
=> Adds PHP 7.4 fn closure surrpot in PSR12.Functions.ReturnTypeDeclaration

src/Standards/Squiz/Sniffs/Functions/FunctionDeclarationArgumentSpacingSniff.php, src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.inc, src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.inc.fixed, src/Standards/Squiz/Tests/Functions/FunctionDeclarationArgumentSpacingUnitTest.php
=> Adds support for array closures in Squiz.Functions.FunctionDeclarationArgumentSpacing

src/Standards/Generic/Sniffs/CodeAnalysis/UnusedFunctionParameterSniff.php, src/Standards/Generic/Tests/CodeAnalysis/UnusedFunctionParameterUnitTest.inc, src/Standards/Generic/Tests/CodeAnalysis/UnusedFunctionParameterUnitTest.php
=> Adds support for array closures in Generic.CodeAnalysis.UnusedFunctionParameter

src/Standards/PSR12/Sniffs/ControlStructures/BooleanOperatorPlacementSniff.php, src/Standards/PSR12/Tests/ControlStructures/BooleanOperatorPlacementUnitTest.inc, src/Standards/PSR12/Tests/ControlStructures/BooleanOperatorPlacementUnitTest.inc.fixed, src/Standards/PSR12/Tests/ControlStructures/BooleanOperatorPlacementUnitTest.php
Fix https://github.com/squizlabs/PHP_CodeSniffer/issues/2620
=> Add option allowOnly

src/Standards/PSR12/Sniffs/Traits/UseDeclarationSniff.php, src/Standards/PSR12/Tests/Traits/UseDeclarationUnitTest.inc, src/Standards/PSR12/Tests/Traits/UseDeclarationUnitTest.inc.fixed, src/Standards/PSR12/Tests/Traits/UseDeclarationUnitTest.php
Fix https://github.com/squizlabs/PHP_CodeSniffer/issues/2790
=> Fix use declaration

src/Standards/Generic/Sniffs/WhiteSpace/ArbitraryParenthesesSpacingSniff.php, src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.inc, src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.inc.fixed, src/Standards/Generic/Tests/WhiteSpace/ArbitraryParenthesesSpacingUnitTest.php
Fix https://github.com/squizlabs/PHP_CodeSniffer/issues/2826
=> [Bugfix] Handle parenthesis after scope condition closer

src/Standards/PEAR/Sniffs/Functions/FunctionCallSignatureSniff.php
=> [PEAR.Functions.FunctionCallSignatureSniff] Add consistency in the errors message

src/Standards/PEAR/Sniffs/Functions/FunctionCallSignatureSniff.php, src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.inc, src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.inc.fixed, src/Standards/PEAR/Tests/Functions/FunctionCallSignatureUnitTest.php
Close https://github.com/squizlabs/PHP_CodeSniffer/issues/2877
=> [FunctionCallSignatureSniff] Handle array of function

src/Standards/Squiz/Sniffs/WhiteSpace/OperatorSpacingSniff.php, src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc, src/Standards/Squiz/Tests/WhiteSpace/OperatorSpacingUnitTest.inc.fixed
=> Squiz.WhiteSpace.OperatorSpacing false positive when exiting with negative number

src/Files/File.php, src/Fixer.php, src/Standards/Generic/Sniffs/CodeAnalysis/UnconditionalIfStatementSniff.php, src/Tokenizers/PHP.php, tests/Core/File/IsReferenceTest.php
=> Various minor documentation fixes

src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.1.inc.fixed, src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.1.js.fixed
The regular annual update to make sure the build still passes ;-)
=> FileComment: update year in test file

src/Config.php, src/Reports/Code.php, src/Standards/Generic/Tests/Files/ExecutableFileUnitTest.php, src/Tokenizers/PHP.php, src/Util/Common.php
Replace a nested function call with a singular function call, which does the same.
=> QA: minor code simplification

.github/workflows/validate.yml
Fix failing installation of the xmllint tooling.
=> GH Actions/CS: fix build failure

src/Files/File.php, src/Sniffs/AbstractArraySniff.php, src/Standards/Generic/Sniffs/PHP/DisallowRequestSuperglobalSniff.php, src/Standards/PSR12/Sniffs/Classes/AnonClassDeclarationSniff.php, src/Standards/Squiz/Sniffs/Scope/StaticThisUsageSniff.php, src/Tokenizers/PHP.php, src/Util/Common.php, tests/Core/Autoloader/DetermineLoadedClassTest.php, tests/Core/File/FindStartOfStatementTest.php, tests/Core/Tokenizer/AttributesTest.php
=> Documentation: various minor fixes

src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.1.inc.fixed, src/Standards/Squiz/Tests/Commenting/FileCommentUnitTest.1.js.fixed
The regular annual update to make sure the build still passes ;-)
Happy 2023!
=> FileComment: update year in test files
